#!/bin/bash

# Set environment values
. $HOME/bin/adp_environment_qtrly
program=`basename $0`

echo -e "\nBegin processing for `whoami` outbound processing"
cd $outbound_dir
	let filecount=0
	find . -type f -name "*.tag" | while read FILE1
	do
		let filecount=filecount+1

		echo "-Processing loop $filecount Tag file: $FILE1 -------------------------------------------------"
		rm -fv $FILE1
		export filepref=`echo $FILE1 | sed -e 's/.tag//'`
		export filename=`ls -1 ${filepref}.*`
		export pgpfile=${filename}.pgp
		outbound   #Outbound file function
	done

archive_clean $outbound_archive aag1 $FileAge

echo -e "\nEnd of `whoami` outbound processing"

Mail -s "ADP Outbound File(s)" $wc_mailto < $UNISON_STDLIST
