#!/bin/bash

# Check for and then archive the ADP data file(s)

# Set environment values
. $HOME/bin/adp_environment
program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
proper syntax is: process_adp_data direction where
direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        inlien)

echo -e "\nBegin processing for `whoami` inbound processing"

        echo "\nThis is for the lien file"
	export filepref=aag*.grn*   #pgp file.  Missing extension
        export datafile=tfwgld.dat 
        export tagfile=tfwgld.tag
inbound
echo -e "\nend processing for `whoami` lien files"

#echo -e "\nemail to HCM team the stdlist for this job"
Mail -s "ADP Inbound Lien File" $wc_mailto < $UNISON_STDLIST

;;

	inPQQ)
        echo "\nThis is for the PQQ file"
	export filepref=AAG1*.PREQ.PQQ* #pgp file.  Missing extension
        export datafile=tfwgpqq_req.dat 
        export tagfile=tfwgpqq_req.tag
inbound
echo -e "\nend processing for `whoami` PQQ files"

#echo -e "\nemail to HCM team  the stdlist for this job"
Mail -s "ADP Inbound PQQ File" $wc_mailto < $UNISON_STDLIST

        ;;

        out)

echo -e "\nBegin processing for `whoami` outbound processing"
cd $hcmdir_out
	let filecount=0
	find . -type f -name "*.tag" | while read FILE1
	do
		let filecount=filecount+1

		echo "-Processing loop $filecount Tag file: $FILE1 -------------------------------------------------"
		rm -fv $FILE1
		export filepref=`echo $FILE1 | sed -e 's/.tag//'`
		export filename=`ls -1 ${filepref}.*`
		export pgpfile=${filename}.pgp
		outbound   #Outbound file function
	done

archive_clean $outbound_archive aag1 $FileAge

archive_clean $done_dir AAG1 $FileAge

echo -e "\nEnd of `whoami` outbound processing"

#echo -e "\nemail to HCM team  the stdlist for this job"
Mail -s "ADP Outbound File(s)" $wc_mailto < $UNISON_STDLIST

        ;;

esac
