#!/bin/bash

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export info_to="production.services@alaskaair.com"
#export mail_to="mlr.alerts@alaskaair.com"
export nofiledate=`/bin/date "+%A, %D"`
FileAge=30

. /opt/local/ops_scripts/function_lib

export airline=$1

	if [ -z $airline ]; then
echo -e "\n	Missing direction parm.
	proper syntax is: process_aerdata_in airline
	where airline equals AS or QX\n"
	exit 4
	fi

function inproc {

cd $inbound_dir

	ls -1 ${filepref}* | while read File1
	do
echo -e "\nprocessing Aerdata $File1"

securezip $File1 inbound
ftp_file $ftp_local_host $File1 $File1 "cd $filedir"
rm -fv $File1 

	done

archive_clean $inbound_archive $filepref $FileAge

}

case $airline in

	AS)
export filedir=me_aerdata/AS/me_business/from_aerdata
export filepref=Alask
inproc
;;
	QX)
export filedir=me_aerdata/QX/qx_me_business/qx_from_aerdata
export filepref=Horizon
inproc
;;

*)

echo -e "\nargument is missing or invalid, 
need to pass one of the following arguments:
AS or QX"

exit 4
;;

esac
