#!/bin/bash

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export info_to="production.services@alaskaair.com"
export dom=alaskaair.com
#export mail_to="ics.me.log@alaskaair.com"
export mail_to="jeff.peerson@$dom"
export nofiledate=`/bin/date "+%A, %D"`
export FileAge=30

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

ls -1 | while read FILE1
	do
export namechk=`echo $FILE1 | wc | awk '{print $2}'`

	if [ $namechk -gt 1 ]; then
export newname=`echo $FILE1 | sed -e 's/ /_/g'`
echo -e "\nrenaming $FILE1 to $newname"
mv "$FILE1" $newname
else
export newname=$FILE1
	fi

securezip $newname outbound
rm -fv $newname
	done

function outproc {

echo -e "\nget files on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd $filedir
	dir
      	mget *.*
	cd $filedir1
	dir
	mget *.*
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$

echo -e "\nprocessing $airline aerdata files"

echo -e "\nArchive file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "$archdir"
        mput ${filepref}*.*
        quit
GETDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "Archive of file $File1 on $ftp_local_host failed" | Mail -s "$program failure" $mail_to_error
	cat ftp_results.$$
	rm ftp_results.$$
	fi

cat ftp_results.$$
rm ftp_results.$$

echo -e "\nDelete files on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "$filedir"
        mdel ${filepref}*.*
	mdel ftp*.*
	cd "$filedir1"
	mdel ${filepref}*.*
        quit
GETDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "Delete of files on $ftp_local_host failed" | Mail -s "$program failure" $mail_to_error
	cat ftp_results.$$
	rm ftp_results.$$
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

find $outbound_archive -mtime +7 | xargs rm -fv

}

export airline=AS
export filedir=ME_Aerdata/$airline
export filedir1=/ME_Aerdata/$airline/ME_Business
export archdir=/${filedir}/archive
outproc

export airline=QX
export filedir=ME_Aerdata/$airline
export filedir1=/ME_Aerdata/$airline/QX_ME_Business
export archdir=/${filedir}/QX_Archive
export filepref=HOR
outproc

echo -e "\nsend email to Jeff Peerson that files have been put on the sever"
ls -1 | Mail -s "File(s) are available for aerdata on the external FTP server" $mail_to
