#!/bin/bash

# Set up the aeromex data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/aeromex_environment"

export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
#export lz=mptest
export lz=mpprod
export infile_pref=FFPAMAS
export local_file=aeromexico_out.txt
export solar_file=AMAEROMEXICOPIT.txt
export partner_file=FFPASAMY
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=systems.mamangement@alaskaair.com
#export datestamp=`/bin/date +%Y%M%D`
export datestamp=`/bin/date +%Y%m%d`
export nofiledate=`/bin/date "+%A, %D"`
export FileAge=30

. /opt/local/ops_scripts/function_lib

function inbound {

cd $inbound_dir

export data_file=`ls -1 $infile_pref*`
records=`wc $data_file | awk '{print $2}'`

echo -e "\n$data_file file ($records records) received at `date`"

securezip $data_file inbound

echo -e "\nrename $data_file to $solar_file"
mv -fv $data_file $solar_file

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $solar_file

echo -e "\ncleaning up inbound directory"
rm -f $solar_file

archive_clean $inbound_archive $infile_pref $FileAge

}

function outbound {

cd $outbound_dir

echo -e "\nremove files older than 20 days from outbound"
find . -mtime +20 | xargs rm -v

echo -e "\nmake record length 200 for all records"
$HOME/bin/200.pl $local_file >$partner_file$datestamp.txt

	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact EPS"
	exit 4
	fi

securezip $local_file outbound

echo -e "remove $local_file file in outbound"
rm -fv $local_file 

archive_clean $outbound_archive $local_file $FileAge

}
