#!/bin/bash

export sftp_host=alaskaair@216.127.152.39
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export partner=RM
export lzout_dir=scheduling/RM/IndSSIM
export lzout_archive=scheduling/RM/IndSSIM/Archive
export data_file=oagindustry.sim
export mail_to="ysapir@airfacts.com"
export sentdate=`/bin/date "+%Y%m%d"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
#export tagfile=${data_file}.$sentdate.done
export FileAge=10

export program=`basename $0`

. /opt/local/ops_scripts/function_lib


cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\nftp get $data_file from $ftp_local_host\n"
	ftp -v -i $ftp_local_host <<MGET >ftp_results.$$
	cd $lzout_dir
	dir
	mget $data_file
	bye
MGET
	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP get of $data_file file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

#touch $tagfile

zip $data_file.zip $data_file


securezip $data_file outbound

echo -e "\nput $data_file to $sftp_host"
	sftp -v $sftp_host <<PUTDATA >ftp_results.$$
        cd incoming
  	put ${data_file}.zip ${data_file}$sentdate.zip 
	ls -l
	quit
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $data_file to Airfacts"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$


echo -e "\nemail to Airfacts that the OAg file is on thier site"
Mail -s "The IndSSIM OAG file is now on your server" $mail_to </dev/null


#lz archive
ftp_file $ftp_local_host $data_file $data_file.$sentdate "cd $lzout_archive"

#lz clean up
ftp_delete $ftp_local_host $data_file "cd $lzout_dir"


rm -fv $data_file ${data_file}.zip
rm -fv ftp_results.$$


