#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export partner=Airfacts
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export namebase=asoag
export maildom=alaskaair.com
export maillist=dean.liebrich@$maildom
#export maillist="ASQX.ScheduleDistribution@maildom"
export sentdate=`/bin/date "+%Y%m%d_%H%M"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7

export program=`basename $0`

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

sleep 60

ftp_check $ftp_local_host

echo -e "\nftp get $namebase file from $ftp_local_host\n"
	ftp -v -i $ftp_local_host <<MGET >ftp_results.$$
	cd $lzout_dir
	dir
	mget ${namebase}*
	bye
MGET
	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP get of $namebase file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

export sim_file=`ls -1 ${namebase}*`
export arch_name=`echo $sim_file | sed -e 's/.txt//'`
export relmo=`echo $sim_file | cut -c6-7`
export relday=`echo $sim_file | cut -c8-9`

securezip $sim_file outbound

echo -e "\nsend mail to $maillist with file $sim_file attached"
echo -e "Please see attached SSIM file for the ${relmo}-${relday}-`date +%Y` release date." | mutt -s "ASQX SSIM File for $partner ${relmo}-${relday}-`date +%Y`" -a $sim_file $maillist

echo "SSIM file $sim_file was emailed from AS to $partner on $maildate" | Mail -s "$partner SSIM file" $maillist

ftp_file $ftp_local_host $sim_file ${arch_name}_$sentdate.txt "cd $lzout_archive"

ftp_delete $ftp_local_host $sim_file "cd $lzout_dir

echo "remove file $sim_file
rm -fv $sim_file

archive_clean $outbound_archive $namebase $FileAge

