#!/bin/bash

# Check for and then archive the Air Pacific data file
#
# Set environment values

. $HOME/bin/airpacific_environment
program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_airpacfic_data direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        IN)

export data_pgp_file=fjmile.gpg
echo -e "\nBegin processing for Air Pacific inbound file"
airpac_in
echo -e "\nEnd of `whoami` inbound processing"

        ;;

esac
