#!/bin/sh

# script to process Alamo Rental Car data

		

export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export data_file=alaska_al.air.dat
export local_file=ALALAMOCARPIT.txt
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14

. /opt/local/ops_scripts/function_lib



cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

records=`wc -l $data_file | awk '{print $1}'`
	
	if [ $records -eq 0 ]; then
	echo "Alamo data file ($data_file) is empty"
	exit 4
	fi

echo -e "\n`whoami` file ($records records) received at `date`"

mv $data_file $local_file

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nclean up $inbound_dir"
rm -f $local_file $data_file

#ftp_rename $ftp_host $rem_file $rem_old_file

archive_clean $inbound_archive $local_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"

