#!/bin/bash

program=`basename $0`

. $HOME/bin/amadeus_psmc_environment

export direction=$1

#make sure direction parm was passed as first arg
	if [ -z $direction ]; then
echo -e "\n Missing direction parm.  Proper syntax
is get_amadeus_data in, where direction
is equal to in."
	exit 4
	fi

case "$direction" in
 in)
	export export ftp_local_host=asprodftp
        export file_prefix=NOSHOWAS*.TXT
	export ftpmode=ascii 
amadeusin
	export ftp_local_host=asprodftp
        export file_prefix=QREVSDATA*.CSV
	export ftpmode=ascii
amadeusin
	export ftp_local_host=asprodftp
        export file_prefix=CancelText*.ZIP
	export ftpmode=bin
amadeusin

;;

esac

#Mail -s "Files picked up from amadeus for $file_prefix" $mailto </dev/null
