#!/bin/bash

set -x

export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export sftp_host=as-qx@ari.lcl@sftp.amadeusri.com
export dom=alaskaair.com
export maillist="CRC.Alerts@$dom"
export datestamp=`date +%Y%m%d`
export logdate=`date +%Y%m%d.%H%M`
export FileAge=10

ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

export fileprefix=$1

#make sure job parm was passed as first arg
	if [ -z $fileprefix ]; then
echo -e "\n Missing job parm.  Proper syntax
is put_amadeus_files, where files
is equal to aag or tsa or ..."
	exit 4
	fi

cd $outbound_dir

echo -e "\ncheck for connectivity to $sftp_host"
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	quit
PUT

export ftpcheck=`grep -ci "sftp\>" ftp_results.$$`

	if [ $ftpcheck -lt 1 ]; then
echo -e "\nConnection to $sftp_host failed, check for
connectivity and/or contact `whoami` to see why then rerun.\n"
cat ftp_results.$$
rm -fv ftp_results.$$
	exit 4
	fi

rm -fv ftp_results.$$

export tag_file=`ls -1 ${fileprefix}.tag`
export zip_file=`ls -1 ${fileprefix}.zip`
      
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	cd AS-QX/TSA
	put $zip_file
        dir
	quit
PUT
	result=$?

      if [ $result -ne 0 ]; then
      echo -e "\nput $zip_file to $sftp_host failed"
	echo "contents of $outbound_dir:"
	ls -l $outbound_dir
       exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

securezip $zip_file outbound

rm -fv $tag_file

ls -1 |Mail -s "File(s) were sent to Amadeus on $logdate" $maillist

rm -fv $zip_file 

archive_clean $outbound_archive $fileprefix $FileAge
