#!/bin/bash

set -x

export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export sftp_host=as-qx@ari.lcl@sftp.amadeusri.com
export ftp_host=asprodftp
export source_dir=\\seavvfile1\ftpprod\rev_acctg\AS_TO_BA
export data_file=AS2BAUSG.DAT
export dom=alaskaair.com
#export maillist="CRC.Alerts@$dom"
export maillist=dean.liebrich@$dom
export datestamp=`date +%Y%m%d`
export logdate=`date +%Y%m%d.%H%M`
export FileAge=10

ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

ftp_check $ftp_host

echo -e "\ncheck for connectivity to $sftp_host"
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	quit
PUT

export ftpcheck=`grep -ci "sftp\>" ftp_results.$$`

	if [ $ftpcheck -lt 1 ]; then
echo -e "\nConnection to $sftp_host failed, check for
connectivity and/or contact `whoami` to see why then rerun.\n"
cat ftp_results.$$
rm -fv ftp_results.$$
	exit 4
	fi

rm -fv ftp_results.$$

ftp_vendor_get $ftp_host $data_file $data_file "cd rev_acctg/AS_to_BA"

securezip $data_file outbound

#export zip_file=`echo $data_file | sed -e '/dat/zip//'`
      
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	cd AS-QX/incoming
	put $data_file
        dir
	quit
PUT
	result=$?

	if [ $result -ne 0 ]; then
        echo -e "\nput $data_file to $sftp_host failed"
	echo "contents of $outbound_dir:"
	ls -l $outbound_dir
	cat $ftp_results
	rm -fv ftp_resutls.$$
        exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

ls -1 | Mail -s "$data_file was sent to Amadeus on $logdate" $maillist

rm -fv $data_file 

archive_clean $outbound_archive AS2BAUSG $FileAge
