#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export partner=Amadeus
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export namebase=ASoag
export maildom=alaskaair.com
export maillist="dean.liebrich@$maildom,joanne.gies@$maildom"
#export maillist="ASQX.ScheduleDistribution@$maildom,dean.liebrich@$maildom"
export sentdate=`/bin/date "+%Y%m%d_%H%M"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7

export program=`basename $0`

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

sleep 60

ftp_check $ftp_local_host

echo -e "\nftp get $namebase file from $ftp_local_host\n"
	ftp -v -i $ftp_local_host <<MGET >ftp_results.$$
	cd $lzout_dir
	dir
	mget ${namebase}*
	bye
MGET
	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP get of $namebase file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

export sim_file=`ls -1 ${namebase}*`
export arch_name=`echo $sim_file | sed -e 's/.txt//'`
export zip_name=${arch_name}.zip
export reldate=`head -6 $sim_file | tail -1 | cut -c65-71`

securezip $sim_file outbound

zip $zip_name $sim_file
errorchk $? "zip file $sim_file"

echo -e "\nsend mail to $maillist with file $sim_file attached\n"

echo -e "Please see the attached updated Alaska schedule to $partner for release $reldate.

The files attached are:
$sim_file

For questions regarding the SSIM please contact us via email at ASQX.ScheduleDistribution@$maildom.  If
your question is urgent you can reach us directly at one of the numbers listed below.

Thank you,
Alaska Airlines Schedule Distribution

Bill Lettner, 206-392-5039
Paul Twedt, 206-392-5837
Jody Stevenson, 206-392-5612

NOTICE: This email and any attachments are for the exclusive and confidential use of the intended
recipient(s).  If you are not an intended recipient, please do not read, distribute, or take action in
reliance upon this message.  If you received this in error, please notify me immediately by return email
and promptly delete this message and its attachements from your computer." | mutt -s "AS SSIM to $partner for release $reldate" -a $zip_file $maillist

#echo "SSIM file $sim_file was emailed from AS to $partner on $maildate" | Mail -s "$partner SSIM file" $maillist

ftp_file $ftp_local_host $sim_file ${arch_name}_$sentdate.txt "cd $lzout_archive"

ftp_delete $ftp_local_host $sim_file "cd $lzout_dir"

echo "remove file $sim_file"
rm -fv $sim_file $zip_file

archive_clean $outbound_archive $namebase $FileAge
