#!/bin/bash

program=`basename $0`
export PGPPASS=seavvdmzftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export sftp_host=as-qx@ari.lcl@sftp.amadeusri.com
export filedate=`/bin/date +%Y%m%d`
export FileAge=30
export mail_to="joanne.gies@alaskaair.com"
export datestamp=`/bin/date +%Y%m%d`

. /opt/local/ops_scripts/function_lib

function amadeusin {

cd $inbound_dir

	sftp -v $sftp_host <<GET >>ftp_results.$$
	cd AS-QX/outgoing
	mget $file_prefix
	quit
GET
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nsftp get of $file_prefix files get failed... fix it"
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

	ls -1 $file_prefix | while read File1
	do

echo -e "\nprocessing file $File1"

ftp_file $ftp_local_host $File1 $File1 "cd psmc/ari/inbound" $ftpmode

securezip $File1 inbound

	sftp -v $sftp_host <<DEL >>ftp_results.$$
	cd AS-QX/outgoing
	rm $file_prefix
	quit
DEL
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nsftp get of $file_prefix files get failed... fix it"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

rm -fv $File1

	done
}

archive_clean $inbound_archive $file_prefix $FileAge
