#!/bin/bash

export pgppass=seavvdmzftp
export pgp_rem_sig=EDSELIT
#export sftp_host=ASAAtest@mft2.svcs.hp.com
export sftp_host=ASAA@mft2.svcs.hpe.com
export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export indate=`date +%Y%m%d%H%M%S`
export info_to="joanne.gies@alaskaair.com"
export FileAge=14

. /opt/local/ops_scripts/function_lib

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_american_orca_data direction where
        direction equals in or out\n"
        exit 4
        fi

function outproc {

cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\ncheck for ftp connectivity to $sftp_host"
	sftp -v $sftp_host <<TEST >ftp_results.$$
	pwd
	bye
TEST

ftptest=`grep -i -c -e "Remote working directory" ftp_results.$$`

	if [ $ftptest -lt 1 ]; then
echo -e "\nUNABLE TO OPEN SFTP SESSION TO $sftp_host\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	else
echo -e "\nconnection to $sftp_host confirmed, processing continues...\n"
rm ftp_results.$$
	fi

ftp_retrocred_out $ftp_local_host $file_prefix "cd $lz"

	ls -1 ${file_prefix}* | while read FILE1
	do	
export data_file=$FILE1
#export outfile=${outfile_pref}`echo $data_file |sed -e 's/_//g' | cut $cutamt`.PROD
export outfile=$data_file.pgp
securezip $data_file outbound

echo -e "\nencrypt outbound $data_file for `whoami`"
echo $pgppass | gpg --passphrase-fd 0 --batch --armor -r $pgp_rem_sig --output $outfile --encrypt $data_file >pgp_transcript.$$ 2>&1
cat pgp_transcript.$$
errorchk $? "encrypt outbound $data_file for `whoami`"

echo -e "\nsftp $outfile to $sftp_host"
	sftp -v $sftp_host <<PUT >ftp_results.$$
	$chgdir
	put $outfile
	bye
PUT

errorchk $? "ftp $outfile to $sftp_host"

ftp_file $ftp_local_host $data_file $data_file "cd $lz/archive"

ftp_delete $ftp_local_host $data_file "cd $lz"

echo -e "\nremove temp files from $outbound_dir"
rm -fv $data_file $outfile pgp_transcript.$$
errorchk $? "remove temp files from $outbound_dir"
	done

ftp_delete $ftp_local_host $tag_file "cd $lz"

archive_clean $outbound_archive $file_prefix $FileAge

}

function inproc {

cd $inbound_dir

ftp_check $ftp_local_host

export pgp_file=`ls -1 $in_file_pref*`

echo $pgppass | gpg --passphrase-fd 0 --batch --output $local_tmp_file --decrypt $pgp_file >pgp_transcript.$$ 2>&1
cat pgp_transcript.$$
errorchk $? "decrypt $pgp_file for inbound `whoami`"

mv -fv $pgp_file $inbound_archive
errorchk $? "move $pgp_file to $inbound_archive"

echo -e "\nremove carriage control"
$HOME/bin/remove_crlf.pl $local_tmp_file >$local_file
errorchk $? "remove carriage control"

ftp_file $ftp_local_host $local_file $local_file "cd $lz"

echo "remove temp files"
rm -fv $local_file pgp_transcript.$$ $local_tmp_file
errorchk $? "remove temp files from $inbound_dir"

archive_clean $inbound_archive $in_file_pref $FileAge

}

case "$direction" in 

	oalout)	
export lz=mpprod/RetroCredit/OALResponse/AA  #prod
#export lz=mptest/RetroCredit/OALResponse/AA  #test
export file_prefix=AA_Member_Response_ASsend
#export file_prefix=AmericanAirlines_Member_Response_ASsend
export tag_file=AA_MEMBER_RESPONSE_TAG.TXT
#export tag_file=AmericanAirlines_MEMBER_RESPONSE_TAG.TXT
#export outfile_pref=RF
#export cutamt=-c25-30
#export cutamt=-c39-51
#export chgdir="cd /asaatest/aadvantage/rfastest/./striplf/lrecl=300"
export chgdir="cd /asaa/aadvantage/rfasprod/./striplf/lrecl=300"
echo -e "\nBegin processing for $datafile"
outproc
echo -e "\nProcessing for $datafile complete"
	;;

	asout)
export lz=mpprod/RetroCredit/ASQuery/AA  #prod
#export lz=mptest/RetroCredit/ASQuery/AA  #test
export file_prefix=ASQuery_AA_
export tag_file=AA_Member_Query_TAG.txt
export outfile_pref=QF
export cutamt=-c12-17
#export chgdir="cd /asaatest/aadvantage/qfastest/./striplf/lrecl=300"
export chgdir="cd /asaa/aadvantage/qfasprod/./striplf/lrecl=300"
echo -e "\nBegin processing for $datafile"
outproc
echo -e "\nProcessing for $datafile complete"
	;;

	oalin)
export lz=mpprod/RetroCredit/OALQuery/AA 	#prod
#export lz=mptest/RetroCredit/OALQuery/AA 	#test
export in_file_pref=QFAS
export local_tmp_file=AA_Member_Query_AAsend_toAS_${indate}.tmp
export local_file=AA_Member_Query_AAsend_toAS_${indate}.txt
echo -e "\nBegin processing for hand back file"
inproc
echo -e "\nProcessing for $datafile complete"
	;;

	asin)
export lz=mpprod/RetroCredit/ASResponse/AA	#prod
#export lz=mptest/RetroCredit/ASResponse/AA	#test
export in_file_pref=RFAS
export local_tmp_file=ASResponse_AA_${indate}.tmp
export local_file=ASResponse_AA_${indate}.txt
echo -e "\nBegin processing for hand back file"
inproc
echo -e "\nProcessing for $datafile complete"
	;;

esac
