#!/bin/bash

export ftp_host=151.193.132.144
#export ftp_local_host=asprodftp #prod
export ftp_local_host=testftp 	 #test
export sftp_host=ASAAtest@mft2.svcs.hp.com
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export indate=`date +%Y%m%d%H%M%S`
export info_to="dean.liebricha@alaskaair.com"
export FileAge=14

. /opt/local/ops_scripts/function_lib

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_american_orca_data direction where
        direction equals in or out\n"
        exit 4
        fi

function outproc {

rm ~/.netrc
ln -s ~/.netrc_atm ~/.netrc

cd $outbound_dir

ftp_retrocred_out $ftp_local_host $file_prefix "cd $lz"

ls -1 $file_prefix* | while read FILE1
		do
securezip $FILE1 outbound
#encrypt files
		done

ftp_retrocred_in $ftp_local_host $file_prefix "cd $lz/archive"

echo -e "\nremove $file_prefix* files from $ftp_local_host"
	ftp -v -i $ftp_local_host <<DEL >ftp_results.$$
	cd $lz
	mdel $file_prefix*
	quit
DEL

errorchk $? "remove $file_prefix* files from $ftp_local_host"

ftp_delete $ftp_local_host $tag_file "cd $lz"

echo -e "\nremove $file_prefix* files from $outbound_dir"
rm -fv $file_prefix*

}

function inproc {

cd $inbound_dir

#decrypt file(s)

mv -v $data_file $local_file

#mv -fv $pgp_file $inbound_archive

ftp_check $ftp_local_host
ftp_retrocred_in $ftp_local_host $local_file "cd $lz"

echo "remove temp files"
rm -fv $local_file

archive_clean $inbound_archive $local_file $FileAge

}

case "$direction" in 

	oalout)	
#export lz=mpprod/RetroCredit/OALResponse/AA  #prod
export lz=mptest/RetroCredit/OALResponse/AA  #test
export file_prefix=AA_Member_Response_ASsend
export tag_file=AA_MEMBER_RESPONSE_TAG.TXT
echo -e "\nBegin processing for $datafile"
outproc
echo -e "\nProcessing for $datafile complete"
	;;

	asout)
#export lz=mpprod/RetroCredit/ASQueryAA  #prod
export lz=mptest/RetroCredit/ASQuery/AA  #test
export file_prefix=ASQuery_AA_
export tag_file=AA_Member_Query_TAG.txt
echo -e "\nBegin processing for $datafile"
outproc
echo -e "\nProcessing for $datafile complete"
	;;

	oalin)
#export lz=mpprod/RetroCredit/OALQuery/AA 	#prod
export lz=mptest/RetroCredit/OALQuery/AA 	#test
export data_file=
export local_file=AA_Member_Query_AAsend_toAS_${indate}.txt
echo -e "\nBegin processing for hand back file"
inproc
echo -e "\nProcessing for hand back file complete"
	;;

	asin)
#export lz=mpprod/RetroCredit/ASResponse/AA	#prod
export lz=mptest/RetroCredit/ASResponse/AA	#test
echo -e "\nBegin processing for hand back file"
inproc
echo -e "\nProcessing for hand back file complete"
	;;

esac
