#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export ftp_host=151.193.132.144
export partner=AA
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_dir_win=\\\\seavvfile1\\ftpprod\\scheduling\\PartnerSSIM\\${partner}\\inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export base_name=.zip
export maildom=alaskaair.com
#export mail_list="dean.liebrich@$maildom"
export mail_list="ASQX.ScheduleDistribution@$maildom,AA.Distribution@$maildom"
export recdate=`/bin/date "+%Y%m%d_%H%M"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7
export program=`basename $0`
. /opt/local/ops_scripts/function_lib

export file_prefix=$1

	if [ -z $file_prefix ]; then
echo -e "\nMissing $file_prefix parm, proper syntax is
process_ssim_file file_prefix, where $file_prefix is 
equal to pubas_aa, pubas10_aa, aaskd_aa or blah...\n"
exit 4
	fi

function get_file_name {

cd $inbound_dir
size_check $zip_file
export sim_file=`unzip -l $zip_file | tail -3 | head -1 | awk '{print $4}'`
export sim_file_tmp=${sim_file}.tmp

}

function preproc {

case "$filetype" in

	PUBAA)
export export loc_prefix=aaas
       ;;

	PUBAS)
export export loc_prefix=asaa
       ;;

	AASKD)
export export loc_prefix=op-aa
       ;;

esac

}

function mainproc {

cd $inbound_dir
 
ftp_check $ftp_local_host

size_check $zip_file

unzip $zip_file
errorchk  $? "unzip `whoami` ssim file $zip_file"

export filetype=`ls -1 $sim_file | cut -c1-5`

echo -e "\nremove carriage control"
$HOME/bin/remove_crlf.pl $sim_file >$sim_file_tmp
	result=$?
	if [ $result -ne 0 ]; then
	echo -e  "\nremove carriage control failed, create and assign IM to SM"
	exit 4
	fi

preproc

export reldate=`head -6 $sim_file_tmp | tail -1 | cut -c65-71`
export relday=`head -6 $sim_file_tmp | tail -1 | cut -c65-66`
export month=`head -6 $sim_file_tmp | tail -1 | cut -c67-69`

month_cvt $month $sim_file_tmp
export in_file=${loc_prefix}${newrelmon}${relday}${suffix}.$recdate.txt

ftp_file $ftp_local_host $sim_file_tmp $in_file "cd $lzin_dir" dir

echo "SSIM file $sim_file for release $reldate was sent from $partner to AS on $maildate. The files can be found here: $lzin_dir_win" | Mail -s "$partner to AS SSIM file release $reldate" $mail_list

securezip $zip_file inbound

rm -fv $zip_file $sim_file $sim_file_tmp

archive_clean $outbound_archive $base_name $FileAge

}

case $file_prefix in

	pubas_aa)
export suffix=mk
export zip_file=${file_prefix}.zip
export sim_file=PUBASssm.txt
export sim_file_tmp=${sim_file}.tmp
mainproc
;;

	pubas10_aa)
export suffix=op
export zip_file=${file_prefix}.zip
export sim_file=PUBASssm10
export sim_file_tmp=${sim_file}.tmp
mainproc
;;

	aaskd_aa)
export suffix=_cnnx
export zip_file=${file_prefix}.zip
get_file_name
mainproc
;;

	pubaaasqx_aa)
export suffix=mk
export zip_file=${file_prefix}.zip
get_file_name
mainproc
;;

esac
