#!/bin/bash

export sftp_host=Alaska@144.9.39.83
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export fids_dir=$HOME/fids
export archive_dir=$fids_dir/archive
export badfile_dir=$fids_dir/badfiles
export tagfile=aa_fids_lax.tag
export errors_to="production.services@alaskaair.com"

. /opt/local/ops_scripts/function_lib

function mainproc {

echo -e "\ncheck for ftp connectivity to $sftp_host"
	sftp -v $sftp_host <<TEST >ftp_results.$$
	pwd
	bye
TEST

ftptest=`grep -i -c -e "Remote working directory" ftp_results.$$`

	if [ $ftptest -lt 1 ]; then
echo -e "\nUNABLE TO OPEN SFTP SESSION TO $sftp_host\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	else
echo -e "\nconnection to $sftp_host confirmed, processing continues...\n"
rm ftp_results.$$
	fi

echo -e "\nRemove previous archived .xml files"
ls -1 $archive_dir/${filepref}*.xml | xargs rm -fv

cd $outbound_dir

ls -1 ${filepref}*.xml | while read FILE1
	do

filechk=`grep -c \<\/Flight\> $FILE1`

	if [ $filechk -lt 1 ]; then
echo -e "\nincomplete file, moving to badfiles directory"
mv -fv $FILE1 badfiles
	else	
mv -v $FILE1 $fids_dir
	fi
	done

cd $fids_dir

echo -e "FTP .xml files to $ftp_host"
	sftp -v $sftp_host <<PUT > ftp_results.$$
	mput ${filepref}*.xml
PUT

	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nftp of .xml files failed\n"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$ $outbound_dir/$tagfile
mv -v ${filepref}*.xml $archive_dir

}

export station=$1

	if [ -z $station ]; then
echo -e "\n	Missing portname parm, proper syntax is:
	put_xml_files station where station is the city code
	we are sending files to, e.g. sna"
	fi

case "$station" in

	lax)
export filepref=F_ASLAX
export tagfile=aa_fids_${station}.tag
mainproc
       ;;

*)

echo -e "\nargument is missing or invalid, 
need to run script with a station code"

exit 4
	;;

esac
