#!/bin/bash

. $HOME/bin/amex_environment
program=`basename $0`

export confirmation=$1

	if [ -z $confirmation ]; then
echo -e "\n	Missing confirmation parm.
	proper syntax is: get_amex_confirmation filename
	where confirmation equals IN or IN1\n"
	exit 4
	fi

case "$confirmation" in
 
	IN)
	
echo -e "\nBegin processing for $confirmation from `whoami`"
export fileprefix=SUB002.105246.C
export country=US
getconfirm
echo -e "\nProcessing for confirmation file complete"

	;;

	IN1)
	
echo -e "\nBegin processing for $confirmation from whoami"
export fileprefix=SUB002.105267.C
export country=Canadian
getconfirm
echo -e "\nProcessing for confirmation file complete"

	;;

*)

echo -e "\nargument is missing or invalid, 
need to pass argument of in or in1"

exit 4

	;;

esac

#end of script
