#!/bin/bash

# Set up the amex data transfer environment
# 2/3/07 Set up file transfer - jg
# 4/18/08 - cr15943 - added out1 proc to send Canadian currency file. ts.
# 6/29/11  - changed to drop crlf and rename US and CAN files. jg

export sftp_host=ALASKAAIRPRD@fsgateway.aexp.com
export ftp_local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export alert_recipient=joanne.gies@alaskaair.com
#export datestamp=`/bin/date +%b%d%Y.%H%M`
export datestamp=`/bin/date +%b%d%Y`
export dom=alaskaair.com
export mail_list="joanne.gies@alaskaair.com"
#export infor_to="joanne.gies@alaskaair.com"
export infor_to="accounts.receivable@$dom,fire.team.oncall.support@$dom"
export logfile=$HOME/transfer_log
export FileAge=30

. /opt/local/ops_scripts/function_lib

function getconfirm {

cd $inbound_dir

export data_file=`ls -1 SUB002.105246.C*`

echo -e "processing $country file $data_file"

count_records=`wc -l $data_file | awk '{print $1}'`
echo -e "\n$count_records records from amex confirmation file at $sftp_host"

securezip $data_file inbound

ftp_file $ftp_local_host $data_file $data_file.$datestamp.txt "cd AR_AccountsReceivable/AmexC"

echo "Send mail notification to $infor_to"
Mail -s "AMEX $country - $fileprefix - File confirmation at `date`" $infor_to < $data_file

archive_clean $inbound_archive $fileprefix $FileAge

echo -e "\nclean up outbound directory\n"
rm -fv $tagfile $data_file

}

echo -e "\nBegin processing for $confirmation from whoami"
export country=US
getconfirm
echo -e "\nProcessing for confirmation file complete"
