#!/bin/bash

. $HOME/bin/amex_environment
program=`basename $0`

export direction=$1

	if [ -z $direction ]; then
echo -e "\n	Missing direction parm.
	proper syntax is: put_amex_data direction
	where direction equals OUT or OUT1\n"
	exit 4
	fi

case "$direction" in 
	OUT)

export tagfile=amex.tag
export datafile=amex.txt
	
echo -e "\nBegin processing for $datafile to whoami"
outproc
echo -e "\nProcessing for $base_name complete"

	;;

	OUT1)

export tagfile=amexcad.tag
export datafile=amexcad.txt
	
echo -e "\nBegin processing for $datafile to whoami"
outproc1
echo -e "\nProcessing for $base_name complete"

	;;

*)

echo -e "\nargument is missing or invalid, 
need to pass argument of OUT or OUT1"

exit 4

	;;

esac

#end of script
