#!/bin/bash

# Set up the aonhewitt data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/aonhewitt_environment"


export sftp_host=aag_elig@cbafiles.aonhewitt.com
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export hcmdir_in=/home/hcmprod/inbound/aon_hewitt
export hcmdir_out=/home/hcmprod/outbound/aon_hewitt
export datestamp=`/bin/date +%b%d%Y.%H%M`
export datestamp_rem=`/bin/date +%m%d%Y`
export file_prefix=PayrollFile*.txt
export info_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

cp $hcmdir_out/$data_file $outbound_dir
errorchk $? "copy $data_file to $outbound_dir"

echo -e "\nprocessing $whoami $data_file"

securezip $data_file outbound

data_records=`wc -l $data_file | awk '{print $1}'`


echo -e "\nPush file from seavvftp to AONhewitt"
echo -e "\nput $datafile to $sftp_host"
	sftp -v -o port=2127 $sftp_host <<PUTDATA >ftp_results.$$
        cd ToHewitt
	put $data_file $remote_file
	dir
	quit
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $datafile to AON_hewitt failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

errorchk $? "sftp $outfile to $sftp_host"

echo -e "\n$datestamp: there were $data_records records sent to aonhewitt"

archive_clean $outbound_archive $data_file $FileAge

echo -e "\nRemove temp files"
rm -fv $data_file $hcmdir_out/$data_file $hcmdir_out/$data_tagfile $outfile

}

function inproc {

cd $inbound_dir

	ls -1 AONBNDED_*.txt | while read File1
	do

echo -e "\nprocessing AONHEWITT inbound $File1"

securezip $File1 inbound


echo -e "\nMove $File1 to $hcmdir_in"
mv $File1 $hcmdir_in/$File1
touch $hcmdir_in/${File1}.tag


	result=$?

	if [ $result -ne 0 -o -f $File1 ]; then
	echo -e "\nMove $File1 to $hcmdir_in failed, contact Systems Operations.\n"
  	exit 8
	fi

archive_clean $inbound_archive AONBNDED*.zip $FileAge

done


}
