#!/bin/bash

set -x

# Determine file direction for aonhewitt then process
# Set the environment variables

. $HOME/bin/aonhewitt_environment
program=`basename $0`

export direction=$1

	if [ -z $direction ]; then
echo -e "\n	Missing direction parm.
	proper syntax is: process_aonhewitt_data direction
	where direction equals 'in' or 'out'\n"
	exit 4
	fi

case "$direction" in 
	in)

echo -e "\nbegin processing for `whoami` Input file"		
inproc 
echo -e "\nend processing for `whoami` Input file"
	;;

	out)
export data_file=AGBN0104.txt
export data_tagfile=AGBN0104.tag
export remote_file=63227.txt
outproc 
echo -e "\nend processing for `whoami` AONHewitt out file"
      ;;

	out1)
export data_file=AGBN0108.txt
export data_tagfile=AGBN0108.tag
export remote_file=AGBN108.txt
outproc 
echo -e "\nend processing for `whoami` AONHewitt out file"
      ;;

esac
