#!/bin/bash

# Set up the APG data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/apg_environment"

export PGPPASS=seavvdmzftp
export qsifilename=QSI_*
export qsitagfile=QSItag
export ext=.DAT.gz
export tagext=.txt
export ftp_localhost=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export fileprefix=QSI_
export FileAge=35

. /opt/local/ops_scripts/function_lib

function inproc {

cd $inbound_dir

ftp_vendor_chk $ftp_localhost

#Create list of files to create tag files
echo "Creating list of files to create tag files."
	ls -1 > dir.txt        

listoffiles=`grep -e $fileprefix dir.txt`

echo "This is the list of files names:"
echo "$listoffiles" | while read FILE1
        do
        echo "Creating tag file for $FILE1"
        touch $FILE1.tag
	done

echo -e "\nput $qsifilename$ext to $ftp_localhost" 
	ftp -v -i $ftp_localhost <<GETDATA >ftp_results.$$
	bin
	cd "bi\qsi\inbound"
	mput $qsifilename
	dir	
	bye
GETDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "ftp put of $qsifilename$ext failed"
	cat ftp_results.$$
	rm -f ftp_results.$$
	exit 4 
	fi

rm -f ftp_results.$$

echo -e "\nmove $qsifilename$ext to $inbound_archive and delete tag & temp files."
mv $qsifilename$ext $inbound_archive/
rm $qsitagfile$tagext
rm $qsifilename
rm dir.txt

archive_clean $inbound_archive $fileprefix $FileAge

}
