#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_host=asprodftp
export lz=CharterGroupSales
#export file_prefix=API_
export file_prefix=AS_
export maildom=alaskaair.com
export mail_list="dean.liebrich@$maildom"
export timestamp=`/bin/date "+%H%M"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export FileAge=7
export program=`basename $0`

. /opt/local/ops_scripts/function_lib

#mv -v $HOME/${file_prefix}*.TXT $inbound_dir

cd $inbound_dir

function ftpproc {
echo -e "\nputting files `ls -1 ${namebase}*` to $ftp_host"
	ftp -v -i $ftp_host <<PUT >ftp_results.$$
	cd $lz
	mput ${namebase}*
	bye
PUT
}

ftp_check $ftp_host

ls -1 ${file_prefix}* | while read FILE1
			do
size_check $FILE1

export namebase=`echo $FILE1 | sed -e 's/.TXT//'`
export in_file_name=${namebase}_${timestamp}.TXT

securezip $FILE1 inbound

ftp_file $ftp_host $FILE1 $in_file_name "cd $lz"

rm -fv $FILE1
			done

archive_clean $inbound_archive $file_prefix $FileAge
