#!/bin/bash

# Process ARC data for Outbound.

# Set the environment variables
. $HOME/bin/arc_environment

export direction=$1

case "$direction" in

	OUT)

outproc

	;;

	INBANK)

CYC=$2

echo "Begin processing for bank cycle=$CYC"
inproc_bank
echo "end processing for bank cycle=$CYC"

	;;

	INECB)

CYC=$2

echo "Begin processing for ECB cycle=$CYC"
inproc_ecb
echo "end processing for ECB cycle=$CYC"
	
	;;

	INWKLY)

echo "Begin processing for Weekly ARC file"
inproc_weekly
echo "end processing for Weekly ARC file"
	
	;;

	INQTRLY)

echo "Begin processing for Quarterly ARC file."
inproc_quarterly
echo "end processing for Quarterly ARC file."
	
	;;

*)

echo -e "\nargument is missing or invalid, 
need to pass one of the following arguments:
OUT, INBANK, INECB, INWKLY, or INWKLY\n"

exit 4

	;;

esac
