#!/bin/bash

export sftp_host=as027wec3vup@67.218.194.51
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=joanne.gies@alaskaair.com
export datestamp=`/bin/date +%Y%m%d`
export info_to="joanne.gies@alaskaair.com"
export tagfile=asi.tag
export errors_to="production.services@aaskaair.com"
#export asi_mailto="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20

. /opt/local/ops_scripts/function_lib

export filetype=$1

#make sure filetype parm was passed as first arg
	if [ -z $filetype ]; then
echo -e "\n Missing filetype parm.  Proper syntax
is put_ra_data type, where type
is equal to ap or ar."
	exit 4
	fi

function mainproc {

cd $outbound_dir

zip ${datafile}.zip  $datafile

echo "${datafile}.zip This is datafile.zip"

echo -e "\nsftp data files to $sftp_host"
	sftp -v $sftp_host <<PUT >ftp_results.$$
       	put ${datafile}.zip ${datafile}.$datestamp.zip
        dir
	bye
PUT

errorchk $? "ftp data files to $sftp_host"

rm -fv ftp_results.$$

securezip $datafile outbound

echo -e "\nclean up inbound directory"
rm -f  $datafile $tagfile ${datafile}.zip

archive_clean $outbound_archive $basename $FileAge

}

case "$filetype" in
 ap)
        export datafile=alaska_sfi_payable  
mainproc
	export datafile=alaska_sales_payable    
mainproc	


echo -e "\nAccounts payable files sent"
;;

 ar)
 	export datafile=alaska_sales_receivable
mainproc
        export datafile=alaska_sfi_receivable
mainproc
echo -e "\nAccounts receivable files sent"
;;

esac

#Mail -s "Files have been sent at `date`" $asi_mailto </dev/null
