#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export log_dir=$HOME/log
export FileAge=90
export errors_to=dean.liebrich@alaskaair.com
export prefix=XAS
. /opt/local/ops_scripts/function_lib

function remove {
echo -e "\nremoving files from $dir"
find $dir -mtime +$FileAge | xargs rm -fv
}

export dir=$log_dir
remove

export dir=$outbound_archive
remove


