#!/bin/bash

# stand alone scipt for the MVS file XAS.PROD.XMTASRCN.IDECP (Joanne 6/29/2011)


export ftphost_outbound=ftpin.atpco.net
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=joanne.gies@alaskaair.com
export idec_file=XAS.PROD.XMTASRCN.IDECP
export basename=XAS.PROD.XMTASRCZ.IDECP
export zip_file=XAS.PROD.XMTASRCZ.IDECP.zip
export tag_file=idec.tag
export filedate=`date +%Y%m%d`
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="joanne.gies@alaskaair.com"
export cryptalg="-cryptalgorithm=AES,256"
export password=4FsQyx6sqAT1YyjJBTsc8eSm9GiTmZwknvnS4BCWU6RijiQvFO
export mail_to="joanne.gies@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

#rm ~/.netrc
#ln -s ~/.netrc.prod ~/.netrc

cd $outbound_dir

############################################################
# Compress the IDEC file per ATPCO requirements (secure PKZip)
############################################################
echo -e "\nCompressing file $outbound_dir/$idec_file into zip archive $outbound_dir/$zip_file"

pkzipc -add $cryptalg -passphrase=$password $outbound_dir/$basename $outbound_dir/$idec_file
	pkzipc_rc=$?

	if [[ $pkzipc_rc -ne 0 ]]
	then
    echo -e "\npkzipc create of zipped file $OUTBOUND/$zip_file containing $OUTBOUND/$idec_file Failed- contact SysMgmt."
	exit 4
	fi

# For FTP session: Create ATPCO's required MVS data set name by adding quotes to zip file name     
#echo ATPCO DSN name with qoutes is "'$basename'"

############################################################
# Send file to ATPCO SSL connection to the mainframe
############################################################
curl -vk --stderr - --ftp-ssl -u xas0ft2:idecatp -T $zip_file --quote "site LRECL=0 RECFM=U BLKSIZE=27990" ftp://ftpin.atpco.net/"'$basename'" >ftp_results.$$
	result=$?
	
	if [ $result -ne 0 ]; then
echo -e "\nFTP to ftpin.atpco.net failed"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

securezip $idec_file outbound

archive_clean $outbound_archive $idec_file $FileAge

rm -fv $tag_file $idec_file $zip_file $tag_file ftp_results.$$

#echo -e "\nemail to ATPCO that the IDEC file has been sent"
#Mail -s "Zipped IDEC has been sent to your server" $mail_to </dev/null
