#!/bin/bash

export ftp_local_host=mvs
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export data_file=RA.ATPCO.RECEIVE.IDEC.DATA
export zip_temp_file=${data_file}.Z
export zip_file=${data_file}.ZIP
export data_file_crlf=${data_file}.tmp
export jcl=$HOME/bin/railptpe.jcl
export dcbparms="site recfm=fb lrecl=160 cylinders pri=100 sec=50 unit=wrkda blksize=0"
export password=4FsQyx6sqAT1YyjJBTsc8eSm9GiTmZwknvnS4BCWU6RijiQvFO
export datestamp=`date +%m%d%y.%H%M`
export FileAge=7
export errors_to=dean.liebrich@alaskaair.com
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

	if [ ! -s $zip_temp_file ]; then
	echo -e "\nexpected TCN file not found\n"
	echo "Check into inbound `whoami` TCN file" | Mail -s "inbound TCN" $errors_to
	exit 4
	fi

startsize=`ls -l $zip_temp_file | awk '{print $5}'`
sleep 60
endsize=`ls -l $zip_temp_file | awk '{print $5}'`

		while [ $startsize -ne $endsize ]
		do
		echo "incomplete file... re-checking"
		startsize=`ls -l $zip_temp_file | awk '{print $5}'`
		sleep 60
		endsize=`ls -l $zip_temp_file | awk '{print $5}'`
		done

echo -e "\nrename zip_temp_file $zip_file"
mv $zip_temp_file $zip_file

echo -e "\nunzip file $zip_file"
pkzipc -extract -password=$password $zip_file
	
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nunzip of file $zip_file failed"
	exit 4
	fi
	
crlf_rem $data_file $data_file_crlf

ftp_check $ftp_local_host
dsn_2mvs $ftp_local_host $data_file_crlf "'$data_file'"

ftp_jcl $jcl $ftp_local_host

echo -e "\nmove $zip_file to $inbound_archive/$data_file.$datestamp.ZIP"
mv $zip_file $inbound_archive/$data_file.$datestamp.ZIP

echo -e "\nclean up inbound directory"
rm $data_file $data_file_crlf

archive_clean $inbound_archive $data_file $FileAge
