#!/bin/bash

export ftp_host=seatsairprice01
export inbound_dir=$HOME/inbound_dds_test
export inbound_archive=${inbound_dir}/archive
export password=4FsQyx6sqAT1YyjJBTsc8eSm9GiTmZwknvnS4BCWU6RijiQvFO
export lz=/airprice/atpco/dds_test
export FileAge=10
export errors_to=dean.liebrich@alaskaair.com
#export zipsuff2=ZIP
export filepref=QAS.PROD
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

ls -1 $filepref*.zip | while read file1
	do
pkzipc -extract -password=$password $file1
	done

gzip $fileprefix*.txt

        ftp -iv $ftp_host <<PUT >ftp_results.$$ 2>&1
	cd $lz
	bin
	mput $fileprefix*.gz
	ascii
	mput $fileprefix*.txt
        quit
PUT

	result=$1

	if [ $result -ne 0 ]; then
echo "FTP dds_test file to $ftp_host failed,
OPEN INCDENT FOR NEXT BUSINESS DAY"
cat ftp_results.$$
rm -v ftp_results.$$
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

mv -v $filepre* $inbound_archive

archive_clean $inbound_archive $filepref $FileAge

echo "all done"
