#!/bin/sh

# script to process AVIS car rental data
# contact info: MICHAEL HORNUNG
# 		516-222-4032
#		MICHAEL.HORNUNG@CENDANT.COM
#

#export ftp_host=dmz-ftp2.wizcom.com
export ftp_host=170.225.12.197
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export basename=alaskaair
export rem_file=${base_name}.txt
export rem_old_file=${base_name}.old
export local_file=ZIAVISCARRENTALPIT.txt
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14
program=`basename $0`

. /opt/local/ops_scripts/function_lib

export ENV=$1

case $ENV in

	prod)
	export ftp_local_host=asprodftp
	export lz=mpprod
	
	;;

	test)
        export ftp_local_host=testftp
        export lz=mptest

        ;;

	*)

echo -e "\nargument is missing or invalid, 
need to pass environment argument of prod or test\n"

exit 4

	;;

esac

cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

ftp_vendor_chk $ftp_host
ftp_vendor_get $ftp_host $rem_file $local_file

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nclean up $inbound_dir"
rm -f $local_file

ftp_rename $ftp_host $rem_file $rem_old_file

archive_clean $inbound_archive ZIAVISCARRENTALPIT $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"

