#!/bin/bash

# Process bedynam data file
#

# Set environment values
. $HOME/bin/bedynam_environment
program=`basename $0`

direction=$1

case "$direction" in

        in)

export data_file=AAG_BeDynamic_data.zip

echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"

        ;;

        out)

export data_file=bedynam_handback

echo -e "\nBegin processing for `whoami` outbound processing"
outbound
echo -e "\nEnd of `whoami` outbound processing"

        ;;

	*)

echo -e "\nargument is missing or invalid, 
need to pass direction argument of in or out\n"

exit 4

	;;

esac
