#!/bin/bash

export sftp_host=alaskaairlines@files.benevity.org
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export hcmdir_out=/home/hcmprod/outbound/benevity
export datestamp=`/bin/date +%b%d%Y.%H%M`
export filedate=`/bin/date +%Y%m%d`
export alert_recipient=joanne.gies@alaskaair.com
export info_to="joanne.gies@alaskaair.com"
export errors_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

echo -e "get $data_file from $hcmdir_out"
cp $hcmdir_out/$data_file $outbound_dir

securezip $data_file outbound

echo -e "\nput  $data_file on Benevity server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd $dir
       	put $data_file $datestamp$data_file
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$

data_records=`wc -l $data_file | awk '{print $1}'`
echo -e "\n$datestamp: there were $data_records records sent to benevity" 

echo -e "\nRemove temp files"
rm -f $data_file  $pgpfile $hcmdir_out/$data_file $hcmdir_out/$tag_file

archive_clean $outbound_archive $data_file $FileAge

}

function inproc {

cd $inbound_dir

echo -e "\nget  file on Benevity server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd $dir
       	get $in_file
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$

	if [ ! -f $in_file ]; then
echo -e "\nno in_file at Benevity ... exiting"
Mail -s "No $in_file at Benevity"

Mail -s "No $in_file on the Benevity server on  $datestamp" $errors_to </dev/null
	exit 0
	fi

echo -e "\nprocessing Benevity $in_file"

securezip $in_file inbound

echo -e "\nMove $in_file to $hcmdir_in and create $tagfile"
cp $in_file $hcmdir_in
touch $hcmdir_in/$tag

rm -fv $in_file

cat ftp_results.$$
rm -fv ftp_results.$$

echo -e "\ndelete file from Benevity server"
        sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd $dir
        rm $in_file
	dir
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$

archive_clean $inbound_archive .txt $FileAge

}
