#!/bin/bash

# Set environment values

. $HOME/bin/benevity_environment

program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_benevity_data direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in_bnvtflt)
echo -e "\nBegin processing for `whoami` inbound processing"
export in_file=bnvtflt_inbound.csv
export dir=Payroll
export hcmdir_in=/home/hcmprod/inbound/deductions
export tag=bnvtflt_inbound.tag
inproc
echo -e "\nEnd of `whoami` inbound processing"
        ;;

        in_bnvtgrnd)
echo -e "\nBegin processing for `whoami` inbound processing"
export in_file=bnvtgrnd_inbound.csv
export dir=Payroll
export hcmdir_in=/home/hcmprod/inbound/deductions
export tag=bnvtgrnd_inbound.tag
inproc
echo -e "\nEnd of `whoami` inbound processing"
        ;;

        outPeople)
echo -e "\nBegin processing for `whoami` $data_file to UserImport dir file processing"
export data_file=aagbenevity.csv
export tag_file=aagbenevity.tag
export dir=UserImport
outproc
echo -e "\nEnd of `whoami` outbound processing"
        ;;

        outGround)
echo -e "\nBegin processing for `whoami` $data_file to Payroll dir file processing"
export data_file=alaska_grnd.csv
export tag_file=alaska_grnd.tag
export dir=Payroll
outproc
echo -e "\nEnd of `whoami` outbound processing"
        ;;

	outFlight)
echo -e "\nBegin processing for `whoami` $data_file to Payroll dir file processing"
export data_file=alaska_flight.csv
export tag_file=alaska_flight.tag
export dir=Payroll
outproc 
echo -e "\nEnd of `whoami` outbound processing"
      ;;

esac
