#!/bin/bash

set -x

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export sftp_host=Alaskaair@ftp.blackline.com
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%Y%B%d.%H%M`
export GL_file=GL_Extract_$datestamp.txt
export mail_to="joanne.gies@alaskaair.com"
export nofiledate=`/bin/date "+%A, %D"`
FileAge=30

. /opt/local/ops_scripts/function_lib

cd $outbound_dir
bye

*echo -e "\nget file on $ftp_local_host" 
*	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
*        cd "PSFINFTP/outbound/gl_Blackline"
*	dir
*     	mget GL_Extract*.txt
*        quit
*GETDATA
cd
*cat ftp_results.$$
*rm -f ftp_results.$$

*export data_file=`ls -1 GL_Extract*.txt`

echo -e "\nProcessing file $data_file"

let tailamt="`wc $data_file | awk '{print $1}'` -1"
echo -e "\$nThe line count $tailamt"

tail -$tailamt $data_file > $GL_file
echo -e "\nThis is the GL_file  $GL_File"

securezip $GL_file outbound

echo -e "\nput $GL_File to $sftp_host"
	sftp -v $sftp_host <<PUTDATA >ftp_results.$$
        cd PROD
	put $GL_file 
        dir
	bye
PUTDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $GL_File to Blackline failed, contactSystem Operations"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

echo -e "\nRemove $GL_file on asprodftp" 
	ftp -v asprodftp <<GETDATA >ftp_results.$$
	cd "PSFINFTP/outbound/gl_blackline/Archive
#	put $GL_file 
        cd ..
#       del $data_file
	bye
GETDATA

rm -fv $GL_file $data_file ftp_result*

archive_clean $outbound_archive GL_Extract $FileAge
