#!/bin/bash

set -x

# Blackline bank recon files data transfer environment

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
#export sftp_host=#Alaskaair@ftp.blackline.com
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export info_to="production.services@alaskaair.com"
export nofiledate=`/bin/date "+%A, %D"`
export dir=SNBA
export dir1=BAI
FileAge=30

. /opt/local/ops_scripts/function_lib

function mainproc {

cd $outbound_dir

echo -e "\nget file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "BR_Chesapeake/outgoing/
	dir
      	mget *.txt
        quit
GETDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nftp get of Bank Recon files failed... fix it"
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

rm sftp_commands.txt
rm BRFtp_FileList.txt


	ls -1 *.txt |grep -iv bank | while read File1
	do

export filesize=`ls -l $File1 | awk '{print $5}'`

	if [ $filesize -eq 0 ]; then
	rm -v $File1
	fi

echo -e "processing Bank recon file $File1"

export file_name=$File1
export reform_file=`echo $file_name | sed -e 's/txt/dat/'`

$HOME/bin/decimal $file_name


       done

rename .dat .txt *


}

function decimal {

	ls -1 *.txt |grep -iv bank | while read File1
	do

echo -e "processing Bank recon file $File1"

export file_name=$File1
export reform_file=`echo $file_name | sed -e 's/txt/dat/'`

$HOME/bin/decimal $file_name

#rm -fv $file_name

#mv -v $reform_file $file_name



       done

}

mainproc


#echo -e "\nput bank recon files to $sftp_host"
#	sftp -v $stp_host <<PUTDATA >ftp_results.$$
#        cd dir
#	mput *BANK*.txt
#        dir
#	bye
#PUTDATA
#
#	result=$?




#echo -e "\nput bank recon files to $sftp_host"
#	sftp -v $blah <<PUTDATA >ftp_results.$$
#        cd dir1
#	mput *.txt
#       dir
#	bye
#PUTDATA

#	result=$?

#	if [ $result -ne 0 ]; then
#	echo "FTP put of $GL_File to Blackline failed, contactSystem Operations"
#	cat ftp_results.$$
#	rm -fv ftp_results.$$
#	exit 4
#	fi

#cat ftp_results.$$


#echo -e "\nArchive file on $ftp_local_host" 
#	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
#        cd "BR_Chesapeake/outgoing"
#        put $File1
#        cd ..
#        quit
#GETDATA

#	result=$?
#
#	if [ $result -ne 0 ]; then
#	echo -e "\narchive of file $File1 on $ftp_local_host failed.\n"
#	cat ftp_results.$$
#	rm -fv ftp_results.$$
#	exit 4
#	fi

#cat ftp_results.$$
#rm -fv ftp_results.$$

archive_clean $outbound_archive $GL_file $FileAge
