#!/bin/ksh

#rm ${1}.dat

cat $1 | 
    while read fieldA
do
	header=${fieldA:0:1}
	if [ $header = 'D' ]
	   then
  	   part1=${fieldA:0:73}
  	   part2=${fieldA:73}
       
#  	   echo " part1 >>${part1}<<"
#  	   echo " part2 >>${part2}<<"  
       
  	   rebuild="$part1"."$part2"
#  	   echo " Rebuild >>${rebuild}<<"
  	   echo "$rebuild" >> $reform_file
#  	   echo " "
#  	   echo " "
    else 
  	   echo "$fieldA" >> $reform_file
rm -fv $1

    fi 
done
