#!/bin/bash

set -x

cd MayNonBankDec_0501to0507


	ls -1 *.txt | while read File1
	do

echo -e "\nprocessing Bank recon files $File1"

export file_name=$File1
export reform_file=`echo $file_name | sed -e 's/txt/dat/'`

$HOME/bin/decimal $file_name

       done

