#!/bin/bash

# Encrypt the AS ach file and push to BofA
# 2006-09-13 Modified to use gpg encryption  and function call on seavvftp by DL 


# Set the environment variables
. $HOME/bin/boa-aspr_environment
program=`basename $0`

export filetype=$1

#make sure filetype parm was passed as first arg
	if [ -z $filetype ]; then
echo -e "\n	File type parm is missing.  Proper syntax
	is put_boa-aspr_data filetype, where 
	file type is equal to ach or pay."
	exit 4
	fi

cd $outbound_dir

case "$filetype" in
	ach)
	export boa_file="PGP ACH PAYRLW CAFR117C"
	export file=aspr_achfile.txt
	export asc_file=${file}.asc
	export tagfile=$hcmdir/aspr_achfile.tag

echo -e "\nBegin processing $filetype file to BofA"

#crlf_rem $temp_file $file

;;

	pay)
	export boa_file="PGP ARP INBNDR GAFR131I"
	export file=appayboa.txt
	export asc_file=${file}.asc
	export tagfile=appayboa.tag
	export tagfile=$hcmdir/appayboa.tag


echo -e "\nBegin processing $filetype (ARP) file to BofA"

;;

esac

mainproc

echo -e "\nPut $filetype file to BofA complete."
