#!/bin/bash

# Set the environment variables
. $HOME/bin/`whoami`_environment

export airdir=$1

	if [ -z $airdir ]; then
echo -e "\n	Missing airline/direction parm,
	proper syntax is process_boa-apos_data airline.direction
	where airline=as or qx and direction=in or out. i.e.
	process_boa-apos_data asout\n"
	exit 4
	fi	

case "$airdir" in

	qxin)

export airline=QX
export boa_pgp_file="PGP ARP RECONM NCFS4TZ"
export local_file=qxboain
export local_pgp_file=${local_file}.pgp

echo -e "\nBegin processing for QX inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"

;;

	asout)

airline=AS
export data_file=appayboa
export data_file_asc=${data_file}.asc
export boa_pgp_file="PGP APR ISSUED NCFR4TY"
export tag_file=${data_file}.tag

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $data_file"

;;

	qxout)

export airline=QX
export data_file=qppayboa
export data_file_asc=${data_file}.asc
export boa_pgp_file="PGP ARP INBNDR GAFR5KK"
export tag_file=${data_file}.tag

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $data_file"

;;

esac
