#!/bin/bash

# Set up the Bank of America comsumer credit card data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/boa_new_environment"

export PGPPASS=seavvdmzftp
export ftp_host=elink-ftp4.bankofamerica.com
export ftp_local_host=asprodftp 	#prod
#export ftp_local_host=testftp 		#test
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export datestamp2=`/bin/date '+%b.%d.%Y'`
export data_file="BCBOACONSUMERPIT.txt"
export data_asc_file=${data_file}.asc 
export debug_to="dean.liebrich@alaskaair.com"
export info_to="alaskarewardsfileconf@bankofamerica.com, Lisa.Raefield@Alaskaair.com,Jennifer.Harrison@Alaskaair.com"
export errors_to="dean.liebrich@alaskaair.com,joanne.gies@alaskaair.com"
export FileAge=20

. /opt/local/ops_scripts/function_lib
