#!/bin/bash

# Encrypt the AS data file and push to BofA Employee Incentive

# Set the environment variables
. $HOME/bin/boa-emp_environment
program=`basename $0`

cd $outbound_dir

#begin AMS
export gpg_sig=BOAPUBKY
export account=AMS
export basename=AAGPY008_VisaIncentElig
export outfile=${basename}.txt
export gpg_file=${outfile}.asc
export boa_file="PGP $account INBNDM CAFR$account"
export tagfile=$hcmout_dir/${basename}.tag
export ftpcmd=passive

echo -e "\nexecuting sub routine encyrpt"
encrypt

echo -e "\nexecuting sub routine putfile"
#putfile
#end AMS

#begin MBNA
export account=MBNA
export basename=AAGPY008_VisaIncentElig
export outfile=${basename}.txt
export dir=incoming/products
tagfile=$hcmout_dir/${basename}.tag

echo -e "\nexecuting sub routine putfile1"
putfile

echo -e "\nexecuting sub routine cleanup"
cleanup
#end MBNA
