#!/bin/bash

# Set up the Bank of America Employee incentive visa data transfer environment

export PGPPASS=seavvdmzftp
export sftp_host=jgalaska@b2b22.bankofamerica.com
#export ftp_host=elink-ftp4.bankofamerica.com
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export hcmdir=/home/hcmprod
export hcmout_dir=${hcmdir}/outbound/bankofamerica
export hcmin_dir=${hcmdir}/inbound/bankofamerica
export datestamp=`/bin/date +%b%d%Y.%H%M`
export FileAge=90
export outputerrors_to="production.services@alaskaair.com"
export errors_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export last_file_received=$HOME/last_file_received

. /opt/local/ops_scripts/function_lib

function inproc {

cd $inbound_dir

echo -e "\nConnect to BOA and get $inloc_file"
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	cd outgoing
	get $inloc_file
        dir
	quit
PUT
	result=$?

      if [ $result -ne 0 ]; then
      echo -e "\nget $remote_file_in from $sftp_host failed"
	echo "contents of outgoing"
	ls -l outgoing
       exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

records=`wc $inloc_file | awk '{print $2}'`
echo -e "\nBOA file $inloc_file ($records records) received at `date`"

securezip $inloc_file inbound

echo -e "\ncopy $inloc_file to $hcmin_dir"
cp $inloc_file $hcmin_dir
chmod 660 $hcmin_dir/$inloc_file

echo -e "\ncreate tag file"
touch $hcmin_dir/$tagfile
chmod 660 $hcmin_dir/$tagfile

echo -e "\nclean up inbound directory"
rm -fv $inloc_file $boa_visa_file 

echo -e "\nmove $inloc_pgp_file to $inbound_archive and date stamp"
mv  $inloc_file $inbound_archive/$inloc_file.$datestamp

echo -e "\nremove files older than $FileAge days from archive directory"
	find $inbound_archive/$inloc_pgp_file* -mtime +$FileAge -print |

	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

}

export inloc_file=boavisabus.prn
tagfile=$hcmin_dir/boavisabus.prn.tag

echo -e "Begin processing for inbound Visabus file"
inproc
echo -e "\nInbound Visabus file processing complete" 


