#!/bin/bash

# Set up the BOA solar enrollment data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/solarenroll_environment"


export PGPPASS=seavvdmzftp
export remote_sig=BOAPUBKY
export ftp_host=elink-ftp4.bankofamerica.com
export ftp_local_host=asprodftp
export lz=mpprod
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export file_prefix=BCBOABUSINESSPIT
export boa_pgp_file=${file_prefix}.txt
export local_pgp_file=${boa_pgp_file}.pgp
export remote_file=${file_prefix}_HB
export remote_pgp_file=${remote_file}.txt
export DT=`date '+%c'`
export info_to="alaskarewardsfileconf@bankofamerica.com,joanne.gies@alaskaair.com,Lisa.Raefield@Alaskaair.com,Jennifer.Harrison@Alaskaair.com"
export datestamp=`/bin/date '+%b%d%Y.%H%M'`
export datestamp2=`/bin/date '+%b.%d.%Y'`
export outdate=`/bin/date '+%Y%m%d'`
export errors_to="dean.liebrich@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20

. /opt/local/ops_scripts/function_lib

function outproc {

rm ~/.netrc
ln -s ~/.netrc.outbound ~/.netrc

cd $outbound_dir

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $file_prefix

export solar_file=`ls -1 $file_prefix*`
echo -e "\nprocessing outbound file $solar_file"

# rename file for handoff to bank
mv $solar_file $remote_file

securezip $remote_file outbound

echo -e "\nencrypt file $solar_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor --sign -r $remote_sig --output $remote_pgp_file --encrypt $remote_file
	
	result=$?

	if [ $result -ne 0 -o ! -f $remote_pgp_file ]; then
	echo "file $remote_pgp_file encryption failure"
	exit 8
	fi

ftp_check $ftp_host
ftp_vendor $ftp_host $remote_pgp_file $remote_pgp_file passive bin

echo -e "\nremove temporary files"
rm -f $remote_file $remote_pgp_file

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

archive_clean $outbound_archive $remote_file $FileAge

}

function inproc {

rm ~/.netrc
ln -s ~/.netrc.psolarin ~/.netrc

cd $inbound_dir

ftp_check $ftp_host
ftp_vendor_get $ftp_host $boa_pgp_file $local_pgp_file passive bin

echo -e "\ndecrypt $local_pgp_file" 
echo $PGPPASS | gpg --passphrase-f 0 --batch --output $boa_pgp_file --decrypt $local_pgp_file

	result=$?

	if [ $result -ne 0 -o ! -s $boa_pgp_file ]; then
	echo -e "\n`whoami` $local_pgp_file decrypt problem.\n"
	exit 8
	fi

record_count=`wc -l $boa_pgp_file | awk '{print $1}'`
echo -e "\n$boa_pgp_file record count is $record_count on `date`"

ftp_solar_in $ftp_local_host $boa_pgp_file

echo -e "send confirmation email to BOA"
echo -e "$boa_pgp_file file has been received by Alaska Airlines.
Thank You." | mutt -s "$boa_pgp_file Received $datestamp2" $info_to

echo -e "\nmove $local_pgp_file to archive directory and timestamp"
mv $local_pgp_file $inbound_archive/$local_pgp_file.$datestamp

echo "remove temp file $boa_pgp_file"
rm -f $boa_pgp_file

archive_clean $inbound_archive $local_pgp_file $FileAge

}
