#!/bin/bash

# Set up the Bank of America Employee incentive visa data transfer environment

export PGPPASS=seavvdmzftp
export sftp_host=jgalaska@b2b22.bankofamerica.com
export ftp_local_host=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export filedir=mpprod/bankcardupdate/input
export datestamp=`/bin/date +%b%d%Y.%H%M`
export FileAge=10
export logfile=$HOME/transfer_log

. /opt/local/ops_scripts/function_lib

filetype=$1

#make sure filetype parm was passed in as first arg
        if [ -z $filetype ]; then
echo -e "\n     Missing filetype parm.
        proper syntax is: process_qantas_file filetype where
        filetype equals open or closed\n"
        exit 4
        fi

function inproc {

cd $inbound_dir

echo -e "\nConnect to BOA and get $inloc_file"
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	cd outgoing
	get $file_pref*
        dir
	quit
PUT
	result=$?

	if [ $result -ne 0 ]; then
      	echo -e "\nget $remote_file_in from $sftp_host failed"
	echo "contents of outgoing"
	ls -l outgoing
       	exit 4
        fi

data_ready=`grep -i -c -e "$file_pref" ftp_results.$$`

	if [ $data_ready -eq 0 ]; then
        MSG="There was no boa business card file to process for `date +%A`,`date +%D`."
#       echo $MSG | Mail -s "CapSystem feed" "ftp.partner.alerts@alaskaair.com"
        echo -e "\nNo business card file to process\n"
        cat ftp_results.$$
        rm -fv ftp_results.$$
        exit 0
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

export data_file=`ls -1 $file_pref*`

securezip $data_file inbound

ftp_file $ftp_local_host $data_file $data_file "cd $filedir"

echo -e "\nclean up inbound directory"
rm -fv $data_file

archive_clean $inbound_archive $file_pref $FileAge

}

case "$filetype" in

        open)
export file_pref=BCBUSCARD_OPEN
echo -e "Begin processing for inbound BCBUSCARD_OPEN file"
inproc
echo -e "\nInbound Visabus file processing complete" 
;;

        closed)
export file_pref=BOAACCTCLOSE
echo -e "Begin processing for inbound BOAACCTCLOSE file"
inproc
echo -e "\nInbound Visabus file processing complete" 
;;

esac
