#!/bin/bash

export PGPPASS=seavvdmzftp
export remote_sig=BOAPUBKY
export ftp_host=elink-ftp4.bankofamerica.com
#export ftp_local_host=testftp
export ftp_local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export DT=`date '+%c'`
export info_to="joanne.gies@alaskaair.com"
export datestamp=`/bin/date '+%b%d%Y.%H%M'`
export outdate=`/bin/date '+%Y%m%d'`
export errors_to="production.services@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=99

. /opt/local/ops_scripts/function_lib

export direction=$1

	if [ -z $direction ]; then
echo -e "\n	Missing direction_file parm,
	proper syntax is process_solarenroll_new_data direction
	where direction=IN_XX or OUT_XX. i.e.
	process_solarenroll_data\n"
	exit 4
	fi	

function inproc {

cd $inbound_dir

echo -e "\nmake record length 450 for all records"
$HOME/bin/450.pl $local_file > $crl_file

result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact EPS"
	exit 4
	fi

record_count=`wc -l $crl_file | awk '{print $1}'`
MSG="$crl_file record count is $record_count on `date`"
echo -e "\n$MSG"

ftp_vendor $ftp_local_host $crl_file $crl_file "cd MPPROD/BofAEnrollment/Input"

echo -e "\nmove $local_pgp_file to archive directory and timestamp"
mv $local_pgp_file $inbound_archive/$local_pgp_file.$datestamp

echo "remove temp files"
rm -f $local_file $crl_file $local_pgp_file

archive_clean $inbound_archive $local_pgp_file $FileAge

}

case "$direction" in

         IN_B20)

export local_file=B20PIEin
export local_pgp_file=${local_file}.pgp
export crl_file=BCBankofAmericaB20PIE.dat

echo -e "\nBegin processing for file inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"

;;

esac
