#!/bin/bash

# Set the environment variables
. $HOME/bin/solarenroll_new_test_environment

export direction=$1

	if [ -z $direction ]; then
echo -e "\n	Missing direction_file parm,
	proper syntax is process_solarenroll_new_data direction
	where direction=IN_XX or OUT_XX. i.e.
	process_solarenroll_data\n"
	exit 4
	fi	

case "$direction" in
         IN_B20)

rm ~/.netrc
ln -s ~/.netrc.tsolar20in ~/.netrc

cat $HOME/.netrc

export boa_pgp_file="BCBankofAmericaB20PIE_Test.txt"
export local_file=B20PIEin
export local_pgp_file=${local_file}.pgp
export crl_file=BCBankofAmericaB20PIE.dat


echo -e "\nBegin processing for file inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"

;;


         IN_B21)

rm ~/.netrc
ln -s ~/.netrc.psolar21in ~/.netrc

export boa_pgp_file="BCBankofAmericaB21PIE_test.txt"
export local_file=B21PIEin
export local_pgp_file=${local_file}.pgp
export crl_file=BCBankofAmericaB21PIE.dat


echo -e "\nBegin processing for file inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"

;;



         IN_B22)

rm ~/.netrc
ln -s ~/.netrc.tsolar22in ~/.netrc

export boa_pgp_file="BCBankofAmericaB22PIE_test.txt"
export local_file=B22PIEin
export local_pgp_file=${local_file}.pgp
export crl_file=BCBankofAmericaB22PIE.dat


echo -e "\nBegin processing for file inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"

;;

	OUT_B20)

rm ~/.netrc
ln -s ~/.netrc.tsolar20out ~/.netrc

export local_file=BCBankofAmericaB20PIE_HB.dat
export local_pgp_file=${local_file}.asc
export remote_pgp_file="BCBankofAmericaB20PIE_HB_test.txt"
export tag_file=${data_file}.tag

echo -e "\nBegin processing for $airline outbound file $local_file"
outproc
echo -e "\nOutbound processing complete for $airline file $local_file"

;;

	OUT_B21)

rm ~/.netrc
ln -s ~/.netrc.psolar21out ~/.netrc

cat .netrc

export local_file=BCBankofAmericaB21PIE_HB.dat
export local_pgp_file=${local_file}.asc
export remote_pgp_file="BCBankofAmericaB21PIE_HB.Test.txt"
export tag_file=${data_file}.tag

echo -e "\nBegin processing for $airline outbound file $local_file"
outproc
echo -e "\nOutbound processing complete for $airline file $local_file"

;;
	OUT_B22)


rm ~/.netrc
ln -s ~/.netrc.tsolar22out ~/.netrc

export local_file=BCBankofAmericaB22PIE_HB.dat
export local_pgp_file=${local_file}.asc
export remote_pgp_file="BCBankofAmericaB22PIE_HB_Test.txt"
export tag_file=${data_file}.tag

echo -e "\nBegin processing for $airline outbound file $local_file"
outproc
echo -e "\nOutbound processing complete for $airline file $local_file"

;;

esac
