#!/bin/bash

# Set up the Bank of America visa check card data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/boa-vcc_environment"

export PGPPASS=seavvdmzftp
export pgp_remote_signature=BOAPUBKY
export ftp_host=elink-ftp5.bankofamerica.com
export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export datestamp2=`/bin/date '+%b.%d.%Y'`
export file_prefix=BCBOADEBITPIT
export data_file=${file_prefix}.txt
export boa_file=${data_file}.asc
export handback_file=${file_prefix}_HB
export handback_asc_file=${handback_file}.txt
export FileAge=20
export info_to="alaskarewardsfileconf@bankofamerica.com,tyler.sonnen@alaskaair.com"
export errors_to="dean.liebrich@alaskaair.com"

. /opt/local/ops_scripts/function_lib
