#!/bin/bash


# Fetch data from Bank of America,
# then submit a piece of mainframe JCL to trigger file processing

# Set the environment variables
. $HOME/bin/boa_environment
program=`basename $0`

echo -e "\ndecrypt $data_asc_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $data_file --decrypt $data_asc_file
    
	result=$?

	if [ $result -ne 0 ]; then
	echo "${program}: inbound results file decrypt problem.  Call Ops Analyst."
        exit 8
	fi

echo -e "\nverify EOF record"
records=`wc -l $data_file | awk '{print $1}'`
correct_trailer=`tail -1 $data_file | grep -c '^9'`

	if [ $correct_trailer -ne 1 ]; then
	echo "${program}: BofA data file trailer record missing, contact BofA to have the file recreated."
	exit 8
	fi

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $data_file

echo -e "\nftp $data_file to mvs"
    	ftp -v bigiron <<EOF3
        ascii
        site recfm=fb lrecl=150 cylinders pri=25 sec=5 unit=prdda blksize=0
        put $data_file 'ff.ffcrtb5.bofa.ftp.activity(+1)'
        quit
EOF3
        
echo "BofA weekly data file ($records records) received at `date`"

echo -e "send confirmation email to BOA"
echo -e "$data_file file has been received by Alaska Airlines.
Thank You." | mutt -s "$data_file Received $datestamp2" $info_to

echo -e "\nmove $data_asc_file to archive directory and timestamp"
mv $data_asc_file $inbound_archive/$data_asc_file.$datestamp
    
echo -e "\ndelete $data_file"
rm -f ftp_results.$$ $data_file

archive_clean $inbound_archive $data_asc_file $FileAge
