#!/bin/bash

#This script is US Bank of America Consumer file for in accrul and enroll and handback accural
#a week. It also includes - us sending them a handback file.
#Job names are: FFBOAACCRUAL_GET FFBOAACCRUAL_PUT

set -x
export pgppass=seavvdmzftp
#export sftp_host=jgalaska@b2b22.bankofamerica.com
export sftp_host=jgalaska@b2b02u.bankofamerica.com
export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export indate=`date +%Y%m%d%H%M`
export outdate=`date +%y%m%d`
export info_to="joanne.gies@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_boaaccrual_data direction where
        direction equals accr_in or accr_out\n"
        exit 4
        fi

function outproc {

cd $outbound_dir

ftp_check $ftp_local_host

ftp_solar_out $ftp_local_host $out_file_prefix

export remote_file=`ls -1 $out_file_prefix*`
echo -e "\nprocessing outbound file $remote_file"

echo $remote_file

securezip $remote_file outbound


echo -e "\nsftp data files to $sftp_host"
	sftp -v $sftp_host <<PUT >ftp_results.$$
	cd incoming
       	put $remote_file
        dir
	bye
PUT
errorchk $? "ftp data files to $sftp_host"

#ftp_delete $ftp_local_host $remote_file "cd mpprod/outbound/handback"

echo -e "\nremove $remote file from $outbound_dir"
rm -fv $remote_file 
errorchk $? "remove $remote_file from $outbound_dir"

archive_clean $outbound_archive $file_prefix $FileAge

}

function inproc {

cd $inbound_dir

ftp_check $ftp_local_host

echo -e "\nConnect to BOA and get $remote_file_in"
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	cd outgoing
	get $remote_file_in
        dir
	quit
PUT
	result=$?

      if [ $result -ne 0 ]; then
      echo -e "\nget $remote_file_in from $sftp_host failed"
	echo "contents of outgoing"
	ls -l outgoing
       exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

securezip $remote_file_in inbound

record_count=`wc -l $remote_file_in | awk '{print $1}'`
MSG="record count is $record_count on `date`"
echo -e "\n$MSG"

ftp_solar_in $ftp_local_host $remote_file_in "cd mpprod"


echo -e "send confirmation email to BOA"
echo -e "$remote_data_in file has been received by Alaska Airlines.
Thank You." | mutt -s "$remote_data_in Received $datestamp" $info_to

echo "remove temp files"
rm -fv $remore_file_in 
errorchk $? "remove temp files from $inbound_dir"

archive_clean $inbound_archive $in_file_pref $FileAge

}

case "$direction" in 

	accr_in)

export remote_file_in=BCBOAUSCONSUMERPITTEST.txt
echo -e "\nBegin processing for Accural in file"
inproc
echo -e "\nProcessing for BOA Accrual Consumer TSYS file 'in' complete"
	;;

	accr_out)

export out_file_prefix=BCBOAUSCONSUMERPIT
echo -e "\nBegin processing for Accrual handback BOA file"
outproc
echo -e "\nProcessing for BOA accrual handback 'out' is complete"
	;;

esac
