#!/bin/bash

#This script is US Bank of America Consumer file for in accrul and enroll and handback accural
#a week. It also includes - us sending them a handback file.
#Job names are: FFTSYSBOAENROLL_PUT and  FFTYSBOAENROLL_GET

set -x
export pgppass=seavvdmzftp
#export sftp_host=jgalaska@b2b22.bankofamerica.com
export sftp_host=jgalaska@b2b02u.bankofamerica.com
export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export indate=`date +%Y%m%d%H%M`
export outdate=`date +%y%m%d`
export info_to="joanne.gies@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_boaconsumer_data direction where
        direction equals accr_in or enrollin or accr_out\n"
        exit 4
        fi

function outproc {

cd $outbound_dir

ftp_check $ftp_local_host

export out_file=BCBOAUSCONSUMERPITTESTHB.txt


echo -e "\nConnect to BOA and put  $remote_file_out"
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	cd outgoing
	get $remote_file
        dir
	quit
PUT
	result=$?

      if [ $result -ne 0 ]; then
      echo -e "\nput $zip_file to $sftp_host failed"
	echo "contents of $outbound_dir:"
	ls -l $outbound_dir
       exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

exit

#ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix

export solar_file=`ls -1 $outfile_prefix*`
echo -e "\nprocessing outbound file $solar_file"

echo $solar_file

securezip $solar_file outbound

export out_file=HF${outdate}.AS




echo -e "\nsftp data files to $sftp_host"
	sftp -v $sftp_host <<PUT >ftp_results.$$
	$chgdir
       	put $out_file
        dir
	bye
PUT
errorchk $? "ftp data files to $sftp_host"

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nremove $data_file files from $outbound_dir"
rm -fv $solar_file pgp_transcript.$$ $out_file
errorchk $? "remove $solar_file from $outbound_dir"

archive_clean $outbound_archive $file_prefix $FileAge

}

function inproc {

cd $inbound_dir

ftp_check $ftp_local_host


echo -e "\nConnect to BOA and get $remote_file_in"
	sftp -v $sftp_host <<PUT >>ftp_results.$$
	cd outgoing
	get $remote_file_in
        dir
	quit
PUT
	result=$?

      if [ $result -ne 0 ]; then
      echo -e "\nget $remote_file_in from $sftp_host failed"
	echo "contents of outgoing"
	ls -l outgoing
       exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

records=`wc $remote_file_in | awk '{print $2}'`
echo -e "\nBOA file $remote_file_in ($records records) received at `date`"

securezip $remote_file_in inbound

ftp_vendor $ftp_local_host $local_file $local_file "cd MPPROD/BofAEnrollment/Input"

echo "remove temp files"

securezip $remote_file_in inbound

echo -e "send confirmation email to BOA"
echo -e "$remote_data_in file has been received by Alaska Airlines.
Thank You." | mutt -s "$remote_data_in Received $datestamp" $info_to

echo "remove temp files"
rm -fv $remote_file_in 
errorchk $? "remove temp files from $inbound_dir"

archive_clean $inbound_archive $in_file_pref $FileAge

}

case "$direction" in 

        enroll_in)

export remote_file_in=BCBankofAmericab23PIE.dat
echo -e "\nBegin processing for Ennroll In  file"
inproc
echo -e "\nProcessing for BOA enroll Condumer TSYS file 'in' complete"
	;;


	enroll_out)

export in_file_pref=BCBOAUSCONSUMER
echo -e "\nBegin processing for Autopost 'in' file"
outproc
echo -e "\nProcessing for BOA accrual handback 'out' is complete"
	;;

esac
