#!/bin/bash

# Encrypt the AS data file and push to BofA for Visa Check Card

# Set the environment variables
. $HOME/bin/boa-vcc_environment
program=`basename $0`

cd $outbound_dir
rm ~/.netrc
ln -s ~/.netrc.outbound ~/.netrc

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $file_prefix

export solar_file=`ls -1 $file_prefix*`
echo -e "\necho processing outbound file $solar_file"

# strip off timestamp for transfer to bank
mv $solar_file $handback_file

echo -e "\nencrypt file $handback_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor --sign -r $pgp_remote_signature --output $handback_asc_file --encrypt $handback_file

	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\n$handback_file encryption failure, assign ticket to Prod. Svcs.\n"
	exit 8
	fi

ftp_vendor $ftp_host $handback_asc_file $handback_asc_file passive bin

securezip $handback_file outbound

archive_clean $outbound_archive $handback_file $FileAge

output_records=`wc -l $handback_file`
echo -e "\n$output_records records sent to $ftp_host"

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nclean up local directory"
rm -f $handback_file $handback_asc_file
