#!/bin/bash


# Fetch data from Bank of America,
# then submit a piece of mainframe JCL to trigger file processing

# Set the environment variables
. $HOME/bin/boa_environment
program=`basename $0`

rm ~/.netrc
ln -s ~/.netrc.boab5 ~/.netrc

cd $inbound_dir

ftp_check $ftp_host
echo -e "\nsee if file $data_file is available at $ftp_host"
	ftp -v $ftp_host <<EOF1 >ftp_results.$$
	passive
	dir
	quit
EOF1

data_ready=`grep -c -e "-AR-.*$data_file" ftp_results.$$`

	if [ $data_ready -eq 0 ]; then
	echo -e "\nexpected file $data_file not available at $ftp_host"
	cat ftp_results.$$
	rm ftp_result.$$
	exit 4
	fi

	if [ $data_ready -ne 1 ]; then
	echo -e "\nmore than one BofA file $data_file found at $ftp_host"
	echo -e "notify Production Services\n"
	exit 4
	fi

ftp_vendor_get $ftp_host $data_file $data_asc_file passive bin

echo -e "\ndecrypt $data_asc_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $data_file --decrypt $data_asc_file
    
	result=$?

	if [ $result -ne 0 ]; then
	echo "${program}: inbound results file decrypt problem.  Call Ops Analyst."
        exit 8
	fi

echo -e "\nverify EOF record"
records=`wc -l $data_file | awk '{print $1}'`
correct_trailer=`tail -1 $data_file | grep -c '^9'`

	if [ $correct_trailer -ne 1 ]; then
	echo "${program}: BofA data file trailer record missing, contact BofA to have the file recreated."
	exit 8
	fi

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $data_file

echo -e "\nftp $data_file to mvs"
    	ftp -v bigiron <<EOF3
        ascii
        site recfm=fb lrecl=150 cylinders pri=25 sec=5 unit=prdda blksize=0
        put $data_file 'ff.ffcrtb5.bofa.ftp.activity(+1)'
        quit
EOF3
        
echo "BofA weekly data file ($records records) received at `date`"

echo -e "send confirmation email to BOA"
echo -e "$data_file file has been received by Alaska Airlines.
Thank You." | mutt -s "$data_file Received $datestamp2" $info_to

echo -e "\nmove $data_asc_file to archive directory and timestamp"
mv $data_asc_file $inbound_archive/$data_asc_file.$datestamp
    
echo -e "\ndelete $data_file"
rm -f ftp_results.$$ $data_file

archive_clean $inbound_archive $data_asc_file $FileAge
