#!/bin/bash

# Encrypt the AS data file.
# Set the environment variables
. $HOME/bin/britair_environment
program=`basename $0`

cd $outbound_dir

# Is there a previous batape file in outbound dir?
# If so, datestamp and send email notification to EPS 
	if [ -s $batape_pgp_file ]; then
	mv $batape_pgp_file $batape_pgp_file.$datestamp
	echo "batape file left in outbound directory" | Mail -s "Britair outbound" $errors_to
	fi

echo -e "\ntimestamp $batape_file file"
mv $batape_file $batape_datestamp

echo -e "\nencrypt $batape_datestamp"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor --sign -r $pgp_remote_signature --output $batape_pgp_file --encrypt $batape_datestamp >pgp_transcript.$$ 2>&1

	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nBatape file encryption failure, contact EPS."
	cat pgp_transcript.$$
  	exit 8
	fi

rm -f pgp_transcript.$$

echo -e "\nput file $batape_pgp_file to $ftp_host"
	ftp -v $ftp_host <<PUTDATA >ftp_results.$$
	cd to-ba
	put $batape_pgp_file 
	quit  
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nFTP put of $batape_pgp_file to Britair failed."
	echo "Contact Production Services or EPS"
	cat ftp_results.$$
	exit 4
	fi

rm -f ftp_results.$$

echo -e "\nmove file $batape_datestamp to $outbound_archive"
gzip <$batape_datestamp >$outbound_archive/$batape_datestamp.gz

echo -e "\nremove archived files older than $FileAge days"
find $outbound_archive/* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

count_records=`wc -l $batape_datestamp | awk '{print $1}'` >> $logfile
echo -e "\n$count_records records sent to $ftp_host"

echo -e "\nremove temp files"
rm -f $batape_pgp_file $tagfile $batape_datestamp $ftp_results.$$
