#!/bin/bash

# Process data from britair, then uploadad to windows

# Set the environment variables
. $HOME/bin/britair_environment

cd $inbound_dir

echo -e "\ndelete britair file at $ftp_host"
	ftp -i $ftp_host <<DELETE
	cd from-ba
	mdel ASAUBAPTD*.asc.done
	quit
DELETE

echo -e "\ncheck for current file at britair"
	ftp $ftp_host <<CHECK >ftp_results.$$ 2>&1
	cd from-ba
	dir
	quit
CHECK
 
echo -e "\nftp results:"
cat ftp_results.$$

data_ready=`cat ftp_results.$$ | grep -i $britair_file | grep -i -c "0.asc"` 
britair_asc_file=`cat ftp_results.$$ | grep -i $britair_file | grep -i "0.asc" | awk '{print $9}'`

	if [ $data_ready -eq 0 ]; then
	echo -e "\nIncoming britair file expected, not found\n"
	cat ftp_results.$$
	rm -f ftp_results.$$
	exit 4

	else

	if [ $data_ready -gt 1 ]; then
	echo -e "\nmore than 1 file on britair server"
	echo -e "have EPS investigate...\n"
	cat ftp_results.$$
	rm -f ftp_results.$$
	exit 4
		fi
    	fi

rm -f ftp_results.$$

echo -e "\ngetting file $britair_asc_file from $ftp_host"
	ftp -v $ftp_host <<GETDATA >ftp_results.$$
	cd from-ba
	get $britair_asc_file
	quit  
GETDATA
	result=$?

	if [ $result -ne 0 -o ! -f $britair_asc_file ]; then
	echo -e "\nFTP get of $britair_asc_file from britair failed."
	echo -e "Contact Production Services\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

rm -f ftp_results.$$

echo -e "\ndecrypt $britair_asc_file" 
echo $PGPPASS | gpg --passphrase-fd 0 --batch --decrypt --output $local_file $britair_asc_file 

	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nbritair inbound file decrypt problem.\n"
	exit 8
	fi

echo -e "\nmove $britair_asc_file to archive directory and timestamp"
mv $britair_asc_file $inbound_archive/$britair_asc_file.$datestamp

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

echo -e "\nremove temp files"
rm -f $local_file

echo -e "\nrename $britair_asc_file to $britair_asc_file.done"
	ftp -v $ftp_host <<RENAME >ftp_results.$$
	cd from-ba
        rename $britair_asc_file $britair_asc_file.done
        quit 
RENAME

result=$?

	if  [ $result -ne 0 ]; then
echo "Rename of britair file failed" | Mail -s "britair FTP" $errors_to
	fi

rm -f ftp_results.$$

archive_clean $inbound_archive $britair_file $FileAge
