#!/bin/sh

# Check for, upload to windows and then archive the budget data file
set -x

export ftp_local_host=asprodftp
export lz=mpprod
export PGPPASS=seavvdmzftp
export pgp_remote_signature='alaskaair'
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export remote_pgp_file=asbudget.txt.pgp
export local_file=ZDBUDGETCARRENTALPIT.txt
export info_to="joanne.gies@alaskaair.com"
export errors_to="joanne.gies@alaskaair.com"
export FileAge=30
export rundate=`date "+%A, %B %d, %Y"`
export MAILLIST="joanne.gies@alaskaair.com"

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

echo -e "\ndecrypt file $remote_pgp_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $local_file --decrypt $remote_pgp_file

	result=$?

	if [ $result -ne 0 ]; then
	echo "`whoami` $remote_pgp_file decrypt failed."
	exit 4
	fi

records=`wc $local_file | awk '{print $2}'`

	if [ $records -eq 0 ]; then
	export MSG="Budget data file for date $rundate is empty."
	echo -e "\n$MSG\n"
	echo $MSG | Mail -s "Budget Mileage Plan data" $MAILLIST
	exit 0
	fi

echo -e "\nfile $local_file ($records records) received at `date`"

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

echo -e "\nSecure zip file"
securezip $local_file inbound

echo -e "\nclean up inbound directory"
rm -f ftp_results.$$ $local_file $remote_pgp_file

archive_clean $inbound_archive $data_file $FileAge


