#!/bin/sh

# script to process Budget car rental data
# contact info: 
#

#export ftp_host=dmz-ftp2.wizcom.com
export ftp_host=170.225.12.197
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export basename=asbudget
export rem_file=${basename}.txt
export rem_old_file=${basename}.old
export local_file=ZDBUDGETCARRENTALPIT.txt
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14

. /opt/local/ops_scripts/function_lib

export ENV=$1

        if [ -z $ENV ]; then
echo -e "\n	missing environment argument,
	please provide a parm of prod or test
	when executing this script.\n"
        exit
        fi

case $ENV in

	prod)
	export ftp_local_host=asprodftp
	export lz=mpprod
	
	;;

	test)
        export ftp_local_host=testftp
        export lz=mptest

        ;;
esac

cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

ftp_vendor_chk $ftp_host
ftp_vendor_get $ftp_host $rem_file $local_file

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nclean up $inbound_dir"

rm -f $local_file

ftp_rename $ftp_host $rem_file $rem_old_file

archive_clean $inbound_archive $local_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"
