#!/bin/bash

# Process data from capsystm, then upload to windows

# Set the environment variables
. $HOME/bin/capsystm_environment

cd $inbound_dir

#ftp_check $sftp_host
echo -e "\ndelete .done file at $sftp_host"
	sftp -v $sftp_host <<DELETE
        cd outbound
	rm *.pgp.done
	quit
DELETE

echo -e "\ncheck for current file at capsystm"
	sftp $sftp_host <<CHECK >ftp_results.$$
	cd outbound
        dir
	quit
CHECK

set -x
data_ready=`ls -1 *.txt.pgp | wc | awk '{print $1}'`
set +x

     	if [ $data_ready -eq 0 ]; then
	MSG="There were no Cap System files to process for `date +%A`,`date +%D`."
	echo $MSG | Mail -s "CapSystem feed" "ftp.partner.alerts@alaskaair.com"
	echo -e "\nNo capsystm files to process\n"
	cat ftp_results.$$
	rm -f ftp_results.$$
	exit 0

	else

	if [ $data_ready -gt 1 ]; then
	echo -e "\ntoo many files on capsystem server"
	echo -e "please investigate\n"
	cat ftp_results.$$
	rm -f ftp_results.$$
	exit 4
	fi
        fi

rm -fv ftp_results.$$

#ftp_vendor_get $ftp_host $capsystm_pgp_file $capsystm_pgp_file passive "cd outbound" 

echo -e "\nget $capsystm_pgp_file file at capsystm"
        sftp $sftp_host <<CHECK >ftp_results.$$
        cd outbound
        get $capsystm_pgp_file $inbound_dir
        quit
CHECK

echo -e "\ndecrypt file $capsystm_pgp_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $local_file --decrypt $capsystm_pgp_file

	result=$?

	if [ $result -ne 0 ]; then
	echo "${program}: file decrypt problem.  Assign ticket to Prod. Svcs."
        exit 8
	fi

echo -e "\nmove $capsystm_pgp_file to archive directory and timestamp"
mv -v $capsystm_pgp_file $inbound_archive/$capsystm_pgp_file.$datestamp

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

echo -e "\nrename $capsystm_pgp_file to $capsystm_pgp_file.done"
	sftp -v $sftp_host <<RENAME >ftp_results.$$
	passive
	cd outbound
	rename $capsystm_pgp_file $capsystm_pgp_file.done
	quit 
RENAME

	result=$?

	if  [ $result -ne 0 ]; then
	echo "Rename of capsystm file failed" | Mail -s "capsystm FTP" $errors_to
	fi

rm -f ftp_results.$$

echo -e "\nremove temp files"
rm -f ftp_results* $local_file

archive_clean $inbound_archive ".txt.pgp" $FileAge
