#!/bin/bash

# Set up the Cap Systems data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/capsystm_environment"

export PGPPASS=seavvdmzftp
export pgp_remote_signature="newsub production1"
export ftp_host=208.251.178.168
export sftp_host=alaskaprod@208.251.178.168
export ftp_local_host=asprodftp
export lz=mpprod
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export out_data_file=cap_padded_file
export pgpfileo=Alaska_file
export tagfile=cap_hb.tag
export data_file=capfile
export file_prefix=MMMILESFORMAGSPIT
export local_file=${file_prefix}.txt
export datestamp=`/bin/date +%b%d%Y.%H%M`
export date=`/bin/date +%Y%m%d`
export errors_to="eps@alaskaair.com,production.services@alaskaair.com"
export FileAge=20

. /opt/local/ops_scripts/function_lib
