#!/bin/bash

. $HOME/bin/capsystm_environment
program=`basename $0`

cd $outbound_dir

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $file_prefix

solar_file=`ls -1 $file_prefix*`
echo -e "\nprocessing outbound file $solar_file"

echo -e "\nmake record length 152 for all records"
$HOME/bin/152.pl $solar_file >$out_data_file
	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact SysMgnt"
	exit 4
	fi

securezip $out_data_file outbound

#echo -e "\nencrypting file $solar_file"
#echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor -r "$pgp_remote_signature" --output $pgpfileo --encrypt $out_data_file 

#	result=$?

#	if [ ! -s $out_data_file -o $result -ne 0 ]; then
#	echo -e "\n$datafile encryption failure, contact Production Analyst" 
#	exit 4
#	fi

#ftp_vendor $ftp_host $out_data_file Alaska_$date.txt passive "cd inbound"


echo -e "\nput $out_data_file to $sftp_host"
	sftp -v $sftp_host <<PUTDATA >ftp_results.$$
        cd inbound
  	put $out_data_file Alaska_$date.txt
	ls -l
	quit
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "SFTP put of magazine for miles file to capstsems"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

archive_clean $outbound_archive $out_data_file $FileAge

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nremove temp files"
rm -f $pgpfileo $solar_file $out_data_file
