#!/bin/bash

. $HOME/bin/cathay_environment
program=`basename $0`

cd $outbound_dir


echo -e "\nput $cx_file to $sftp_host"
	sftp $sftp_host <<PUTDATA >ftp_results.$$
        cd from-AS
	put $cx_file 
        dir
        ls -l
	bye
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $cx_file to Cathay failed, contact EPS"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

rm -f ftp_results.$$

count_records=`wc -l $cx_file | awk '{print $1}'`
echo -e "\n$count_records records sent to Cathay at $sftp_host"

echo -e "\nMove $cx_file to $outbound_archive"
gzip <$cx_file >$outbound_archive/$cx_file.$datestamp.gz

echo -e "\nremove archived files older than $FileAge days"
find $outbound_archive/* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

echo -e "\nclean up outbound directory"
rm -f $cx_file $tagfile ftp_results.$$

#end of script
