#!/bin/bash

# Set up the Cathay data transfer environment

export PGPPASS=seavvdmzftp
export pgp_remote_signature="Cathay Pacific"
export BATCHMODE=yes          # Turn on non-prompted PGP encrypting
export sftp_host=as#ftp@218.103.40.10
export ftp_local_host=asprodftp
export lz=mpprod
export cx_file=CXFFMPAS.AOT
export cxbill_file=CXBillingFile.txt
export cx_pgp_file=${cx_file}.pgp
export tagfile=cathay.tag
export as_file=ASFFMPCX.AOT
export local_file=CXCATHAYPACIFICPIT.txt
export as_mvs_file=ASFFMPCX
export as_pgp_file=${as_file}.pgp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export alert_recipient=dean.liebrich@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export no_file="ftp.partner.alerts@alaskaair.com,jkgroup@alaskaair.com"
export errors_to="eps@alaskaair.com"
export mvs_dsn="'ff.ffcrtcx.input(+1)'"
export mvs_jcl=$HOME/bin/ffcrtcx.jcl
export logfile=$HOME/transfer_log
export FileAge=30

. /opt/local/ops_scripts/function_lib
