#!/bin/bash

# Process data from Cathay, upload to Seavvfile1.

# Set the environment variables
. $HOME/bin/cathay_environment

cd $inbound_dir

	if [ ! -s $as_file ]; then
	MSG="expected incoming Cathay file, $as_file, not found for $date"
	echo -e "\n$MSG"
	echo -e "sending email to $no_file"
	echo $MSG | Mail -s "inbound Cathay file" $no_file
	dir
	exit 
	fi

#rename local file for SOLAR conv.
mv $as_file $local_file

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e  "\nclean up inbound directory"
rm -fv $local_file

archive_clean $inbound_archive $local_file $FileAge
