#!/bin/sh

export ftp_host=64.122.97.158
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export filesuff=_invoices
export datestamp=`/bin/date +%b%d%Y`
export errors_to="joanne.gies@alaskaair.com"
export mail_list="joanne.gies@alaskaair.com"
export FileAge=35

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

ls -1 $filesuff | while read FILE1
		do
ftp_vendor $ftp_host $FILE1 $FILE1

securezip $FILE1 outbound

archive_clean $outbound_archive $FILE1 $FileAge

rm -fv $FILE1
		done
exit


echo -e "\nput invoice files to cdccom"
ftp -v 64.122.97.158 <<EOF                    
cd incoming33
put ar_invoices
put freight_invoices
put sales_invoices
bye
EOF

result=$?

exit $result

