#!/bin/bash

set -x

export sftp_host=alaskcm@securefiletransfer.citigroup.com
export ftp_local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export findir=/home/finprod/inbound/ap_citivca
export DT=`date '+%c'`
export datestamp=`/bin/date '+%b%d%Y.%H%M'`
export outdate=`/bin/date '+%Y%m%d'`
export dom=alaskaair.com
export infor_to="joanne.gies@alaskaair.com"
#export infor_to="accountspayable@$dom,Treasury@$dom,joanne.gies@$dom"
export logfile=$HOME/transfer_log
export FileAge=40

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

cp $findir/$basename*.XML $outbound_dir

export data_file=`ls -1 $basename*`
export tag_file=`echo $data_file | sed -e 's/.XML/.tag/'`
export citi_file=`echo $data_file | sed -e 's/.XML//'`

#cp -v $data_file $citi_file

securezip $data_file outbound


echo -e "\nput $citi_pgp_file to $sftp_host"
	sftp -v $sftp_host <<PUTDATA >ftp_results.$$
  	put $data_file
	ls -l
	quit
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $citi_virtual card file to citi"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

echo -e "\nremoving temporary files"
rm -fv $data_file $tag_file $findir/$tag_file $findir/$data_file
rm -fv $citi_file $pgp_file

 
archive_clean $outbound_archive $basename $FileAge

}

function inproc {

cd $inbound_dir

echo -e "\nget $citi_pgp_file from  $sftp_host"
	sftp -v $sftp_host <<PUTDATA >ftp_results.$$
  	get $basename*
	dir
	quit
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP get of $citi $basename failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$
		
	ls -1 $basename*.txt | while read File1
		do
securezip $File1 inbound
		done

echo -e "\nprocessing file(s) `ls -1 $basename*.txt`"
cat $basename* > $datafile

echo "Send mail notification to $infor_to"
Mail -s "CITI MVC in - $Citi - File for Joanne at `date`" $infor_to < $localfile

echo "This is datafile" $datafile
echo "This is the localfile"  $localfile

echo -e "\nMove $datafile to $findir and create $tagfile"
cp $datafile $findir
 
touch $findir/$tagfile

echo -e "\nremove file on Citi server" 
	sftp -v $sftp_host <<RENMDATA >ftp_results.$$ 2>&1
      	rm $basename*.txt
        quit
RENMDATA

	result=$?

	if [ $result -ne 0 ]; then
echo -e "\nrename of file $rem_file on $sftp_host failed"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

rm -fv ftp_results.$$

echo -e "\nremove $datafile & `ls -1 $basename*.txt` files"
rm -fv $datafile $basename*.txt

archive_clean $inbound_archive $basename $FileAge

}

export filetype=$1

	if [ -z $filetype ]; then
echo -e "\n	Missing file type and/direction parm,
	proper syntax is process_citi_virtcrd_data airline.direction
	where filetype=MVCin or careq_out and direction=in or out. i.e.
	process_citi_virtcrd_data MVSin\n"
	exit 4
	fi	

case "$filetype" in

	MVCin)
	export basename=ALASKAAIRO_FPCSMVC
	export findir=/home/finprod/inbound/ap_citivca
        export datafile=ALASKAAIRO_FPCSMVC.txt
        export tagfile=ALASKAAIRO_FPCSMVC.tag

        
echo -e "\nBegin processing for Citi MVC in $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"
;;

	careq_out)
	export basename=ALASKAAIRVCAREQUEST
	export findir=/home/finprod/outbound/ap_citivca

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $datafile"
;;

	XXout)
	export basename=whatever
	export findir=/home/finprod/outbound/ap_citivca

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $data_file"
;;

esac
