#!/bin/bash

# Set the environment variable
. $HOME/bin/citi_environment

export airdir=$1

	if [ -z $airdir ]; then
echo -e "\n	Missing airline/direction parm,
	proper syntax is process_citi_data airline.direction
	where airline=as or qx and direction=in or out. i.e.
	process_citi_data asout\n"
	exit 4
	fi	

case "$airdir" in

	qxin)
	export basename=aalo-prod-AA8435TA
#       export basename=aalo-test-AA8435TA
	export findir=/home/finprod/inbound/ap_qxciti
        export Citiirlne=AA8435

echo -e "\nBegin processing for QX inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"
;;

	asin)
	export basename=aalo-prod-AA3918TA
#       export basename=aalo-test-AA3918TA
        export findir=/home/finprod/inbound/ap_asciti
        export Citiirlne=AA3918

echo -e "\nBegin processing for AS inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"
;;

	asout)
	export basename=aali-prod-AA3918AR
#       export basename=aali-test-AA3918AR
	export findir=/home/finprod/outbound/ap_asciti

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $datafile"
;;

	qxout)
	export basename=aali-prod-AA8435AR
#       export basename=aali-test-AA8435AR
	export findir=/home/finprod/outbound/ap_qxciti 

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $data_file"
;;

esac
