#!/bin/sh

# script to process Coast Hotels data
#
#	CONTACT INFO  Joh Marsh - Zdirect                      
#	FOR FTP INFORMATION:                           
#	=========================                


export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export lz=mpprod
export local_file=WXCOASTHOTELSPIT.txt
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14

. /opt/local/ops_scripts/function_lib


cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound


echo -e "\nclean up $inbound_dir"
rm -f $local_file

archive_clean $inbound_archive $local_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"
