#!/bin/bash


set -x
export ftphost=mvs
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`date +%m%d%y.%H%M`
export dcbparms=""
export fileage=20

. /opt/local/ops_scripts/function_lib

function putdsn {

cd $inbound_dir

export data_file=`ls -1 $file_pref*`

export datfile=`ls -1 $file_pref*.DAT`  Data 
export tagfile=`echo $datfile | sed -e 's/DAT/TAG/'`


dsn_2mvs $ftphost $data_file "'$dsn'" bin

echo -e "\nmove $data_file to $inbound_archive"
mv $data_file $inbound_archive

echo -e "\nremove tagfiles older than $fileage days"
#find $inbound_archive/*.tag* -mtime +$fileage -print |
#       while read FILE1
#        do
#        echo "removing file $FILE1"
#        rm -f $FILE1
#        done

}


echo -e "\nprocess tcn file"
#	export tagfile=certrecatc_tcn4.tag.comp
        export file_pref=cert_as_accb*.cmp
	export dsn=PROG.SR.SABRE.AS.ACCB
	if [ -f $tagfile ]; then

putdsn
	fi

echo -e "\nprocess tcn file"
#	export tagfile=certrecatc_tcn4.tag.comp
        export file_pref=cert_as_accb_nobill*.cmp
	export dsn=PROG.SR.SABRE.AS.ACCB.NOBILL
	if [ -f $tagfile ]; then

putdsn
	fi

echo -e "\nprocess tcn file"
#	export tagfile=certrecatc_tcn4.tag.comp
        export file_pref=cert_as_local*.cmp
	export dsn=PROG.SR.SABRE.AS.AUTH
	if [ -f $tagfile ]; then

putdsn
	fi

echo -e "\nprocess tcn file"
#	export tagfile=certrecatc_tcn4.tag.comp
        export file_pref=cert_as_auth_c*.com
	export dsn=PROG.SR.SABRE.AS.LOCAL
	if [ -f $tagfile ]; then

putdsn
	fi


echo -e "\nPresent files were sent to the mainframe"

;;

esac

