#!/bin/bash


set -x
export ftphost=mvs
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`date +%m%d%y.%H%M`
export dcbparms=""
export fileage=20

. /opt/local/ops_scripts/function_lib

function putdsn {

cd $inbound_dir

export data_file=`ls -1 $file_pref*`

dsn_2mvs $ftphost $data_file "'$dsn'" bin

echo -e "\nmove $data_file to $inbound_archive"
mv $data_file $inbound_archive

}


echo -e "\nprocess cert file"
#	export tagfile=certxxxx_xxx.tag.comp
#        export tagfile=`echo $datfile | sed -e 's/DAT/TAG/'`
        export file_pref=CERT_AS_ACCB_*.CMP
	export dsn=PROG.SR.AMRIS.RECEIVE.ASR.COMP
	if [ -f $file_pref ]; then
putdsn
	fi


echo -e "\nprocess cert file"
#	export tagfile=certxxxx_xxx.tag.comp
#        export tagfile=`echo $datfile | sed -e 's/DAT/TAG/'`
        export file_pref=CERT_AS_ACCB_*.CMP
	export dsn=PROG.SR.AMRIS.RECEIVE.ASR.COMP

	if [ -f $file_pref ]; then
putdsn
	fi

echo -e "\nprocess cert file"
#	export tagfile=certxxxx_xxx.tag.comp
#        export tagfile=`echo $datfile | sed -e 's/DAT/TAG/'`
        export file_pref=CERT_AS_ACCB_*.CMP
	export dsn=PROG.SR.AMRIS.RECEIVE.ASR.COMP
	if [ -f $file_pref ]; then
putdsn
	fi


echo -e "\nprocess cert file"
#	export tagfile=certxxxx_xxx.tag.comp
#        export tagfile=`echo $datfile | sed -e 's/DAT/TAG/'`
        export file_pref=CERT_AS_ACCB_*.CMP
	export dsn=PROG.SR.AMRIS.RECEIVE.ASR.COMP

	if [ -f $file_pref ]; then
putdsn
	fi

echo -e "\nSabre Cert  Mainframe transfer for Sabre Air complete"

;;

esac









