#!/bin/bash

program=`basename $0`

. $HOME/bin/cobra_environment_test

export airline=$1

#make sure airline parm was passed as first arg
	if [ -z $airline ]; then
echo -e "\n Missing airline parm.  Proper syntax
is put_cobra_new_data airline, where airline
is equal to as or qx."
	exit 4
	fi

case "$airline" in
 as)
	export basename=test_ASA_COBRA
	export datafile=${basename}.txt 
	export pgpfile=${basename}.$datestamp
	export hcmdir=$ashcmdir
	export tagfile=$hcmdir/${basename}.tag
cobraproc
	
	export basename=test_ASA_NEWHIRE
        export datafile=${basename}.txt  
        export pgpfile=${basename}.$datestamp
        export tagfile=$hcmdir/${basename}.tag
cobraproc

	export basename=test_ASA_RETIREE
	export datafile=${basename}.txt
       	export pgpfile=${basename}.$datestamp
       	export tagfile=$hcmdir/${basename}.tag
cobraproc


echo -e "\nCobra Service Plan data transfer for Alaska Air complete"

;;

 qx)
	basename=test_QXA_COBRA
 	export datafile=${basename}.txt 
      	export pgpfile=${basename}.$datestamp
      	export hcmdir=$qxhcmdir
      	export tagfile=$hcmdir/${basename}.tag
cobraproc

	export basename=test_QXA_NEWHIRE
        export datafile=${basename}.txt  
        export pgpfile=${basename}.$datestamp
        export tagfile=$hcmdir/${basename}.tag
cobraproc

	export basename=test_QXA_RETIREE
       	export datafile=${basename}.txt
       	export pgpfile=${basename}.$datestamp
       	export tagfile=$hcmdir/${basename}.tag 
cobraproc


echo -e "\nCobra Service Plan data transfer for Horizon Air complete"

;;

esac

Mail -s "CMS data files sent to $ftp_host at `date`" $cobra_mailto </dev/null
