#!/bin/bash

program=`basename $0`

export PGPPASS=seavvdmzftp
export pgp_remote_signature="Delta_AlaskaAir"
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export ftplocalhost=asprodftp
export ftpremotehost=ftp.delta.com
export filedate=`/bin/date +%Y%m%d`
export FileAge=30

. /opt/local/ops_scripts/function_lib

function mainproc {

rm ~/.netrc
ln -s ~/.netrc_mp ~/.netrc

cd $outbound_dir

	ftp -i -v $ftplocalhost <<GET >>ftp_results.$$
	cd "\mpprod\outbound\delta_usage"
        dir
        bin
	mget "$file_prefix"
	quit
GET

cat ftp_results.$$
rm -fv ftp_results.$$

export data_file=`ls -1 $file_prefix`

echo -e "\nencrypt $data_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor -r "$pgp_remote_signature" --output $outfilename --encrypt $data_file >pgp_transcript.$$
	
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nEncryption error on Alaska to Delta file $filename,
	notify Systems Management during normal business hours\n"
	cat pgp_transcript.$$
	rm -f pgp_transcript.$$
	exit 4
	fi

rm -fv pgp_transcript.$$

echo -e "\nThis is the data_file $data_file\n"

ftp_vendor $ftpremotehost $outfilename $outfilename bin "cd p_from_alsff2dl"

securezip $data_file outbound

echo -e "\nmove $data_file on asprodftp" 
 ftp -v $ftplocalhost <<ARCHDATA >ftp_results.$$
	cd "mpprod/outbound/delta_usage/Archive"
        put $data_file
        dir
	cd ..
        delete $data_file
	bye
ARCHDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "move to archive and delete step failed"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4 
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

rm -fv $filename $outfilename MP_Partner_Balancing_Detail_DL* FFBASDL.pgp

archive_clean $outbound_archive $file_prefix $FileAge

}

export file_prefix=MP_Partner*.csv
export outfilename=FFBASDL${filedate}.pgp
echo -e "\nbegin processing $file_prefix"
mainproc
echo -e "\nend processing for $file_prefix"


