#!/bin/bash

# Set up the Delta Air Activity data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/deltaact_environment"

export PGPPASS=seavvdmzftp
export pgp_remote_signature="Delta_AlaskaAir"
export ftp_local_host=mvs
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=dean.liebrich@alaskaair.com
export elite_file=dlelite
export elite_tag_file=${elite_file}.tag
export elite_gpg_file=${elite_file}.pgp
export elite_dsn="'prod.ffdelta.elite.data'"
export elite_out_file=CIDeltaImport.txt
export elite_out_tag=${elilte_out_file}.trigger
export dcbparms="site recfm=fb lrecl=92 blksize=0 cylinders pri=75 sec=50 unit=prdda"
export jclfile=$HOME/bin/ffdlelit.jcl
export datestamp=`/bin/date +%Y%m%d`
export FileAge=30

. /opt/local/ops_scripts/function_lib

function inproc {

cd $inbound_dir

ftp_check $ftp_local_host

echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $elite_file --decrypt $elite_gpg_file

dsn_2mvs $ftp_local_host $elite_file "$elite_dsn" 

ftp_jcl $jclfile $ftp_local_host

mv $elite_gpg_file $inbound_archive/$elite_gpg_file.$datestamp

set -x
archive_clean $inbound_archive $elite_gpg_file $FileAge
set +x

echo -e "\nclean up inbound directory"
rm -f $elite_file $elite_tag_file

}

function delta_out {

cd $outbound_dir

ftp_vendor_chk $ftp_host

ftp_vendor $ftp_host $elite_out_file $elite_out_file bin

echo -e "\nclean up outbound directory"
rm -fv $elite_out_file $elite_out_tag
rm  delta2sabre.tag

}
