#!/bin/bash

# decrypt deltaair elite file and encrypt with tdaccess for ftp to 
# sabre

# Set the environment variables
. $HOME/bin/deltaair_environment

echo -e "\nbegin processing of `whoami` inbound elite file"
inproc
echo -e "\nend of `whoami` inbound elite file"

