#!/bin/sh

# no other scripts needed

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export partner=DL
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_dir_win=\\\\seavvfile1\\ftpprod\\scheduling\\PartnerSSIM\\${partner}\\inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export sim_file=DLASMK.SIM
export tag_file=DELTASIM.TAG
export maildom=alaskaair.com
#export mail_list="dean.liebrich@$maildom"
export mail_list="ASQX.ScheduleDistribution@$maildom"
export datestamp=`/bin/date "+%Y%m%d-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H%M"`
export recdate=`/bin/date "+%Y%m%d_%H%M"`
export FileAge=7

. /opt/local/ops_scripts/function_lib

cd $inbound_dir
 
ftp_check $ftp_local_host

size_check $sim_file

export reldate=`head -6 $sim_file | tail -1 | cut -c65-71`
export relday=`head -6 $sim_file | tail -1 | cut -c65-66`
export month=`head -6 $sim_file | tail -1 | cut -c67-69`

month_cvt $month $sim_file
export in_file=dlas${newrelmon}${relday}mk.$recdate.txt

ftp_file $ftp_local_host $sim_file $in_file "cd $lzin_dir"

echo "SSIM file $sim_file for release $reldate was sent from $partner to AS on $maildate. The files can be found here: $lzin_dir_win" | Mail -s "$partner to AS SSIM file release $reldate" $mail_list

securezip $sim_file inbound

rm -fv $sim_file $tag_file

archive_clean $outbound_archive $sim_file $FileAge
