#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export ftp_host=ftp.delta.com
export partner=DL
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export maildom=alaskaair.com
#export mail_list="dean.liebrich@$maildom"
export mail_list="ASQX.ScheduleDistribution@$maildom,DL.distribution@$maildom"
export sentdate=`/bin/date "+%Y%m%d_%H%M"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7
export program=`basename $0`

. /opt/local/ops_scripts/function_lib

export fileprefix=$1

#make sure job parm was passed as first arg
	if [ -z $fileprefix ]; then
echo -e "\n Missing job parm.  Proper syntax
is put_ssim_file fileprefix, where fileprefix
is equal to dlas or asdl"
	exit 4
	fi

function mainproc {

rm ~/.netrc
ln -s ~/.netrc_ss ~/.netrc

cd $outbound_dir

sleep 30

ftp_check $ftp_local_host

echo -e "\nftp get $fileprefix file from $ftp_local_host\n"
	ftp -v -i $ftp_local_host <<MGET >ftp_results.$$
	cd $lzout_dir
	dir
	mget ${fileprefix}*
	bye
MGET
	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP get of $fileprefix file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

#remove spaces in file name if needed
namechk=`ls -1 ${fileprefix}* | wc | awk '{print $2}'`

	if [ $namechk -gt 1 ]; then
echo -e "\nrename ${fileprefix}* to `ls -1 ${fileprefix}* | sed -e 's/ /_/g'`"
mv -v ${fileprefix}* `ls -1 ${fileprefix}* | sed -e 's/ /_/g'`
	fi

export sim_file=`ls -1 ${fileprefix}*`
export arch_prefix=`echo $sim_file | sed -e 's/.txt//'`
export reldate=`head -6 $sim_file | tail -1 | cut -c65-71`

securezip $sim_file outbound

ftp_vendor $ftp_host $sim_file $out_filename "cd p_from_alask2dl"

ftp_file $ftp_local_host $sim_file ${arch_prefix}_$sentdate.txt "cd $lzout_archive"

ftp_delete $ftp_local_host $sim_file "cd $lzout_dir"

echo "SSIM file $sim_file for release $reldate was sent from AS to $partner on $maildate" | Mail -s "AS to $partner SSIM file" $mail_list

echo "remove file $sim_file"
rm -fv $sim_file

archive_clean $outbound_archive $fileprefix $FileAge

}

case "$fileprefix" in

	asdl)
export out_filename=asdlmk.sim
mainproc
       ;;

	dlas)
export out_filename=asdlop.sim
mainproc
       ;;

esac
