#!/bin/bash

. $HOME/bin/deltaair_environment
program=`basename $0`

echo -e "\nBegin processing Delta Elite file to Sabre"
export ftp_host=sgftp.sabre.com

delta_out

echo -e "\nEnd of Delta Elite file to Sabre processing"
