#!/bin/bash

# Check for and then archive the diners data file
#
# Set environment values

. $HOME/bin/diners_environment
program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_diners_file direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in)


export data_pgp_file=`ls -1 BMO-ALASKAAIR.TSY*.gpg`
echo $data_pgp_file

echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"

        ;;

        out)

echo -e "\nBegin processing for `whoami` outbound processing"
outbound
archive_clean $outbound_archive $outfile_prefix $FileAge
echo -e "\nEnd of `whoami` outbound processing"

        ;;

esac
