#!/bin/bash

export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ops=/opt/local/ops_scripts
export DT=`date '+%c'`
export datestamp=`/bin/date '+%b%d%Y.%H%M'`
export outdate=`/bin/date '+%Y%m%d'`
export errors_to="joanne.gies@alaskaair.com"
export mail_local="accounts.receivable@alaskaair.com,fire.team.oncall.support@alaskaair.com,joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=60

export airdir=$1

	if [ -z $airdir ]; then
echo -e "\n	Missing airline/direction parm,
	proper syntax is process_discover_data direction
	where direction=in or out. i.e.
	process_discover_data asout\n"
	exit 4
	fi	

case "$airdir" in

	in)
export conf_file=discvr_confirm.txt

echo -e "\nBegin processing for inbound $conf_file"
inproc
echo -e "\nInbound processing complete for $conf_file"
;;

	out)
export data_file=alaska_file.tmp
export crlfile=discover_crlf
export out_data_file=alaska_file.dat

echo -e "\nBegin processing for discover outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for discover file $data_file"
;;

esac
