#!/bin/bash

# script to process Dollar car rental data
# contact info: JEANIE DANCER  1-918-669-3085 
# 	        JEANIE.DANCER@DOLLAR.COM
#

# Set environment values
. $HOME/bin/dollar_environment
program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_dollar_file direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in)

export file_name=ZRDOLLARCARRENTALPIT.txt

echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"

        ;;

        out)

export file_name=ASHandback.$datestamp

echo -e "\nBegin processing for `whoami` outbound processing"
outbound
echo -e "\nEnd of `whoami` outbound processing"

        ;;

esac
