#!/bin/sh

# script to process Dollar car rental data
# contact info: JEANIE DANCER  1-918-669-3085 
# 	        JEANIE.DANCER@DOLLAR.COM
#

export ftp_host=ftp.dollar.com
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export rem_file=dollar.txt
export rem_old_file=${rem_file}.old
export local_file=ZRDOLLARCARRENTALPIT.txt
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14

. /opt/local/ops_scripts/function_lib

export ENV=$1

        if [ -z $ENV ]; then
echo -e "\n	missing environment argument,
	please provide a parm of prod or test
	when executing this script.\n"
        exit
        fi

case $ENV in

	prod)
	export ftp_local_host=asprodftp
	export lz=mpprod
	
	;;

	test)
        export ftp_local_host=testftp
        export lz=mptest

        ;;
esac

cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

ftp_vendor_chk $ftp_host
ftp_vendor_get $ftp_host $rem_file $local_file "cd out"

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nclean up $inbound_dir"
rm -f $local_file

ftp_delete $ftp_host $rem_old_file "cd out"
ftp_rename $ftp_host $rem_file $rem_old_file "cd out"

archive_clean $inbound_archive $local_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"

