#!/bin/bash

program=`basename $0`

export datestamp=`/bin/date +%b%d%Y.%H%M`
export ops=/opt/local/ops_scripts
export DOM=".alaskaair.com"
export maildate=`date "+%B %d, %Y"`
export maillist="Dave.Hehyawi$DOM,Brian.Malone$DOM,Christopher.Gregory$DOM,David.Kim$DOM,ATLAS.administration$DOM"
#export maillist=dean.liebrich@$DOM
export inbound_dir=$HOME/inbound
export donefile=sabrebidt.done
export MSG="$maildate: still waiting to receive the SABRE bidt file."

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

if [ ! -f  $donefile ]; then

echo -e "\nsend notification that Sabre BIDT file has not been received"
echo $MSG | Mail -s "Sabre BIDT file late" $maillist

rm -f $donefile

exit
	else

rm -f $donefile

fi
