#!/bin/bash

. $HOME/bin/elavon_environment
program=`basename $0`

export direction=$1

	if [ -z $direction ]; then
echo -e "\n	Missing direction parm.
	proper syntax is: put_amex_data direction
	where direction equals OUT or OUT1\n"
	exit 4
	fi

case "$direction" in 
	OUT)

export basename=x340.alskair.t200
export tempfile=${basename}.tmp
export datafile=${basename}
export tagfile=elavon.tag
	
echo -e "\nBegin processing for $datafile"
outproc
echo -e "\nProcessing for $datafile complete"

	;;

	IN)

	
echo -e "\nBegin processing for hand back file"
inproc
echo -e "\nProcessing for hand back file complete"

	;;

esac

#end of script
