#!/bin/bash

# Jan 2009 - Set up the elavon (aka US Bank) data transfer environment
# Modifications - 

export sftp_host=cg260600@ftpsb.usbank.com
export testsftp_host=cg260600@ftpst.usbank.com
export local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export logfile=$HOME/transfer_log
export outfile_prefix=confile
export FileAge=30
export ops=/opt/local/ops_scripts
export mail_to="Accounts.Receivable@alaskaair.com"

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

echo -e "\nremove carriage reterns & line feeds from $tempfile and create $datafile"
crlf_rem $tempfile $datafile

#Check for connectivity to Elavon (US Bank)
echo -e "\ncheck for ftp connectivity to $sftp_host"
	sftp -v -o port=20022 $sftp_host <<TEST >ftp_results.$$
	pwd
	bye
TEST

ftptest=`grep -i -c -e "cg260600" ftp_results.$$`

	if [ $ftptest -lt 1 ]; then
echo -e "\nUNABLE TO OPEN SFTP SESSION TO $sftp_host\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	else
echo -e "\nconnection to $sftp_host confirmed, processing continues...\n"
rm ftp_results.$$
	fi

echo -e "\nPush file from seavvftp to Elavon (us bank)"
echo -e "\nput $datafile to $sftp_host"
	sftp -v -o port=20022 $sftp_host <<PUTDATA >ftp_results.$$
        cd /cg260601
	put $datafile     
	dir
	quit
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $datafile to Elavon failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

echo -e "\nmove $datafile to $outbound_archive/$datafile.$datestamp.gz"
gzip <$datafile >$outbound_archive/$datafile.$datestamp.gz

echo -e "\nremove archived files older than $FileAge days"
find $outbound_archive/$datafile* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

echo -e "\nclean up outbound directory\n"
rm -fv $tagfile $tempfile $datafile

}


function inproc {

cd $inbound_dir

#set handbackfile name
export handbackfile=`ls -1|grep $outfile_prefix`

ftp_check $local_host 

#call function to push dataset to $local_host
ftp_file $local_host $handbackfile $handbackfile "cd AR_AccountsReceivable/Aging"

echo -e "\nsend email notification to Accounts.Receivable@alaskaair.com"
Mail -s "Visa\Master Card handback file is now on our server." $mail_to < $handbackfile

securezip $handbackfile inbound

archive_clean $inbound_archive $outfile_prefix $FileAge

echo -e "\nremove file $handbackfile from inbound dir"
rm -f $handbackfile

}
