#!/bin/bash

export ftp_local_host=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=eps@alaskaair.com
export filedate=`date +%Y%m%d`
export tagext=".tag"
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="joanne.gies@alaskaair.com"
export FileAge=10

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

export emeryair_file=`ls -1 *.zip`

echo #-e "\ndelete $emeryair_file on asprodftp" 
        ftp -v asprodftp <<DELDATA >ftp_results.$$
	cd "MTX_Vendor_FTP\Emery\Archive"
        put $emeryair_file $emeryair_file
        dir
	cd ..
        delete $emeryair_file
	bye
DELDATA

cat ftp_results.$$

rm -f ftp_results.$$ *.zip ftp_results*
