#!/bin/bash

# Set up the emiles data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/emiles_environment"

export PGPPASS=seavvdmzftp
export pgp_remote_signature='emi-operations'
export sftp_host=eriala@transfer.e-miles.com
export ftp_local_host=asprodftp
#export lz=mptest
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=eps@alaskaair.com
export datestamp=`/bin/date +%m%d%Y%H%M`
#export datestamp=`/bin/date +%Y%m%d`
export nofiledate=`/bin/date "+%A, %D"`
export rem_in_file=emiles_accrual.gpg
#export rem_in_file=alaskaair.accrual.20100518
export local_file=EMEMILESPIT.txt
export outfile_prefix=EMEMILESPIT
export out_data_file=emiles_handbk_out
export out_pgp_file=alaskaair.emiles.handback.$datestamp.txt.gpg
FileAge=30

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

function inbound {

echo -e "\nbegin processing for incoming `whoami` MP file"

echo -e "\nget file on Emiles Server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd "incoming"
       	get $rem_in_file
        quit
GETDATA

echo -e "decrypt $rem_in_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $local_file --decrypt $rem_in_file    
	result=$?

	if [ $result -ne 0 ]; then
	echo "${program}: inbound results file decrypt problem.  Call Systems Management"
        exit 8
	fi


records=`wc $local_file | awk '{print $2}'`

	if [ $records -eq 0 ]; then
	export MSG="emile data file for date $rundate is empty."
	echo -e "\n$MSG\n"
	echo $MSG | Mail -s "emiles Mileage Plan data" $MAILLIST
	mv $local_file $inbound_archive/$local_file.MT.$datestamp
	exit 0
	fi

echo -e "\n$local_file file ($records records) received at `date`"

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\ncleaning up inbound directory"
rm -f $local_file $rem_in_file $solar_file

archive_clean $inbound_archive $local_file $FileAge

}

function outbound {

cd $outbound_dir

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix

export solar_file=`ls -1 $outfile_prefix*`
echo -e "\nprocessing outbound file $solar_file"

echo -e "\nmake record length 152 for all records"
$HOME/bin/152.pl $solar_file >$out_data_file
	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact EPS"
	exit 4
	fi

securezip $out_data_file outbound

echo -e "\nencrypt $solar_file (output to $handback_pgp_file)"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor -r "$pgp_remote_signature" --output $out_pgp_file --encrypt $out_data_file >pgp_transcript.$$ 2>&1
	
	result=$?

	if [ ! -s $out_pgp_file -o $result -ne 0 ]; then
	echo -e "\n$solar_file encryption failure\n" 
	cat pgp_transcript.$$
	rm -fv pgp_transcript.$$
	exit 4
	fi

rm -fv pgp_transcript.$$

echo -e "\nput  $out_pgp_file on Emiles server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd "outgoing"
       	put $out_pgp_file $out_pgp_file.txt
        ls -l
        quit
GETDATA


mv $out_pgp_file $out_pgp_file.$datestamp.gpg

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "remove local files in outbound"
rm $out_pgp_file $solar_file $out_pgp_file* $out_data_file

archive_clean $outbound_archive $out_data_file $FileAge

}
