#!/bin/bash

export PGPPASS=seavvdmzftp
export sftp_host=as@crisekftp.emirates.com
export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%Y%m%d`
export nofiledate=`/bin/date "+%A, %D"`
export local_file=EKEMIRATESAIRWAYSPIT.txt
export EMIRATES_MAILLIST="loyaltyoperation@emirates.com.au,loyaltysupport@emirates.com.au"
export FileAge=20
export ops=/opt/local/ops_scripts


. /opt/local/ops_scripts/function_lib

export direction=$1

function outproc {

cd $outbound_dir

ftp_check $ftp_local_host
ftp_check $ftp_host

echo -e "\nget file from $ftp_local_host"
        ftp -iv $ftp_local_host <<GETDATA > ftp_results.$$
        cd $filedir
        mget $file_pref*
GETDATA
        result=$?

        if [ $result -ne 0 ]; then
        echo -e  "\nftp get file from $ftp_local_host failed, contact EPS"
        cat ftp_results.$$
        rm -v ftp_results.$$
        exit 4
        fi

        cat ftp_results.$$
        rm -v ftp_results.$$

export data_file=`ls -1 $file_pref*`

echo -e "\nget file from $sftp_host"
        sftp -v $sftp_host <<PUTDATA > ftp_results.$$
	cd as2ek
        put $data_file
PUTDATA
        
	result=$?

        if [ $result -ne 0 ]; then
        echo -e  "\nput file to $sftp_host failed, contact EPS"
        cat ftp_results.$$
        rm -v ftp_results.$$
        exit 4
        fi

securezip $data_file outbound

ftp_file $ftp_local_host $data_file $data_file "cd $filedir/archive"

ftp_delete $ftp_local_host $data_file "cd $filedir"

ftp_delete $ftp_local_host $tag_file "cd $filedir"

rm -fv $data_file 

archive_clean $outbound_archive $file_pref $FileAge

}

function inproc {

echo -e "\nget file on emirates server"
        sftp $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd ek2as
        dir
        mget $file_pref*
        quit
GETDATA

        result=$?

        if [ $result -ne 0 ]; then
        echo "FTP get of Emirates file(s) failed"
        cat ftp_results.$$
        rm ftp_results.$$
        exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

ls -1 $file_pref* | while read FILE1
	do

echo -e "\nProcessing file $FILE1"

echo -e "\nDelete $FILE1 on Emirates server"
        ftp -v $ftp_host <<RENMDATA >ftp_results.$$ 2>&1
        cd as2ek
        del $FILE1
        quit
RENMDATA

        result=$?

        if [ $result -ne 0 ]; then
echo -e "\nDelete of file $FILE1 on $ftp_host failed"
        cat ftp_results.$$
        rm -fv ftp_results.$$
        exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

ftp_file $ftp_local_host $data_file $data_file "cd $filedir"

echo -e "\ncleaning up inbound directory"
mv -v $FILE1 $inbound_archive

	done

archive_clean $inbound_archive $file_pref $FileAge

}

case "$direction" in 

        retro_in)
export file_pref=emiratesqueries
export filedir=mpprod/retrocredit/OALquery/EK
echo -e "\nBegin processing for retro in file"
inproc
echo -e "\nProcessing for emirates retro file in complete"
        ;;

        response_in)
export file_pref=ASResponse_EK
export filedir=mpprod/retrocredit/ASResponse/EK
echo -e "\nBegin processing for handback in file"
inproc
echo -e "\nProcessing for JL on AS Retropost in complete"
        ;;

        retro_out)
export file_pref=ASQuery_EK
export filedir=mpprod/retrocredit/ASQuery/EK
export tag_file=EK_Member_Query_TAG.txt
echo -e "\nBegin processing for retro in file"
outproc
echo -e "\nProcessing for emirates retro file in complete"
        ;;


        response_out)
export file_pref=EmiratesResponses_ASsend
export tag_file=EK_MEMBER_RESPONSE_TAG.TXT
export filedir=mpprod/retrocredit/OALresponse/EK
echo -e "\nBegin processing for handback in file"
outproc
echo -e "\nProcessing for AS response out is complete"
        ;;

esac
