#!/bin/bash

# Pull or push files from/to Emirates.
#
# Set environment values

. $HOME/bin/emirates_environment
program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_emirates_file direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in)

export data_file=ASTRFOUT.txt
export local_file=EKEMIRATESPIT.txt
echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"

        ;;

        out)

export out_data_file=ASTRFIN
export out_data_date_file=${out_data_file}$datestamp.txt
export out_pgp_file=${out_data_date_file}.pgp
export tag_file=emirates.tag

echo -e "\nBegin processing for `whoami` outbound processing"
outbound
echo -e "\nEnd of `whoami` outbound processing"

        ;;

        inbill)

#export data_file=ASACFOUT_SEP15.txt
export data_file=ASACFOUT.txt
export local_file=ASACFOUT$datestamp.txt
echo -e "\nBegin processing for `whoami` inbound processing"
inboundbill
echo -e "\nEnd of `whoami` inbound processing"

        ;;

        outbill)

      
echo -e "\nBegin processing for `whoami` outbound processing"
outboundbill
echo -e "\nEnd of `whoami` outbound processing"

        ;;

esac
