#!/bin/bash

export sftp_host=as@crisekftp.emirates.com
export lz=mpprod/outbound/EKEliteTier
export ftp_local_host=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export filepref=ASTTR_
export tagfile=_MEMBER_RESPONSE_TAG.TXT
export nofiledate=`/bin/date "+%A, %D"`
export emirates_MAILLIST="dean.liebrich@alaskaair.com"
export FileAge=15

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

echo -e "\nget $filepref file from $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "$lz"
       	mget $filepref*
        dir
       quit
GETDATA

errorchk $? "get $filepref file from $ftp_local_host"

set -x

export data_file=`ls -1 $filepref*`

securezip $data_file outbound

echo -e "\nput file on Emirates server" 
	sftp -v $sftp_host <<PUTDATA >ftp_results.$$ 2>&1
        cd "as2ek"
       	put $data_file
        dir
       quit
PUTDATA

errorchk $? "put file on Emirates server"

echo -e "\narchive & delete $data_file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<ARCHDATA >ftp_results.$$ 2>&1
        cd "$lz/Archive"
       	put $data_file
	cd ..
	del $data_file
	del $tagfile
        dir
       quit
ARCHDATA

errorchk $? "archive & delete $data_file on $ftp_local_host"

echo -e "\nremove local files in outbound"
rm -fv $data_file $ftp_results.$$

archive_clean $outbound_archive $filepref $FileAge

