#!/bin/bash

set -x

# Set up the Epsilon BOA-ITA transfer environment
# This script is stand alone.

export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export info_to="production.services@alaskaair.com"
export email_to="joanne.gies@alaskaair.com"
export nofiledate=`/bin/date "+%A, %D"`
FileAge=30

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

ls -1 Final*.csv.pgp > text.txt

#Run through this loop for each *.csv.pgp file that is found in the inbound directory.

ls -1 Final_*.csv.pgp | while read FILE1
do

	# Define the variables of the files to be processed.
	export pgp_file=$FILE1
	export local_file=`echo $FILE1 | sed -e 's/.pgp//'`   #File name without the PGP  Should be something.csv
	# Decrypt the encrypted file
	echo -e "\ndecrypt file $pgp_file"
	echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $local_file --decrypt $pgp_file
	
	# FTP received file from inbound dir to SEAVVFILE1
	echo -e "\nCall function to push $local_file to $ftp_local_host (SEAVVFILE1)"
	ftp_file $ftp_local_host $local_file $local_file "cd mpprod/epsilon" 

	# Clean up inbound dir
	echo -e "\nMove $pgp_file to $inbound_archive/$pgp_file.$datestamp and remove $local_file"
	mv -fv $pgp_file $inbound_archive/$pgp_file.$datestamp
	rm -fv $local_file

done

# Send email to users that the files have been received.
	Mail -s "`whoami` Epison BOA-ITA are ready for your viewing on seavvfile1" $email_to < text.txt

# Call function 'archive_clean' to delete old archived files.
	archive_clean $inbound_archive Final* $FileAge

rm text.txt
