#!/bin/bash

# Encrypt the AS BofA/epsilon convmail data file.
# Set the environment variables
. $HOME/bin/epsilon_environment
program=`basename $0`

cd $outbound_dir

# Is there a previous convmail file in outbound dir?
# If so, datestamp and send email notification to EPS 
if [ -s $conv_file_pgp ]; then
mv $conv_file_pgp $conv_file_pgp.$datestamp
fi

echo -e "\nmake record length 206 for all records"
$HOME/bin/206.pl $conv_temp_file >$conv_file

result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact EPS"
	exit 4
	fi

record_count=`wc -l $conv_file | awk '{print $1}'`
MSG="$conv_file record count is $record_count on `date`"
echo -e "\n$MSG"

echo -e "\npgp encrypt $conv_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v -r $pgp_remote_signature --output $conv_file_pgp --encrypt $conv_file >pgp_transcript.$$

result=$?
	
	if [ $result -ne 0 -o ! -f $conv_file_pgp ]; then
	echo -e "\n$conv_file encryption failure, contact EPS."
	cat pgp_transcript.$$
	rm pgp_transcript.$$
  	exit 8
	fi

rm -f pgp_transcript.$$

echo -e "\nremove archived files older than $FileAge days"
find $outbound_archive/* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

echo -e "\nremove temp files"
rm -f $tagconv $conv_file $conv_temp_file

