#!/bin/bash

# Check for and then archive the FAIRMONT data file
#

# Set environment values
. $HOME/bin/fairmont_environment
program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_fairmont_data direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in)

export file_name=FAPOST.DAT
echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"
        ;;

        out)

export file_name=fairmont_handback
echo -e "\nBegin processing for `whoami` outbound processing"
outbound
echo -e "\nEnd of `whoami` outbound processing"
        ;;

esac
