#!/bin/sh

# script to process Flower Club data
# contact info:
#

#export ftp_host=65.198.163.248
export sftp_host=FFFLWRCLUB_GET
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export basename=alaska_flowerclub
export rem_file=${basename}.txt
export rem_old_file=${basename}.old
export local_file=FCFLOWERCLUBPIT.txt
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14

. /opt/local/ops_scripts/function_lib

export ENV=$1

        if [ -z $ENV ]; then
echo -e "\n	missing environment argument,
	please provide a parm of prod or test
	when executing this script.\n"
        exit
        fi

case $ENV in

	prod)
	export ftp_local_host=asprodftp
	export lz=mpprod
	
	;;

	test)
        export ftp_local_host=testftp
        export lz=mptest

        ;;
esac

cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

ftp_vendor_chk $ftp_host
ftp_check $ftp_local_host

ftp_vendor_get $ftp_host $rem_file $local_file

ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nclean up $inbound_dir"
rm -fv $local_file

ftp_delete $ftp_host $rem__old_file
ftp_rename $ftp_host $rem_file $rem_old_file

archive_clean $inbound_archive $local_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"
