#!/bin/bash

program=`basename $0`

export PGPPASS=seavvdmzftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export remote_host=ftp.gomez.com
export filedate=`/bin/date +%Y%m%d`
export FileAge=2
export ftp_local_host=asprodftp
export mail_to="joanne.gies@alaskaair.com"

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

	ftp -v $remote_host <<GET >>ftp_results.$$
        bin
        prompt
        cd archive
        mget *.zip
  	quit
GET
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nftp get of all zip files failed... fix it"
cat ftp_results.$$
rm -fv ftp_results.$$	
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

	ls -1 *.zip | while read File1
	do

echo -e "\nprocessing Gomez $File1"
unzip $File1 

securezip $File1 inbound

	done

	ftp -v $ftp_local_host <<GET >>ftp_results.$$
        prompt
        cd "BI/IT_Operations/Gomez"
        mput *.txt

  	quit
GET
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nftp put of Gomez files to seavvfile1 failed... fix it"
cat ftp_results.$$
rm -fv ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv *.txt ftp_results.$$

archive_clean $inbound_archive *.zip $FileAge

#echo -e "\nemail to MLR Team that files have been received from Gomez"
#Mail -s "File(s) are available on Seavvfile1 from Gomez" $mail_to </dev/null



