#!/bin/bash

# Set up the GuestLogix data transfer environment

export ftp_localhost=asprodftp
export datestamp=`/bin/date +%b%d%Y.%H%M`
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export alert_recipient=tyler.sonnen@alaskaair.com
export mailto="tyler.sonnen@alaskaair.com"
export FileAge=20

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

export airline=$1

	if [ -z $airline ]; then
	echo -e "\nairline parm missing, proper syntax is
	name_of_script airline, where airline is equal
	to AS or QX\n"
	exit 4
	fi

ftp_vendor_chk $ftp_localhost

	ls -1 $airline*.tag |
	while read FILE1
	do 

export tag_file=$FILE1
export data_file=`echo $tag_file | sed -e 's/tag/csv/'`

#Check to see that the data_file matches the .tag files - If no then end and send email.
	if [ ! -f $data_file ]; then 
	echo -e "\nfile $tag_file did not have a matching .csv file.  Renaming unmatched file to $tag_file.orphaned"
	mv -v $tag_file $tag_file.orphaned

	else

ftp_file $ftp_localhost $tag_file $tag_file "cd BI/revenue" "put $data_file"

#Call function to create zipped archive version of data file
securezip $data_file inbound

#Call function archive_clean to delete old archived files.
archive_clean $inbound_archive $airline $FileAge

#clean up inbound dir - Delete $tag_file"
rm -v $tag_file $data_file

	fi

	done

#Clean up any unmatched files.
ls -1 $airline*.csv |
	while read FILE1
	do
	echo -e "\nfile $FILE1 did not have a matching .tag file.  Renaming unmatched file to $FILE1.orphaned"
	mv -v $FILE1 $FILE1.orphaned 
	done

orphan_count=`ls -1 $airline*.orphaned |wc |awk '{print $1}'`
		
	if [ $orphan_count -ge 1 ]; then

ls -1 $airline*.orphaned > orphaned_list.txt
mv -v $airline*.orphaned $inbound_archive

#Email list of orphaned files to the correct folks as an attachment.
#The attached list of files did not have a matching .tag or .csv. 
echo -e "\nThe following files did not have a matching .tag or .csv file:"
cat orphaned_list.txt
rm -fv orphaned_list.txt *.orphaned

	fi
