#!/bin/bash

set -x 
export sftp_host=alaskaair@202.100.226.74@221.11.139.168
export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export crfile=tempfile
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export ops=/opt/local/ops_scripts
export datestamp=`/bin/date +%Y%m%d`
export indate=`date +%y%m%d`
export info_to="joanne.gies@alaskaair.com,dean.liebrich@alaskaair.com"
export FileAge=14

. /opt/local/ops_scripts/function_lib

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_hainan_data direction where
        direction equals one of 4\n"
        exit 4
        fi

function outproc {

cd $outbound_dir

echo -e "\ncheck for ftp connectivity to $sftp_host"
	sftp -v $sftp_host <<TEST >ftp_results.$$
	pwd
	bye
TEST

ftptest=`grep -i -c -e "Remote working directory" ftp_results.$$`

	if [ $ftptest -lt 1 ]; then
echo -e "\nUNABLE TO OPEN SFTP SESSION TO $sftp_host\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	else
echo -e "\nconnection to $sftp_host confirmed, processing continues...\n"
rm ftp_results.$$
	fi

#replace record terminator crlf (wintel) with newline (unix)
crlf_rem $out_file $crfile

echo -e "\nmake record length 300 for all records"
$HOME/bin/300.pl $crfile >$padded_file
	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact EPS"
	exit 4
	fi

echo -e "\nsftp data files to $sftp_host"
	sftp -v $sftp_host <<PUT >ftp_results.$$
	$chgdir
	put $padded_file $padded_file
	bye
PUT
rm ftp_results.$$

errorchk $? "ftp $out_file sent to $sftp_host"

securezip $out_file outbound


rm -fv $out_file $tag_file $crfile $padded_file

archive_clean $outbound_archive $basename $FileAge

}

function inproc {

cd $inbound_dir

echo -e "\nget file on Hainan server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd Rev
       	mget $in_file
        quit
GETDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP get of $in_file failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$

rm -fv ftp_results.$$

export filecnt=`ls -1 | grep -c $in_file`

	if [ $filecnt -lt 1 ]; then
echo -e "\nThere was no $in_file file to retrieve, please try again later, then if still no good, contact Jen Fearning\n"
	exit 4
	fi


echo "this is the file it is looking for: $in_file"
cat ftp_results.$$
rm -f ftp_results.$$


ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $in_file

securezip $in_file inbound

echo -e "\nDelete file on Hainan server" 
	sftp -v $sftp_host <<RENMDATA >ftp_results.$$ 2>&1
        cd Rev
     	rm $in_file
        quit
RENMDATA

	result=$?

	if [ $result -ne 0 ]; then
echo -e "\nDelete of file $in_file on $sftp_host failed"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi


echo -e "\ncleaning up inbound directory"
rm -f $in_file

archive_clean $inbound_archive $in_file_pref $FileAge

}


function inproc_hb {

cd $inbound_dir

echo -e "\nget file on Hainan server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd Rev
       	mget $basename
        quit
GETDATA

cat ftp_results.$$
rm -f ftp_results.$$

local_file=`ls -1 $basename*`

#ftp_vendor $ftp_local_host $local_file $local_file "cd MPlan\balancing\Hu_Handback"

echo -e "\npush files to mplan" 
	ftp -i -v $ftp_local_host <<GET >>ftp_results.$$
	cd "\mplan\Balancing\Hu_Handback"
        dir
        ascii
	put "$local_file"
	quit
GET

cat ftp_results.$$
rm -fv ftp_results.$$

securezip $local_file inbound

echo -e "\nDelete file on Hainan server" 
	sftp -v $sftp_host <<RENMDATA >ftp_results.$$ 2>&1
        cd Rev
      	rm $local_file
        quit
RENMDATA

	result=$?

	if [ $result -ne 0 ]; then
echo -e "\nDelete of file $in_file on $sftp_host failed"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi


echo -e "\ncleaning up inbound directory"
rm -f $local_file *

archive_clean $inbound_archive $in_file_pref $FileAge

}

function outproc_hb {

cd $outbound_dir

echo -e "\ncheck for ftp connectivity to $sftp_host"
	sftp -v $sftp_host <<TEST >ftp_results.$$
	pwd
	bye
TEST

ftptest=`grep -i -c -e "Remote working directory" ftp_results.$$`

	if [ $ftptest -lt 1 ]; then
echo -e "\nUNABLE TO OPEN SFTP SESSION TO $sftp_host\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	else
echo -e "\nconnection to $sftp_host confirmed, processing continues...\n"
rm ftp_results.$$
	fi


ftp_solar_out $ftp_local_host $basename

export solar_file=`ls -1 $basename*`
echo -e "\nprocessing outbound file $solar_file"

securezip $solar_file outbound

#replace record terminator crlf (wintel) with newline (unix)
crlf_rem $solar_file $crfile

echo -e "\nmake record length 300 for all records"
$HOME/bin/300.pl $crfile >$padded_file
	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact EPS"
	exit 4
	fi

echo -e "\nsftp data files to $sftp_host"
	sftp -v $sftp_host <<PUT >ftp_results.$$
	$chgdir
	put $padded_file $padded_file
	bye
PUT
rm ftp_results.$$
errorchk $? "ftp $padded_file sent to $sftp_host"

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

rm -fv $solar_file $tag_file $crfile $padded_file

archive_clean $outbound_archive $out_file $FileAge
}


case "$direction" in 

       data_accrual_ha_get)

export in_file=HUHAINANAIRPIT.txt
echo -e "\nBegin processing for accrual  in file"
inproc
echo -e "\nProcessing for Hainan Air  Accrual file in complete"
       ;;

         data_accrual_hbha2as_get)
echo -e "\nBegin processing for Hainan HB get file"
export basename=HUAS_Handback*
inproc_hb
echo -e "\nProcessing for as file from hainan get complete"
       ;;


       data_accrual_hbas2ha_put)
echo -e "\nBegin processing for Enrollment out file"
export basename=HUHAINANAIRPIT
export padded_file=ASRHU_$datestamp.txt
export chgdir="cd /Send"
outproc_hb
echo -e "\nProcessing for Hainan accr hb out complete"
       ;;

        data_accrual_as_put)
echo -e "\nBegin processing for Hainan Accrual out file"
export out_file=HUASOUTBOUND.txt
export tag_file=hainan.tag
export padded_file=ASAHU_$datestamp.txt
export chgdir="cd /Send"
outproc
echo -e "\nProcessing for  Hainan  accrual out file"

       ;;
esac


