#!/bin/bash
set -x
export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export lz=mpprod
export nofiledate=`/bin/date "+%A, %D"`
export local_file=ZTTHRIFTYCARRENTALPIT.txt
export data_file=thrifty.txt
export outfile_prefix=ZTTHRIFTYCARRENTALPIT
export datestamp=`/bin/date +%b%d%Y.%H%M`
export mail_to="FT_Partners@hertz.com"
FileAge=20

. /opt/local/ops_scripts/function_lib

function inbound {

cd $inbound_dir

ftp_check $ftp_local_host

#export data_file=`ls -1 $infile_prefix*.txt`
#records=`wc $data_file | awk '{print $2}'`

echo -e "\n$data_file file ($records records) received at `date`"

securezip $data_file inbound

echo -e "\nrename $data_file to $local_file"
mv -fv $data_file $local_file

ftp_solar_in $ftp_local_host $local_file

echo -e "\ncleaning up inbound directory"
rm -fv $local_file

archive_clean $inbound_archive $infile_prefix $FileAge

}

function outbound {

cd $outbound_dir

echo -e "remove files older than 30 days"
find . -mtime +30 | xargs rm -v

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix

export solar_file=`ls -1 $outfile_prefix*`

securezip $solar_file outbound

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nemail to Hertz that the handback file is ready"
Mail -s "Handback file for Thrifty is now on our server, please delete after picking up, $datestamp" $mail_to </dev/null


}

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_diners_file direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in)

echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"

        ;;

        out)

echo -e "\nBegin processing for `whoami` outbound processing"
outbound
archive_clean $outbound_archive $outfile_prefix $FileAge
echo -e "\nEnd of `whoami` outbound processing"

        ;;

esac
