#!/bin/bash

# Set the environment variables
export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export remote_file=MPHertz
export local_file=ZEHERTZCARRENTALPIT.txt
export outfile_prefix=ZEHERTZCARRENTALPIT
export handback_file=akhertz.txt
export FileAge=10
export rundate=`date "+%A, %B %d, %Y"`
export mail_to="FT_Partners@hertz.com"

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix

export solar_file=`ls -1 $outfile_prefix*`

securezip $solar_file outbound

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nprocessing outbound file $solar_file"

archive_clean $outbound_archive $outfile_prefix $FileAge

echo -e "\nclean up directory $outbound_dir"

echo -e "\nemail to Hertz that the handback file is ready"
Mail -s "Handback file is now on our server, please delete after picking up, $datestamp" $mail_to </dev/null
