#!/bin/bash

set -x

# Set up the iceland data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/iceland_environment"

export ftp_local_host=asprodftp
#export ftp_host=185.56.14.140
export sftp_host=as@file.icelandair.is
export lz=mpprod
export outfile_prefix=FIICELANDAIRPIT
export local_file=${outfile_prefix}.txt
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=eps@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export datestamp1=`/bin/date +%b%d%Y`
export errors_to="producton.servces@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

function inbound {

#Check connectivity to SEAVVFILE1
#ftp_check $ftp_local_host


echo -e "\nGet file from Iceland Air"
echo -e "\nget $datafile to $sftp_host"
	sftp -v -o port=50222 $sftp_host <<GETDATA >ftp_results.$$
        cd "Accural-out"
        dir
        mget $file_name 
	quit
GETDATA
	result=$?
	if [ $result -ne 0 ]; then
	echo "FTP get of $file_name to Iceland failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

mv $file_name $local_file

#Push iceland file to SEAVVFILE1
ftp_solar_in $ftp_local_host $local_file 

#SecureZip the Iceland Air file  prior to copying it to the archive dir.
securezip $local_file inbound

echo -e "\nDelete file from Iceland Air"
echo -e "\nDelete $datafile to $sftp_host"
	sftp -v -o port=50222 $sftp_host <<DELDATA >ftp_results.$$
        cd "Accural-out"
        dir
        rm $file_name 
	quit
DELDATA
result=$?
	if [ $result -ne 0 ]; then
	echo "FTP get of $file_name to Iceland failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

echo -e "\nclean up inbound directory"
rm -f $local_file

archive_clean $inbound_archive $local_file $FileAge

}

function outbound {

cd $outbound_dir

#ftp_check $ftp_host

echo -e "\nPut file to Iceland Air"
echo -e "\nget $datafile to $sftp_host"
	sftp -v -o port=50222 $sftp_host <<PUTDATA >ftp_results.$$
        cd "Flightdata/incoming"
        mput $file_name $file_name.$datestamp1
	quit
PUTDATA
	result=$?
	if [ $result -ne 0 ]; then
	echo "FTP put of $datafile to Iceland failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$


#ftp_vendor "$ftp_host" $file_name $file_name.$datestamp1 "cd Flightdata/incoming"

echo -e "\nfile was sent to iceland Air"
	
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP of iceland file failed, please investigate"
	cat $ftp_results.$$
	exit 8
	fi

securezip $file_name outbound

rm -f ftp_results.$ $file_name 

archive_clean $outbound_archive $file_name $FileAge

}
