#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
#export ftp_host=185.56.14.140
export sftp_host=as@file.icelandair.is

export partner=FI
export mail_partner=IcelandAir
export file_prefix=SSIM
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export maildom=alaskaair.com
#export mail_list="joanne.gies@$maildom"
export mail_list="ASQX.ScheduleDistribution@$maildom,joanne.gies@$maildom"
export sentdate=`/bin/date "+%Y%m%d"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7

export program=`basename $0`

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

echo -e "\nGet file from Iceland Air"
echo -e "\nget $datafile to $sftp_host"
	sftp -v -o port=50222 $sftp_host <<GETDATA >ftp_results.$$
        cd "SSIM-out"
        bin
        mget SSIM*.gz
	quit
GETDATA
	result=$?
	if [ $result -ne 0 ]; then
	echo "FTP put of $datafile to Iceland failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

export zip_file=`ls -1 SSIM*.gz`
echo -e "\nthis is the iceland ssim zipped file: $zip_file"

export data_file=`echo $zip_file | sed -e 's/.gz//'`

echo -e "\nThis is the unzipped file $data_file"

echo -e "\nunzip file $zip_file"
gzip -d $zip_file 

ftp_file $ftp_local_host $data_file SSIM_in.$sentdate.txt "cd $lzin_dir"

echo -e "\nDelete file from Iceland Air"
	sftp -v -o port=50222 $sftp_host <<DELDATA >ftp_results.$$
        cd "SSIM-out"
        delete $zip_file
        mget SSIM*.gz
	quit
DELDATA

echo "SSIM file $sim_file pulled from $partner to AS on $sentdate. The files can be found here: $lzin_dir" | Mail -s "$partner to AS SSIM file release" $mail_list

securezip $data_file inbound

rm -fv ftp_results* $data_file $zip_file

archive_clean $inbound_archive SSIM* $FileAge





