#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
#export ftp_host=185.56.14.140
export sftp_host=as@file.icelandair.is
export partner=FI
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export namebase=export namebase=fias
export maildom=alaskaair.com
#export mail_list="joanne.gies@$maildom"
export mail_list="ASQX.ScheduleDistribution@$maildom,FI.distribution@$maildom,joanne.gies@$maildom"
export sentdate=`/bin/date "+%Y%m%d_%H%M"`
export datestamp=`/bin/date "+%d%b%Y%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7

export program=`basename $0`

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\nftp get $namebase file from $ftp_local_host\n"
	ftp -v -i $ftp_local_host <<MGET >ftp_results.$$
	cd $lzout_dir
	dir
	mget ${namebase}*
	bye
MGET
	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP get of $namebase file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

export sim_file=`ls -1 ${namebase}*`

echo -e "\nzip file for Iceland SSIM"
export remote_file=${sim_file}.zip

zip $remote_file $sim_file

echo -e "\nThis is remote file to send to Iceland" $remote_file


securezip $sim_file outbound

echo -e "\nPut file to Iceland Air"
echo -e "\nput  $datafile to $sftp_host"
	sftp -v -o port=50222 $sftp_host <<PUTDATA >ftp_results.$$
        cd "SSIM-in"
        mput $remote_file
        dir
	quit
PUTDATA
	result=$?
	if [ $result -ne 0 ]; then
	echo "FTP put of $datafile to Iceland failed"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$



#ftp_vendor $ftp_host $remote_file $remote_file bin "cd SSIM-in"

ftp_file $ftp_local_host $sim_file ${sim_file}_$sentdate.txt "cd $lzout_archive"

ftp_delete $ftp_local_host $sim_file "cd $lzout_dir"

echo "SSIM file $sim_file for release $reldate was sent from AS to $partner on $maildate" | Mail -s "AS to $partner SSIM file" $mail_list

echo -e "\nDelete file $sim_file from $local_host"
	ftp -v -i $ftp_local_host <<DEL >ftp_results.$$
	cd $lzout_dir
	mdel ${namebase}*
	dir
	quit
DEL

	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP delete of file $sim_file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

echo "remove file $sim_file"
rm -fv $sim_file $remote_file

archive_clean $outbound_archive $namebase $FileAge
