#!/bin/bash

# Encrypt the data file to ftp to ID90
# This is a stand alone script

#export pgp_signature="alejandroID90T"   
#export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
#export sftp_host=as_updates@hr.id90travel.com
#export ftp_remote_host=apps.id90.com
export local_dir=EMPLOYEETRAVEL/ID90T
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export alert_recipient=dean.liebrich@alaskaair.com
export datestamp=`date +%Y%m%d`
export logfile=$HOME/transfer_log
export FileAge=30
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

function mainproc {

cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\nget $data_file from $ftp_local_host"
ftp_vendor_get $ftp_local_host $data_file $data_file "cd $local_dir"

securezip $data_file outbound

mv $data_file $date_file

archive_clean $outbound_archive $data_file $FileAge

echo -e "\nclean up temp files"

}

echo -e "\nBeginning ID90 data transfer for Alaska Air"

export data_file=AAG_ID90Emp.txt
export date_file=AAG_ID90Emp_$datestamp.txt
mainproc

export data_file=AAG_ID90Dep.txt
export date_file=AAG_ID90Dep_$datestamp.txt
mainproc

echo -e "\nID90 data transfer for Alaska Air complete"

