#!/bin/sh

# script to process Idine data
# 		

export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export data_file=ffcrtid
export local_file=IDMILEAGEPLANDINEPIT.txt
export ftp_local_host=asprodftp
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

ftp_check $ftp_local_host

echo -e "\ncheck for proper EOF record"
records=`wc -l $data_file | awk '{print $1}'`
correct_trailer=`tail -1 $data_file | grep -c '^9'`
	if [ "$correct_trailer" -ne 1 ]; then
	echo -e "\n${program}: I-Dine inbound data file trailer record missing."
	exit 8
	fi

echo -e "\nIdine Car Rental data file ($records records) received at `date`"

echo -e "\ncopy incoming file $data_file to $local_file"
cp -fv $data_file $local_file

ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nclean up $inbound_dir"
rm -fv $local_file $data_file

archive_clean $inbound_archive $local_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"

