#!/bin/sh

. $HOME/bin/iinet_environment

program=`basename $0`
cd $inbound_dir

cycle=$1

# Check for connectivity to the SEAVVFILE1 server.
ftp_check $ftp_win_host

#Depending on the parameter passed to the script, Monthly or Yearly, it will run the following.

case "$cycle" in

	MONTHLY)

for FILE in DOMWAC MGOWAC PASWAC TIDWAC
	do

export zipfile=${FILE}.ZIP

echo -e "\nFTP $zip_date_file to $ftp_win_host\n"
	iatan_in
echo -e "\nFTP $zip_date_file to $ftp_win_host complete"
	done

touch iinet.received.tag

ftp_file $ftp_win_host $tagfile_IATA $tagfile_IATA bin "cd SIS/TravelAgency/Inbound/IATAN"

rm -fv iinet.received.tag DOMWAC.ZIP MGOWAC.ZIP TIDWAC.ZIP
;;

	YEARLY)

for FILE in DOMWAM MGOWAM PASWAM TIDWAM
	do

export zipfile=${FILE}.ZIP

echo -e "\nFTP $zip_date_file to $ftp_win_host\n"
	iatan_in
echo -e "\nFTP $zip_date_file to $ftp_win_host complete"
	done

touch iinet_received.tag

ftp_file $ftp_win_host $tagfile_IATA $tagfile_IATA bin "cd SIS/TravelAgency/Inbound/IATAN"

rm -fv iinet_received.tag DOMWAM.ZIP MGOWAM.ZIP TIDWAM.ZIP

;;

	*)

echo -e "\n Missing or incorrect cycle parm, proper syntax 
	is: process_iatan_file CYCLE, where CYCLE equals MONTHLY or YEARLY\n"

	exit 4

esac
