#!/bin/bash
#stand alone script

set -x

export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export sftp_host=AAI890301JJ3_TCK@aspebi.sedeb2b.com
#export sftp1_host=alaska@ftp.sistemasmig.com.mx
export dom=alaskaair.com
export maillist="joanne.gies@$dom,fire.team.oncall.support@$dom"
#export maillist="dolores.saldana@$dom"
export datestamp=`date +%Y%m%d`
export logdate=`date +%Y%m%d.%H%M`
export FileAge=30

ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

echo -e "\ncheck for connectivity to $sftp_host"
        sftp -v -o port=9032 $sftp_host <<PUT >ftp_results.$$
	quit
PUT

export ftpcheck=`grep -ci "sftp\>" ftp_results.$$`

	if [ $ftpcheck -lt 1 ]; then
echo -e "\nConnection to $sftp_host failed, check for
connectivity and/or contact `whoami` to see why then rerun.\n"
cat ftp_results.$$
rm -fv ftp_results.$$
	exit 4
	fi

rm -fv ftp_results.$$

zip SalesInvoice.zip aero.txt cabfac.txt cargos.txt impfac.txt linfac.txt

echo -e "\nHere is where we put the file to EDICOM\n"
        sftp -v -o port=9032 $sftp_host <<PUT >ftp_results.$$
	cd out/ZIP_TXT_AAI890301JJ3_TCK/AAI890301JJ3_TCK_EDIWIN
	put SalesInvoice.zip SalesInvoice.zip.$datestamp
        dir
	quit
PUT
        result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of SalesInvoice file"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

securezip SalesInvoice.zip outbound

ls -1 *.txt |Mail -s "SalesInvoice daily file was sent to Edicom on $logdate" $maillist

rm -fv SalesInvoice.zip  

rm -fv aero.txt cabfac.txt cargos.txt impfac.txt linfac.txt

archive_clean $outbound_archive SalesInvoice* $FileAge
