#!/bin/sh

export PGPPASS=seavvdmzftp
export ftp_host=mvs
export ftp_win_host=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export tagfile=BSP.LOAD.COMPLETE.TAG
export tagfile_IATA=iinet.received.tag
export datestamp=`date +%m%d%y.%H%M`
export procdate=`date "+%A, %B %d, %Y."`
export info_to="michelle.nakaya@alaskaair.com"
export ops=/opt/local/ops_scripts
export FileAge=30
export FileAgeIATA=30

. /opt/local/ops_scripts/function_lib

function mainproc {

	if [ -f lockfile ]; then
	echo -e "\nlockfile detected in $inbound_dir, check for problems
	with previous BSP run(s).  Lockfile must be removed before restarting."
	echo -e "\ncontents of $inbound_dir:"
	ls -l
	exit 4
	fi

ftp_check $ftp_host

touch lockfile

size_check $zipname

echo -e "\nunzip file $zipname to $unzipfile"
unzip -a $zipname
	
	result=$?

#	if [ -s GB.HOT.P.*.027 ]; then
#	export unzipfile=`ls -1 GB.HOT.P.*.027`
#	fi

	if [ -e $unzipfilealt ]; then
        export unzipfile=$unzipfilealt
        fi

	if [ $result -ne 0 -o ! -f $unzipfile ]; then
	echo -e "\nunzip of file $filename failed"
	touch $tagfile
	rm lockfile
	exit 4
	fi

crlf_rem $unzipfile $filename

dsn_2mvs $ftp_host $filename $dsn

sleep 5

ftp_jcl $jcl $ftp_host

echo -e "\nmove $zipname to $inbound_archive/$zipname.$datestamp"
mv $zipname $inbound_archive/$zipname.$datestamp

echo -e "\ncleanup $inbound_dir"
rm -f $unzipfile $filename $unzipfilealt

rm lockfile
echo "The $country BSP file was processed on $procdate" | Mail -s "$country BSP" $info_to

archive_clean $inbound_archive $zipname $FileAge


}

function iatan_in {

size_check $zipfile

ftp_file $ftp_win_host $zipfile $zipfile bin "cd SIS/TravelAgency/Inbound/IATAN"

echo -e "\ncopy $zipfile to $inbound_archive/$zipfile.$datestamp"
cp $zipfile $inbound_archive/$zipfile.$datestamp

archive_clean $inbound_archive $zipfile $FileAgeIATA

}
