#!/bin/bash

export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export filedate=`/bin/date +%Y%m`
export datestamp=`/bin/date +%Y%m%d%H%M%S`
export ops=/opt/local/ops_scripts
export dom=alaskaair.com
export errors_to="dean.liebrich@$dom"
export mail_to="annette.chanez@$dom,paul.addis@$dom,dean.liebrich@$dom"
export FileAge=30

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\nGet file from $ftp_local_host"
        ftp -iv $ftp_local_host <<DATA >ftp_results.$$ 2>&1
	cd cargospot/iinet/outbound
	mget $prefix*
        quit
DATA

        result=$?

        if [ $result -ne 0 ]; then
        echo -e "\nFTP of get of data to $ftp_local_host failed\n"
        exit 8
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

export data_file=`ls -1 $prefix*`
export temp_file=$data_file.tmp
export crlf_file=$data_file.cr
export zip_file=`echo $data_file | sed -e 's/DAT/zip/'`

securezip $data_file outbound

echo -e "\nArchive and remove $data_file on $ftp_local_host"
        ftp -iv $ftp_local_host <<DATA >ftp_results.$$ 2>&1
	cd cargospot/iinet/outbound/archive
	put $data_file
	cd ..
	del $data_file
        quit
DATA

        result=$?

        if [ $result -ne 0 ]; then
        echo -e "\nFTP archive/clean of $data_file to $ftp_local_host failed\n"
        exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

set -x
mv -fv $data_file $temp_file
set +x

crlf_rem $temp_file $crlf_file

echo -e "\nmake record length 500 for all records"
$HOME/bin/500.pl $crlf_file > $data_file
	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact Systems Management"
	exit 4
	fi

zip $zip_file $data_file

echo -e "\nput $zip_file on iiNet server" 
sftp -v $sftp_host <<PUTDATA >ftp_results.$$
     	put $zip_file
        ls -l
       quit
PUTDATA

echo "CargoSpot file $data_file has been sent to iiNet" | Mail -s "iiNet FTP" $mail_to

cat ftp_results.$$
rm -fv ftp_results.$$

rm -fv $data_file $temp_file $crlf_file $zip_file

archive_clean $outbound_archive $prefix $FileAge

}

function inproc {

cd $inbound_dir

securezip *_VAL.ZIP inbound

unzip ${prefix}*_VAL.ZIP
	
	result=$?

	if [ $result -ne 0 ];then
echo -e "\nunzipping of inbound file failed"
	exit 4
	fi

rm -fv *PIDECF*.ZIP

	ls -1 *PIDECF*.*| while read File1
	do
echo -e "\nprocessing confirmation files $File1"

ftp_file $ftp_local_host $File1 $File1 "cd cargospot/iinet/inbound"

rm $File1

	done

archive_clean $inbound_archive $prefix $FileAge

}

export typedir=$1

	if [ -z $typedir ]; then
echo -e "\n	Missing typedir parm,
	proper syntax is process_iinet_idec typedir
	where direction=in or out. i.e.
	process_iinet_cgsis_data out\n"
	exit 4
	fi	

case "$typedir" in

	in_sb)
prefix=ST-PIDECF
export ftp_local_host=testftp
export sftp_host=SANDSFTP@144.194.18.35
echo -e "\nBegin processing for inbound conf idec file"
inproc
echo -e "\nInbound processing complete for inbound conf idec file"
;;

	in_cert)
prefix=???
export ftp_local_host=testftp
export sftp_host=SANDSFTP@144.194.18.35
echo -e "\nBegin processing for inbound conf idec file"
inproc
echo -e "\nInbound processing complete for inbound conf idec file"
;;

	in)
prefix=PIDECF
export ftp_local_host=asprodftp
export sftp_host=ALSISFTP@144.194.18.35
echo -e "\nBegin processing for inbound conf idec file"
inproc
echo -e "\nInbound processing complete for inbound conf idec file"
;;

	out_sb)
export prefix=ST-CIDECF-027
export sftp_host=SANDSFTP@144.194.18.35
echo -e "\nBegin processing for outbound iinet_idec_file"
outproc
echo -e "\nOutbound processing complete for iinet IDEC file"
;;

	out_cert)
export prefix=CIDECF
export sftp_host=SANDSFTP@144.194.18.35
echo -e "\nBegin processing for outbound iinet_idec_file"
outproc
echo -e "\nOutbound processing complete for iinet IDEC file"
;;

	out)
export prefix=PIDECF
export sftp_host=ALSISFTP@144.194.18.35
echo -e "\nBegin processing for outbound iinet_idec_file"
outproc
echo -e "\nOutbound processing complete for iinet IDEC file"
;;

esac
