#!/bin/sh

. $HOME/bin/iinet_environment

program=`basename $0`
cd $inbound_dir

	if [ ! -f $tagfile ]; then
	echo -e "\ntag file not found, make sure there are no mainframe
RABSP jobs running then attempt a rerun\n"
	exit 4
	fi 

rm -v $tagfile

export filename=$1
export zipname=`ls -1 ${filename}*.zip`

#make sure filename parm was passed in as first arg
	if [ -z $filename ]; then
echo -e "\n	Missing filename parm. 
	proper syntax is: process_bsp_file filename where
	filename equals valid bsp filename (i.e. AUAS)\n"
	exit 4
	fi

case "$filename" in
	AUAS) 
	export dsn="'RA.RABSPSYD.DISKDATA'"
	export jcl=$HOME/bin/rabspsyd.jcl
	export unzipfile=HOTBTHB.027
	export unzipfilealt=XXX
	export country=Australia
	;;

	NZAS) 
	export dsn="'RA.RABSPAKL.DISKDATA'"
	export jcl=$HOME/bin/rabspakl.jcl
	export unzipfile=HOTBTHB.027
	export unzipfilealt=XXX
	export country=New Zealand
        ;;

	ASMX)
	export dsn="'RA.RABSPMEX.DISKDATA'"
	export jcl=$HOME/bin/rabspmex.jcl
	export country=Mexico
	export unzipfile=`echo $zipname | sed -e s/zip/027/`
	export unzipfilealt=`echo $zipname | sed -e s/.zip//`
	;;

	CAAS)
	export dsn="'RA.RABSPCAN.DISKDATA'"
	export jcl=$HOME/bin/rabspcan.jcl
	export unzipfile=HOTBTHB.027
	export unzipfilealt=XXX
	export country=Canada
	;;

        peras01)
	export dsn="'RA.RABSPFRA.DISKDATA'"
        export jcl=$HOME/bin/rabspfra.jcl
	export unzipfile=XAS01027
	export unzipfilealt=XXX
	export country=Germany
        ;;

        asuk)
	export dsn="'RA.RABSPUK.DISKDATA'"
        export jcl=$HOME/bin/rabspuk.jcl
	export unzipfile=`echo $zipname | sed -e s/.zip//`
	export unzipfilealt=XXX
	export country=UK
        ;;

        costarica)
	export dsn="'RA.RABSPUK.DISKDATA'"
        export jcl=$HOME/bin/rabspuk.jcl
	export unzipfile=`echo $zipname | sed -e s/.zip//`
	export unzipfilealt=XXX
	export country=CostaRica
        ;;
	
esac

echo -e "\nBegin processing $country BSP file"
	mainproc
echo -e "\nEnd of $country BSP file processing"
