#!/bin/bash

export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=joanne.gies@alaskaair.com
export filedate=`/bin/date +%Y%m`
export datestamp=`/bin/date +%Y%m%d%H%M%S`
export ops=/opt/local/ops_scripts
export errors_to="dean.liebrich@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

export idec_base_file=${prefix}PIDECF-027
export idec_century=20
export idec_yr=`head -2 $idec_base_file | tail -1 | cut -c47-48`
export idec_month=`head -2 $idec_base_file | tail -1 | cut -c49-50`
export idec_crlf_file=${idec_base_file}$idec_century$idec_yr$idec_month
export idec_period=`head -2 $idec_base_file | tail -1 | cut -c70-71`
export idec_padded_file=${idec_crlf_file}${idec_period}$datestamp
export idec_zipped_file=${idec_padded_file}.zip
export idec_dat_file=${idec_padded_file}.dat

#replace record terminator crlf (wintel) with newline (unix)
crlf_rem $idec_base_file $idec_crlf_file

echo -e "\nmake record length 500 for all records"
$HOME/bin/500.pl $idec_crlf_file > $idec_dat_file
	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact Systems Management"
	exit 4
	fi

echo $idec_crlf_file "idec_crlf_file"
echo $idec_century "idec_century"
echo $idec_yr "idec_yr"
echo $idec_month "idec_month"
echo $idec_period "idec_period"
echo $idec_padded_file "idec_padded_file"
echo $idec_zipped_file "idec_zipped_file"
echo $idec_dat_file "idec_dat_file"

zip $idec_zipped_file $idec_dat_file

securezip $idec_dat_file outbound

echo -e "\nput $file_name on iiNet server" 
sftp -v $sftp_host <<PUTDATA >ftp_results.$$
     	put $idec_zipped_file
        ls -l
       quit
PUTDATA

cat ftp_results.$$
rm -fv ftp_results.$$

archive_clean $outbound_archive $idec_dat_file $FileAge

rm -fv $idec_dat_file $idec_zipped_file $idec_crlf_file $idec_padded_file $idec_base_file

#echo -e "\nemail to iiNet that the IDEC file has been sent"
#Mail -s "Zipped IDEC has been sent to your server" $mail_to </dev/null

}

function inproc {

cd $inbound_dir

securezip *_VAL.ZIP inbound

unzip ${prefix}*_VAL.ZIP
	
	result=$?

	if [ $result -ne 0 ];then
echo -e "\nunzipping of inbound file failed"
	exit 4
	fi

rm -fv *PIDECF*.ZIP

	ls -1 *PIDECF*.*| while read File1
	do
echo -e "\nprocessing confirmation files $File1"

ftp_file $ftp_local_host $File1 $File1 "cd Rev_acctg/iinet"

rm $File1
	done

archive_clean $inbound_archive $prefix $FileAge

}

