#!/bin/bash

# Process Infare data for PSMC Team.

# Set the environment variables
. $HOME/bin/infare_environment

export filetype=$1

	if [ -z $filetype ]; then
echo -e "\n	Missing filetype parm.
	proper syntax is: process_infare_data filetype
	where filetype equals asin or infarein\n"
	exit 4
	fi

case "$filetype" in

	infarein)

export filepref=INFAREAS
infareproc
archive_clean $inbound_archive $filepref $FileAge
       ;;

	asin)

export filepref=AS_
asproc
archive_clean $inbound_archive $filepref $FileAge
	;;

*)

echo -e "\nargument is missing or invalid, 
need to pass one of the following arguments:
infarein, asin"

exit 4
	;;

esac
