#!/bin/bash

# Set up the iSeatz data transfer environment

export ftp_local_host=asprodftp
export sftp_host=alaska-sftp@cms.iseatz.com
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=production.services@alaskaair.com
export datestamp=`/bin/date +%y%m%d`
export local_file=SSHOTELORBITZPIT.txt
export info_to="joanne.gies@alaskaair.com"
export errors_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export last_file_received=$HOME/last_file_received
export nofiledate=`/bin/date "+%A, %D"`
FileAge=20

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

echo -e "\nget file on iseatz server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd "pickup"
       	mget wl_mileage_earned*.txt
        quit
GETDATA

cat ftp_results.$$
rm -f ftp_results.$$

export rem_file=`ls -1 wl_mileage_earned*.txt`
echo -e "\nthis is the iseatz: $rem_file"

# rename local file for SOLAR conv (see if we can get Vendor to put file as Solar name)
cp $rem_file $local_file

securezip $local_file inbound

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

echo -e "\nrename file on iseatz server" 
	sftp -v $sftp_host <<RENMDATA >ftp_results.$$ 2>&1
        cd pickup
       	rename $rem_file $rem_file.done
        quit
RENMDATA

echo -e "\ncleaning up inbound directory"
rm -f $local_file $rem_file

archive_clean $inbound_archive $local_file $FileAge


ftp_delete $ftp_host $rem_old_file "cd out"
ftp_rename $ftp_host $rem_file $rem_old_file

archive_clean $inbound_archive $data_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"


