#!/bin/bash

. $HOME/bin/korean_environment
program=`basename $0`

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

ftp_check "$ftp_host"
ftp_check $ftp_local_host

cd $outbound_dir

#get the file
echo -e "\nget $kebill_file from asprodftp" 
	ftp -v $ftp_local_host <<GETDATA >ftp_results.$$
	cd "mpprod\Outbound"
	get $kebill_file
	bye
GETDATA

	result=$?
	
	if [ $result -ne 0 ]; then
	echo "ftp get of $kebill_file failed"
	cat ftp_results.$$
	exit 4 
	fi

rm -f ftp_results.$$

securezip $kebill_file outbound

#  zip file
echo -e "\zip file for Korean"

zip FFBILLASKE.zip $kebill_file

# ftp data files to Korean
ftp_vendor $ftp_host FFBILLASKE.zip FFBILLASKE.zip bin "cd assky"

echo -e "\cleanup $kebill_file from asprodftp" 
	ftp -v asprodftp <<GETDATA >ftp_results.$$
	cd "mpprod\Outbound"
	delete $kebill_file
	bye
GETDATA

rm -f ftp_results.$$ $kebill_file korean.tag FFBILLASKE.zip

archive_clean $outbound_archive $kebill_file $FileAge
