#!/bin/bash

set -x
# Set up the korean data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/korean_environment"

export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
export sftp_host="assky1@210.105.11.216"
export lz=mpprod
export solar_file=KEKOREANPIT.txt
export kebill_file=KEBilling.txt
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=eps@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="producton.servces@alaskaair.com"
export FileAge=80

. /opt/local/ops_scripts/function_lib

function inbound {

cd $inbound_dir

export zip_file=`ls -1 $file_prefix*.zip`
echo -e "\nthis is the Korean zipped file : $zip_file"
export data_file=`echo $zip_file | sed -e 's/zip/txt/'`

echo -e "\nunzip file $zip_file"
unzip $zip_file $data_file

echo -e "Data file is $data_file"

echo -e "\nrename $data_file to $solar_file"
mv -v $data_file $solar_file

ftp_solar_in $ftp_local_host $solar_file

securezip $solar_file inbound

echo -e "\nclean up inbound directory"
rm -fv ftp_results.$$ $solar_file $data_file $zip_file

archive_clean $inbound_archive $file_prefix $FileAge

}

function outbound {

cd $outbound_dir


echo -e "\nzip file for Korean"
zip FFPASKE.zip $file_name

securezip $file_name outbound


cd $outbound_dir

echo -e "\nput  $file_name on Korean server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        put FFPASKE.zip 
        quit
GETDATA
cat ftp_results.$$
rm -fv ftp_results.$$

securezip $file_name outbound


rm -f ftp_results.$$ $data_file korean.tag FFPASKE.zip $file_name

archive_clean $outbound_archive $file_name $FileAge

}
