#!/bin/bash


set -x
# Set up the korean data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/korean_environment"

export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
export ftp_host="210.105.11.216 5002"
export lz=mpprod
export solar_file=KEKOREANPIT.txt
export kebill_file=KEBilling.txt
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=eps@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="producton.servces@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

function inbound {

cd $inbound_dir


export zip_file=`ls -1 FFPKEAS*.zip`
echo -e "\nthis is the Korean zipped file : $zip_file"
export data_file=`echo $zip_file | sed -e 's/zip/txt/'`

echo -e "\nunzip file $zip_file"
unzip $zip_file $data_file

unix2dos $data_file

echo -e Data file is $data_file

echo -e "\nrename $data_file to $solar_file"
mv -v $data_file $solar_file

ftp_solar_in $ftp_local_host $solar_file

securezip $solar_file inbound


echo -e "\nclean up inbound directory"
rm -fv ftp_results.$$ $solar_file $data_file $zip_file

archive_clean $inbound_archive $file_prefix $FileAge

}

function outbound {

cd $outbound_dir

ftp_check $ftp_local_host
ftp_check "$ftp_host"

echo -e "\nzip file for Korean"
zip FFPASKE.zip $file_name

ftp_vendor "$ftp_host" FFPASKE.zip FFPASKE.zip bin "cd assky"

echo -e "\nfile was sent to Korean Air"
	
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP of Korean file failed, please investigate"
	cat $ftp_results.$$
	exit 8
	fi

securezip $file_name outbound

rm -f ftp_results.$$ $data_file korean.tag FFPASKE.zip $file_name

archive_clean $outbound_archive $file_name $FileAge

}
