#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export partner=KE
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export maildom=alaskaair.com
#export maillist="KE.Distribution@$maildom,ASQX.ScheduleDistribution@$maildom,rsvn@koreanair.com"
export maillist="ASQX.ScheduleDistribution@$maildom,rsvn@koreanair.com"
export sentdate=`/bin/date "+%Y%m%d_%H%M"`
export datestamp=`/bin/date "+%j%y-%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7

. /opt/local/ops_scripts/function_lib

function getfile {
cd $outbound_dir

echo -e "\nftp get $namebase file from $ftp_local_host\n"
	ftp -v -i $ftp_local_host <<MGET >ftp_results.$$
	$ftparg
	cd $lzout_dir
	dir
	mget $namebase
	bye
MGET
	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP get of $namebase file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$
}

function txtfile {

ls -1 $namebase | while read FILE1
	do

export arch_name=`echo $FILE1 | sed -e 's/$ext//'` 

echo $arch_name  This is arch_name

securezip $FILE1 outbound

ftp_file $ftp_local_host $FILE1 ${arch_name}_$sentdate.$ext "cd $lzout_archive" $ftparg

ftp_delete $ftp_local_host $FILE1 "cd $lzout_dir"

	done

}


function chkname {
set -x
export namechk=`ls -1 $namebase | wc| awk '{print $2}'`

	if [ $namechk -gt 1 ]; then
export newname=`ls -1 $namebase | sed -e 's/ /_/g'`
	else
export newname=`ls -1 $namebase`
	fi

mv -fv $namebase $newname

}

function email {

cd $outbound_dir

file1=`ls -1 | head -1`
file2=`ls -1 | head -2 | tail -1`
file3=`ls -1 | tail -1`

echo "send mail to $maillist with `ls` files attached"
echo -e "$maildate

The following attached files were emailed from AS to $partner.

`ls -1`" | mutt -s "email from AS to $partner $maildate complete" -a "$file1" $maillist

echo "remove files `ls`"
rm -fv `ls`

archive_clean $outbound_archive $basename $FileAge

}

ftp_check $ftp_local_host

#sleep 60
export namebase=keas*.txt
export ftparg=ascii
export ext=.txt
getfile
txtfile
email
