#!/bin/bash

# Set up the lanchile data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/lanchile_environment"

export ftp_local_host=asprodftp
export sftp_host=alaska@200.14.104.191
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=production.services@alaskaair.com
export datestamp=`/bin/date +%y%m%d`
export file_name=ASLACF
export local_file=LALANCHILEAIRLINESPIT.TXT
export info_to="joanne.gies@alaskaair.com"
export errors_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export last_file_received=$HOME/last_file_received
export MAILLST="ftp.partner.alerts@alaskaair.com"
#export mail_to="xxxxxx"
export nofiledate=`/bin/date "+%A, %D"`
FileAge=20

. /opt/local/ops_scripts/function_lib

function inbound {

cd $inbound_dir

echo -e "\nget file on Lan Chile server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd "Out"
       	mget LAASCF*.OK
        quit
GETDATA

cat ftp_results.$$
rm -f ftp_results.$$

export rem_file=`ls -1 LAASCF*.OK`
echo -e "\nthis is the LanChile: $rem_file"

# rename local file for SOLAR conv (see if we can get Vendor to put file as Solar name)
cp $rem_file $local_file

securezip $local_file inbound

echo -e "\nrename file on Lan Chile server" 
	sftp -v $sftp_host <<RENMDATA >ftp_results.$$ 2>&1
        cd "Out"
       	rename $rem_file $rem_file.done
        quit
RENMDATA

	result=$?

	if [ $result -ne 0 ]; then
echo -e "\nrename of file $rem_file on $sftp_host failed"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

#rm -fv ftp_results.$$

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

echo -e "\ncleaning up inbound directory"
rm -f $local_file $rem_file

archive_clean $inbound_archive $local_file $FileAge

}

function outbound {

cd $outbound_dir

echo -e "\nput  $file_name on Lan Chile server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd "In"
       	put $file_name $file_name.$datestamp.txt
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$

securezip $file_name outbound

rm -f $file_name 

archive_clean $outbound_archive $file_name $FileAge

}
