#!/bin/bash

# Set up the Marriott data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/marriott_environment"

export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export local_file=MCMARRIOTTHOTELSPIT.txt
export FileAge=45

. /opt/local/ops_scripts/function_lib

function inproc {

cd $inbound_dir

#Check connectivity to SEAVVFILE.
ftp_check $ftp_local_host

#Push Marriott file to SEAVVFILE1
ftp_solar_in $ftp_local_host $local_file

#SecureZip the Marriott prior to copying it to the archive dir.
securezip $local_file inbound

rm -f $local_file

archive_clean $inbound_archive $local_file $FileAge

}
