#!/bin/bash

# Encrypt the matrix data file and push to matrix
# for processing

program=`basename $0`

. $HOME/bin/matrix_environment

export airline=$1

	case "$airline" in

as)
	export datafile=${basename}.txt
	export outfile_pref=Alaska
        export dir=/home/hrdata/ftp-clients/1356
	export outfile=${outfile_pref}_$datestamp
        export pgpfile=${outfile}.pgp
        export sftp_host=aalftp@ftp.matrixcos.com
	export hcmdir=/home/hcmprod/outbound/matrix
	export tagfile=$hcmdir/${basename}.tag

echo -e "\nbegin processing for AS file $datafile"
mainproc
echo -e "\nMatrix Service Plan data transfer for Alaska Air complete"

	;;

qx)
	export datafile=${basename}.txt
	export outfile_pref=Horizon
	export outfile=${outfile_pref}_$datestamp
        export pgpfile=${outfile}.pgp
        export dir=/home/hrdata/ftp-clients/2031
        export sftp_host=horizon@ftp.matrixcos.com
      	export hcmdir=/home/hcmprod/outbound/qxmatrix
      	export tagfile=$hcmdir/${basename}.tag

echo -e "\nbegin processing for QX file $datafile"
mainproc
echo -e "\nMatrix Service Plan data transfer for Horizon Air complete"

	;;

*)

echo -e "\nargument is missing or invalid, 
need to pass airline argument of qx or as\n"

exit 4

	;;

esac
