#!/bin/bash


set -x

# Set up the Motznik data transfer
# This is a stand alone script

export PGPPASS=seavvdmzftp
export ftp_local_host=asprodftp
export lz=mpprod
export remote_file=motznik-alaska-residents.zip
export local_file=motznik-alaska-residents.txt
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=eps@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="joanne.gies@alaskaair.com"
export MAILLIST="mlr.oncall.support@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

	if [ ! -f $remote_file ] ; then
	MSG="No monthly file from Motznik to process. This needs to be investigated. Contact MLR on-call"
	echo -e "\n$MSG" | Mail -s "Motznik file is not here-" $MAILLIST
	dir
	exit 4
	fi

echo "unzip file"
unzip $remote_file 

ftp_check "$ftp_local_host"
ftp_file $ftp_local_host $local_file $local_file "cd $lz/Motznik"

securezip $local_file inbound

echo -e "\nclean up inbound directory"
rm -f ftp_results.$$ $local_file $remote_file

archive_clean $inbound_archive $local_file $FileAge




