#!/bin/sh

# script to process National Rental Car data
export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export data_file=ALASKA.AIR.DAT
export local_file=ZLNATIONALCARRENTALPIT.txt
export export datestamp=`date +%m%d%y.%H%M`
export FileAge=14

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

	if [ ! -f $data_file ]; then
	echo -e "\nNO INCOMING FILE ($data_file) TO PROCESS\n"
	exit 4
	fi

records=`wc -l $data_file | awk '{print $1}'`
	
	if [ $records -eq 0 ]; then
	echo "incoming `whoami` data file ($data_file) is empty"
	exit 4
	fi

ftp_check $ftp_local_host

echo -e "\n`whoami` file ($records records) received at `date`"

mv -v $data_file $local_file

ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nclean up $inbound_dir"
rm -fv $local_file

archive_clean $inbound_archive $local_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"
