#!/bin/bash

set -x
#this is a stand alone script

export BATCHMODE=yes          # Turn on non-prompted PGP encrypting
export sftp_host=alaskaair@filetransfer.NavexGlobal.com
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export hcmdir_out=/home/hcmprod/outbound/navex
export datestamp=`/bin/date +%m%d%Y%H%M%S`
export date=`/bin/date  +%Y%m%d`
export out_file=aagnavex.csv
export tag_file=aagnavex.tag
export alert_recipient=joanne.gies@alaskaair.com
export info_to="joanne.gies@alaskaair.com"
export errors_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

cd $hcmdir_out

echo -e "\nprocessing $whoami $out_file"

echo -e "\ncopy file from $hcmdir_out to $outbound_dir"
cp $hcmdir_out/$out_file $outbound_dir

cd $outbound_dir

securezip $out_file outbound

echo -e "\nput $out_file to $sftp_host"
	sftp -v $sftp_host <<PUTDATA >ftp_results.$$
	put $out_file alaskaairlines_$date.csv
        dir
	bye
PUTDATA
	
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $out_file to navex failed, contact SysOps"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

echo -e "\nRemove archived files older than $FileAge days"
find $outbound_archive/* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

data_records=`wc -l $out_file | awk '{print $1}'`
echo -e "\n$datestamp: there were $data_records records sent to Navex" 

echo -e "\nRemove temp files"
rm -fv $out_file $hcmdir_out/$out_file
rm -fv $hcmdir_out/$tag_file 

