#!/bin/bash

# Encrypt the outbound Northwes handback file & FTP to Northwest.
# Set the environment variables
. $HOME/bin/norwest_environment
program=`basename $0`

cd $outbound_dir

echo -e "\nencrypt file $paxrecs_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor --sign -r $pgp_remote_signature --output $paxrecs_gpg_file --encrypt $paxrecs_file

	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\npaxrecs_file encryption failure, assign ticket to Prod. Svcs.\n"
	exit 8
	fi


ftp_vendor $ftp_host $paxrecs_gpg_file $paxrecs_gpg_file bin

securezip $paxrecs_file outbound

archive_clean $outbound_archive $paxrecs_file $FileAge

count=`wc -l $paxrecs_file | awk '{print $1}'`
echo "$count records were sent to Northwest Air"

echo -e "\nremove temp files"
rm -f $paxrecs_file $paxrecs_gpg_file $tagfile 
