#!/bin/sh

# Set up the Northwest (norwest) data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/norwwest_solar_environment"

export pgp_remote_signature="n37alais"
export BATCHMODE=yes          # Turn on non-prompted PGP encrypting
export ftp_host=ftp.nwa.com
export ftp_local_host=asprodftp
export lz=mpprod
export PGPPASS=seavvdmzftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=production.services@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export data_file=activ88
export local_pgp_file=${data_file}.gpg
export local_file=NWNORTHWESTAIRPIT.txt
#export outfile_prefix=NWNORTHWESTAIRPIT
export info_to="production.services@alaskaair.com"
export errors_to="production.services@alaskaair.com"
export FileAge=30
export rundate=`date "+%A, %B %d, %Y"`
#export MAILLIST="ftp.partner.alerts@alaskaair.com"
export MAILLIST="joanne.gies@alaskaair.com"

. /opt/local/ops_scripts/function_lib

