#!/bin/bash

export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export ftp_local_host=asprodftp
export ftp_host=ftp.oag.com
export partner=OAG
export lzout_dir=scheduling/PartnerSSIM/$partner/outbound
export lzout_archive=scheduling/PartnerSSIM/$partner/outbound.archive
export lzin_dir=scheduling/PartnerSSIM/$partner/inbound
export lzin_archive=scheduling/PartnerSSIM/$partner/inbound.archive
export namebase=ASoag
export outfile=SSIMAS.TXT
export notify="ASQX.ScheduleDistribution@alaskaair.com"
export sentdate=`/bin/date "+%Y%m%d_%H%M"`
export maildate=`/bin/date "+%Y%m%d %H:%M"`
export FileAge=7
export datestamp=`/bin/date +%b%d%Y`
export program=`basename $0`

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

ftp_check $ftp_local_host
ftp_check $ftp_host

sleep 30

echo -e "\nftp get $namebase* file from $ftp_local_host\n"
	ftp -v -i $ftp_local_host <<MGET >ftp_results.$$
	cd $lzout_dir
	dir
	mget $namebase*
	bye
MGET
	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP get of ${namebase}* file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

#remove spaces in file name if needed
namechk=`ls -1 ${namebase}* | wc | awk '{print $2}'`

	if [ $namechk -gt 1 ]; then
echo -e "\nrename ${namebase}* to `ls -1 ${namebase}* | sed -e 's/ /_/g'`"
mv -v ${namebase}* `ls -1 ${namebase}* | sed -e 's/ /_/g'`
	fi

sim_file=`ls -1 ${namebase}*`
arch_pref=`echo $sim_file | sed -e 's/.txt//'`

securezip $sim_file outbound

ftp_vendor_put $ftp_host $sim_file $outfile

cat ftplog.tmp
#ftp_chk=`grep -c 226 ftplog.tmp`

#	if [ $ftp_chk -ne 2 ]; then
#echo -e "\nFTP of file $sim_file to $ftp_host failed, please investigate"
#echo "There was a problem with the FTP of the outbound SSIM file for `whoami`" | Mail -s "`whoami` SSIM ftp" $notify
#rm -fv ftplog.tmp
#	exit 4
#	fi

ftp_file $ftp_local_host $sim_file ${arch_pref}_${sentdate}.txt "cd $lzout_archive"

echo -e "\nDelete file $sim_file from $local_host"
	ftp -v -i $ftp_local_host <<DATA >ftp_results.$$
	cd $lzout_dir
	mdel ${namebase}*
	dir
	quit
DATA

	result=$?

	if [ $result -ne 0 ];then
	echo "\nFTP delete of file $sim_file failed,
	please investigate\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

echo -e "\nclean up outbound directory"
rm -fv $sim_file ftplog.tmp

archive_clean $outbound_archive $namebase $FileAge

echo -e "$maildate

The following files were successfully sent from AS to $partner via FTP.

$sim_file" | Mail -s "AS to $partner $maildate complete" $notify
