#!/bin/bash

set -x

# Set up the stand alone omega air script
# Goes out and picks files up from seavvfile1, moves to seavvftp, sends to Omega archives on seavvfile1

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export ftp_host=ftp.alaska.omegaair.com
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export filedir=MANDE/TraxAmes/PROD
export filedira=MANDE/TraxAmes/Archive
export datestamp=`/bin/date +%Y%m%d`
export info_to="production.services@alaskaair.com"
#export mail_to="jeff.peerson@alaskaair.com"
export mail_to="joanne.gies@alaskaair.com"
export nofiledate=`/bin/date "+%A, %D"`
FileAge=30

. /opt/local/ops_scripts/function_lib

cd $outbound_dir


echo -e "\nget file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd $filedir
	dir
        mget *.txt
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$

echo -e "\nprocessing aerdata files"

	ls -1 | while read File1
	do
securezip $File1 outbound


echo -e "\nput $data_file to $ftp_host"
	ftp -i -v $ftp_host <<PUTDATA >ftp_results.$$
        cd Feeds
        mput *.txt
	bye
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $File1 to Omega failed, contact Systems Management"
	cat ftp_results.$$
#	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
#rm -f ftp_results.$$


echo -e "\nArchive file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "$filedira"
        put $File1 $File1.$datestamp.txt
        cd ..
        cd PROD
        pwd
        dir
        del $File1
GETDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "Archive of file $File1 on $ftp_local_host failed" | Mail -s "$program failure" $mail_to
	cat ftp_results.$$
	rm ftp_results.$$
	fi

cat ftp_results.$$
rm ftp_results.$$

rm -fv $File1 

	done

archive_clean $outbound_archive *.zip $FileAge


