#!/bin/bash

set -x
#this is a stand alone script

export BATCHMODE=yes          # Turn on non-prompted PGP encrypting
export sftp_host=alaskaair@clm-integration.selectica.com
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export findir_out=/home/finprod/outbound/po_clm
export datestamp=`/bin/date +%m%d%Y%H%M%S`
export out_file=agpo_clm_vndr.csv
export tag_file=agpo_clm_vndr.tag
export alert_recipient=joanne.gies@alaskaair.com
export info_to="joanne.gies@alaskaair.com"
export errors_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

cd $findir_out

echo -e "\nprocessing $whoami $out_file"

echo -e "\ncopy file from $findir_out to $outbound_dir"
cp $findir_out/$out_file $outbound_dir

cd $outbound_dir

securezip $out_file outbound

echo -e "\nput $out_file to $sftp_host"
	sftp -v -o port=10022 $sftp_host <<PUTDATA >ftp_results.$$
        cd incoming/alaskaair/prod
	bin
	put $out_file $out_file
        dir
	bye
PUTDATA
	
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $out_file to po_clm failed, contact SysOps"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
#rm -f ftp_results.$$

echo -e "\nRemove archived files older than $FileAge days"
find $outbound_archive/* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

data_records=`wc -l $out_file | awk '{print $1}'`
echo -e "\n$datestamp: there were $data_records records sent to Determine" 

echo -e "\nRemove temp files"
rm -fv $out_file $findir_out/$out_file
rm -fv $findir_out/$tag_file 

