#!/bin/bash

# Set up the Hip Cricket data transfer environment
# This script is used by other scripts to preset values from a common source.

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export info_to="production.services@alaskaair.com"
export mail_to="joanne.gies@alaskaair.com"
export nofiledate=`/bin/date "+%A, %D"`
FileAge=30

. /opt/local/ops_scripts/function_lib

function inbound {

cd $inbound_dir

	ls -1 Hip*.csv | while read File1
	do

echo -e "\nprocessing Hip Cricket $File1"

securezip $File1 inbound

ftp_file $ftp_local_host $File1 $File1 "cd mpprod/LoadliteContact/Inbound"

echo -e "\nArchive file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "mpprod/LoadliteContact/Inbound/Archive"
        put $File1
        quit
GETDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo "Archive of file $File1 on $ftp_local_host failed" | Mail -s "$program failure" $mail_to
	cat ftp_results.$$
	rm ftp_results.$$
	fi

cat ftp_results.$$
rm ftp_results.$$

rm -fv $File1 

	done

archive_clean $inbound_archive HipCricket*.csv $FileAge

}


function outbound {

cd $outbound_dir

rm -fv HipCricket_COMPLETE.tag

echo -e "\nget file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "mpprod/outbound/Hipcricket"
	dir
      	mget Hip*
        quit
GETDATA

cat ftp_results.$$
rm -f ftp_results.$$

	ls -1 Hip* | while read File1
	do

echo -e "\nprocessing HipCricket file $File1"

securezip $File1 outbound

echo -e "\nArchive file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "mpprod/outbound/Hipcricket/Archive"
        put $File1
        cd ..
        delete $File1 HipCricket_COMPLETE.tag
        quit
GETDATA

	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\narchive of file $File1 on $ftp_local_host failed.\n"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -fv ftp_results.$$

	done


#echo -e "\nemail to someone/Joanne for now- that files have been put on the sever"
#Mail -s "Encrypted file(s) are now on your server " $mail_to </dev/null


archive_clean $inbound_archive HipCricket*.csv $FileAge

}
