#!/bin/bash

. $HOME/bin/premera_environment

program=`basename $0`

export direction=$1

	if [ -z $direction ]; then
echo -e "\n	Missing direction parm.
	proper syntax is: process_`whoami`_data direction
	where direction equals IN or OUT\n"
	exit 4
	fi

case "$direction" in

	IN)

base=??????
data_file=${base}.TXT
tagfile=$hcmin_dir/${base}.tag
pgp_data_file=${data_file}.pgp

echo -e "\nbegin processing for `whoami` $localfile"		
inproc 
echo -e "\nend processing for `whoami` $localfile"

	;;

	OUT)

base=AGBN0008
data_file=${base}.txt
pgp_data_file=${data_file}.pgp
tagfile=$hcmout_dir/${base}.tag

echo -e "\nBegin processing Premera outbound processing"
encrypt
echo -e "\nEnd Premera outbound file processing"

	;;

esac

