#!/bin/bash

export PGPPASS=seavvdmzftp
export pgp_rem_sig=49C022E5
#export pgp_rem_sig="QANTAS Airways (Alaskan) Frequent Flyer Data Interfaces Key"
export ftp_host=139.163.83.60
export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%Y%m%d`
export nofiledate=`/bin/date "+%A, %D"`
export local_file=QFQANTASAIRWAYSPIT.txt
export QANTAS_MAILLIST="loyaltyoperation@qantas.com.au,loyaltysupport@qantas.com.au"
export FileAge=20
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

export direction=$1

function outproc {

cd $outbound_dir

ftp_check $ftp_local_host
ftp_check $ftp_host

echo -e "\nget file from $ftp_local_host"
        ftp -iv $ftp_local_host <<GETDATA > ftp_results.$$
        cd $filedir
        mget $file_pref*
GETDATA
        result=$?

        if [ $result -ne 0 ]; then
        echo -e  "\nftp get file from $ftp_local_host failed, contact EPS"
        cat ftp_results.$$
        rm -v ftp_results.$$
        exit 4
        fi

        cat ftp_results.$$
        rm -v ftp_results.$$

	ls -1 $file_pref* | while read FILE1
		
		do

export data_file=$FILE1
export pgp_file=`echo $data_file | sed -e 's/.txt/.pgp/'`

echo -e "\nencrypt $data_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --sign -r "$pgp_rem_sig" --text --output $pgp_file --encrypt $data_file >pgp_transcript.$$

errorchk $? "encrypt $data file"

ftp_vendor $ftp_host $pgp_file $pgp_file bin "cd upload"

securezip $data_file outbound

ftp_file $ftp_local_host $data_file $data_file "cd $filedir/archive"

ftp_delete $ftp_local_host $data_file "cd $filedir"

rm -fv $data_file $pgp_file pgp_transcript.$$

		done

archive_clean $outbound_archive $file_pref $FileAge

}

function inproc {

echo -e "\nget file on qantas server"
        ftp -iv $ftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd upload
 	bin
        dir
        mget $file_pref*.pgp
        quit
GETDATA

        result=$?

        if [ $result -ne 0 ]; then
        echo "FTP get of Qantas file(s) failed"
        cat ftp_results.$$
        rm ftp_results.$$
        exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

ls -1 $file_pref*.pgp | while read FILE1
	do

export data_file=`echo $FILE1 | sed -e 's/pgp/txt/'`

echo -e "\nProcessing file $FILE1"

echo -e "\nDelete $FILE1 on Qanats server"
        ftp -v $ftp_host <<RENMDATA >ftp_results.$$ 2>&1
        cd upload
        del $FILE1
        quit
RENMDATA

        result=$?

        if [ $result -ne 0 ]; then
echo -e "\nDelete of file $FILE1 on $ftp_host failed"
        cat ftp_results.$$
        rm -fv ftp_results.$$
        exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

echo -e "\nDecryptQantas $data_pgp_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch --output $data_file --decrypt $FILE1 >pgp_transcript.$$ 2>&1
cat pgp_transcript.$$
errorchk $? "decrypt $FILE1 for inbound `whoami`"

ftp_file $ftp_local_host $data_file $data_file "cd $filedir"

echo -e "\ncleaning up inbound directory"
mv -v $FILE1 $inbound_archive
rm -fv $data_file pgp_transcript.$$

	done

archive_clean $inbound_archive $file_pref $FileAge

}

case "$direction" in 

        retro_in)
export file_pref=qantasqueries
export filedir=mpprod/retrocredit/OALquery/QF
echo -e "\nBegin processing for retro in file"
inproc
echo -e "\nProcessing for qantas retro file in complete"
        ;;

        response_in)
export file_pref=ASResponse_QF
export filedir=mpprod/retrocredit/ASResponse/QF
echo -e "\nBegin processing for handback in file"
inproc
echo -e "\nProcessing for JL on AS Retropost in complete"
        ;;

        retro_out)
export file_pref=ASQuery_QF
export filedir=mpprod/retrocredit/ASQuery/QF
export tag_file=QF_Member_Query_TAG.txt
echo -e "\nBegin processing for retro in file"
outproc
ftp_delete $ftp_local_host $tag_file "cd $filedir"
echo -e "\nProcessing for qantas retro file in complete"
        ;;


        response_out)
export file_pref=QFResponses_ASsend
export tag_file=QF_MEMBER_RESPONSE_TAG.TXT
export filedir=mpprod/retrocredit/OALresponse/QF
echo -e "\nBegin processing for handback in file"
outproc
ftp_delete $ftp_local_host $tag_file "cd $filedir"
echo -e "\nProcessing for AS response out is complete"
        ;;

esac
