#!/bin/bash

set -x

# Set up the QUBE data transfer stand alone script

export PGPPASS=seavvdmzftp
export BATCHMODE=yes          # Turn on non-prompted PGP encrypting
export ftp_local_host=asprodftp
export basename=*.csv
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export wc_mailto="joanne.gies@alaskaair.com"
#export wc_mailto="pc.hcm.production.system.msgs@alaskaair.com"
export datestamp=`/bin/date +%b%d%Y.%H%M`
export logfile=$HOME/transfer_log
export FileAge=30

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

echo -e "\nget file on $ftp_local_host" 
	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
        cd "airportoperations/qube"
	dir
        bin
      	mget *csv
        quit
GETDATA

cat ftp_results.$$
rm -f ftp_results.$$


echo -e "\nprocessing ADP outbound scanned image file" $File1

	ls -1 *.csv | while read File1
	do

echo -e "\nThis is the csv file" $File1

securezip $File1 outbound
records=`wc -l $File1 | awk '{print $1}'`


echo -e "\nThis is the $File1" $File1
 

#echo -e "\nDelete file on $ftp_local_host" 
#	ftp -v -i $ftp_local_host <<GETDATA >ftp_results.$$ 2>&1
#       cd "Airport Operations\qube"
#       dir
#       del "$File1"   
        quit
#GETDATA

#	result=$?
#	if [ $result -ne 0 ]; then
#	echo -e "\narchive of file $File1 on $ftp_local_host failed.\n"
#	cat ftp_results.$$
#	rm -fv ftp_results.$$
#	exit 4
#	fi

rm -f ftp_results.$$
rm -f $File1

      done

archive_clean $outbound_archive .img $FileAge




archive_clean *.csv $FileAge


echo -e "\nBegin processing for `whoami` inbound processing"


