#!/bin/bash

# Encrypt the AS data file to ftp to/from reliastar
# Set the environment variables

. $HOME/bin/reliastr_environment
program=`basename $0`

export direction=$1

	if [ -z $direction ]; then
echo -e "\n	Missing direction parm.
	proper syntax is: process_reliastr_data direction
	where direction equals IN or OUT\n"
	exit 4
	fi

case "$direction" in

	OUT)

cd $hcmdir_out
export filepref=Alaska_coll*.txt

filecnt=`ls -1 $filepref |wc -l`
echo -e "\nthere are $filecnt files to process"

ls -1 $filepref |
	while read FILE1
	do
	export datafile=$FILE1
	export tagfile=`echo $FILE1 | sed -e s/.txt/.tag/`
	export gpgfile=${datafile}.asc

echo -e "\nbegin processing outbound file $datafile for `whoami`"	
outproc
echo -e "\nend of `whoami` processing for $datafile"		

	done

echo -e "\nRemove archived files older than $FileAge days"
find $outbound_archive/* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

	;;

	IN)

export basename=Alaska_bill
export datafile=${basename}.txt
export pgpfile=${datafile}.pickup
export tagfile=${datafile}.tag

echo -e "\nbegin processing inbound file $datafile for `whoami`"
inproc
echo -e "\nend of `whoami` processing for $datafile"

	;;
esac
