#!/bin/bash

# Set up the rocket data transfer environment

export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export nofiledate=`/bin/date "+%A, %D"`
export infile=RMROCKETMILESPIT.txt
export outfile_prefix=RMROCKETMILES
export mail_to="dave@rocketmiles.com,daniel@rocketmiles.com"
FileAge=30

. /opt/local/ops_scripts/function_lib

direction=$1

function inbound {

cd $inbound_dir

records=`wc $infile | awk '{print $2}'`

echo -e "\n$infile ($records records) received at `date`"

securezip $infile inbound

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $infile

echo -e "\ncleaning up inbound directory"
rm -f $infile

archive_clean $inbound_archive $infile $FileAge

}

function outbound {

cd $outbound_dir

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix

export solar_file=`ls -1 $outfile_prefix*`
echo -e "\n****** processing outbound file $solar_file ******"

securezip $solar_file outbound

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nemail to rocket that the handback file $solar_file is ready, please delete after pickup"
Mail -s "Hello Rocket Man- Handback file $solar_file is now on our server, please delete after picking up" $mail_to </dev/null

}

direction=$1

        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_drocket_data direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in)
echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"
        ;;

        out)
echo -e "\nBegin processing for `whoami` outbound processing"
outbound
archive_clean $outbound_archive $outfile_prefix $FileAge
echo -e "\nEnd of `whoami` outbound processing"
        ;;

esac
