#!/bin/bash

function mainproc {

export data_file=`ls -1 $file_pref`

	if [ -s $data_file ]; then
rm -fv $data_file
	fi

}

cd $HOME/inbound
ls -l invas* >> $HOME/invas.log
echo -e "\n " >> $HOME/invas.log

export file_pref=invas*.txt
mainproc

export file_pref=invas*.cmp
mainproc
