#!/bin/bash

set -x
export ftphost=mvs
export job=srftasrd
export jcl=$HOME/bin/${job}.jcl
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`date +%m%d%y.%H%M`
export dcbparms=""
export fileage=7

. /opt/local/ops_scripts/function_lib

function mainproc {

ftp_check $ftphost

cd $inbound_dir

export data_file=`ls -1 $file_pref*`

dsn_2mvs $ftphost $data_file "'$dsn'" bin

echo -e "\nmove $data_file to $inbound_archive"
mv $data_file $inbound_archive

ftp_jcl $jcl $ftphost

archive_clean $inbound_archive $file_pref $fileage

echo -e "\nremove tagfiles older than $fileage days"

}

echo -e "\nprocess tcn file"
        export file_pref=sabre_as_asr_*
	export dsn=SR.AMRIS.RECEIVE.ASR.COMP
mainproc
