#!/bin/bash



export ftphost=mvs
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`date +%m%d%y.%H%M`
export dcbparms=""
export fileage=20

. /opt/local/ops_scripts/function_lib

function putdsn {

cd $inbound_dir

export data_file=`ls -1 $file_pref*`

dsn_2mvs $ftphost $data_file "'$dsn'" bin

echo -e "\nmove $data_file to $inbound_archive"
mv $data_file $inbound_archive

echo -e "\nremove tagfiles older than $fileage days"
#find $inbound_archive/*.tag* -mtime +$fileage -print |
#       while read FILE1
#        do
#        echo "removing file $FILE1"
#        rm -f $FILE1
#        done

}


echo -e "\nprocess tcn file"
#	export tagfile=certrecatc_tcn4.tag.comp
        export file_pref=1s_as_asr_*.cmp
	export dsn=PROG.SR.AMRIS.RECEIVE.ASR.TEST.COMP
putdsn

