#!/bin/bash

sftp_host=ex_as002@efg.cert.sabre.com

echo -e "\ncheck connectivity to $sftp_host"
        sftp -vvv $sftp_host <<CHECK >ftp_results.$$
        dir
        quit
CHECK
        result=$?

export check=`grep -ic sftp ftp_results.$$`

        if [ $result -ne 0 -o $check -lt 1 ]; then
        echo "FTP check to $local_host failed"
        cat ftp_results.$$
        rm -fv ftp_results.$$
        exit 4
        fi

