#!/bin/bash

export indir=/ftphome/sabreftp/inbound
export outdir=/ftphome/airit/inbound
export airfacts_dir=/ftphome/airfacts/outbound
export alert_recipient=eps@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export file_prefix=sabre_as_pdi
export tagfile=sabrefile.tag
export xmitdate=`date '+%Y%m%d_%H%M%S'`

. /opt/local/ops_scripts/function_lib

cd $indir

echo -e "\ncontents of ${indir}"
ls -lrt

echo -e "\nCmp files - Sabre Compressed Files detected in directory ${indir}"
FILECOUNT=`ls -l ${file_prefix}*.cmp | wc -l`

if [[ $FILECOUNT -gt 0 ]]; then
	echo -e "Total cmp files found $FILECOUNT"
	ls -lh ${file_prefix}*.cmp

	echo -e "Processing date: ${xmitdate}" > $indir/$tagfile
 
	ls -1 ${file_prefix}*.cmp | while read FILE1
	do
	size_check $FILE1

	    export airfacts_tag=$FILE1.done

            echo -e "\ncopy $FILE1 to $airfacts_dir"
	    cp -p $FILE1 $airfacts_dir
	    errorchk $? "copy $FILE1 to $airfacts_dir"

            echo -e "\ncreate $airfacts_tag in $airfacts_dir"
            touch $airfacts_dir/$airfacts_tag
            errorchk $? "create $airfacts_tag in $airfacts_dir"

            echo -e "\nchown to airfacts for $FILE1 in $airfacts_dir"
	    chown -v airfacts:airfacts $airfacts_dir/$FILE1
            errorchk $? "chown to airfacts for $FILE1 & in $airfacts_dir"

            echo -e "\nchown to airfacts for $airfacts_tag in $airfacts_dir"
	    chown -v airfacts:airfacts $airfacts_dir/$airfacts_tag
            errorchk $? "chown to airfacts for $airfacts_tag in $airfacts_dir"

	echo -e "\nTransferring $FILE1 from source to $outdir"
	echo -e "Transferring $FILE1 from source to $outdir" >> $indir/$tagfile

	mv -fv $FILE1 $outdir
	errorchk $? "Move file $FILE1 to $outdir"

	done

	ls -l /ftphome/airfacts/outbound/sabre*

	echo -e "\nGenerate $indir/$tagfile for next job\n"
	mv -v $indir/$tagfile $outdir
	errorchk $? "Move $indir/$tagfile to $outdir"

	echo -e "\nChange Ownership for all files under $outdir"
	chown airit:airit $outdir/*
	errorchk $? "Chg Ownership for all files under $outdir"

else
  	echo -e "\n No cmp files detected"
	errorchk $? "No cmp files detected"
fi
