#!/bin/bash

program=`basename $0`

export BASH_ENV=$HOME/.bashrc
export RUNTIMEPATH=/usr/local/TDAccess2.2
export LD_LIBRARY_PATH=/usr/local/TDAccess2.2
export ftp_host=seavvpsmcfs
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export donefile=
export ops=/opt/local/ops_scripts
export FileAge=15

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

export data_cmp_file=`ls -1 BIDT_*.CMP`
export data_file=`echo $data_cmp_file | sed -e s/CMP/DAT/`

echo -e "\ndecompress $data_cmp_file"
echo $data_cmp_file | decompx $data_file
	
	result=$?

	if [ $result -ne 0 ]; then
MSG="decompress failure of file $data_cmp_file"
echo -e "\nNotify Production Services."
exit 4
	fi

ftp_vendor $ftp_host $data_file $data_file "cd PSMC/BIDT/CDD"

echo -e "\nmove $data_cmp_file to $inbound_archive"
mv $data_cmp_file $inbound_archive

echo -e "\ndo cleanup"
rm -f $data_file decomp.log

archive_clean $inbound_archive -------???-------- $FileAge
