#!/bin/bash

#export local_hostxxx=asprodftp
export PATH=/usr/local/TDAccess3.2:$PATH
export test_host=ftptest
export qa_host=ftpqa
export RUNTIMEPATH=/usr/local/TDAccess3.2
export LD_LIBRARY_PATH=/usr/local/TDAccess3.2
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export lz=/bi/abk/ind
export file_pref=sabre_as_ind
export datestamp=`/bin/date +%b%d%Y.%H%M`
export datadate=`/bin/date +%Y%m%d`
export FileAge=7
export ops=/opt/local/ops_scripts
export dom=alaskaair.com
export mail_to="dean.liebrich@$dom"

. /opt/local/ops_scripts/function_lib

echo -e "\nBegin processing for incoming SABRE ABK files from Sabre at `date`"
#ftp_check $local_host
#ftp_check $test_host
ftp_check $qa_host

cd $inbound_dir
echo -e "\ncontents of $inbound_dir"
ls -l

export encfile=`ls -1 ${file_pref}*.cmp`
export datadate=`echo $encfile | cut -c14-21` 
export datafile=ind.dat.$datadate
export tagfile=inddata.done.$datadate.tag

size_check $encfile

echo -e "\nprocessing encrypted ind file $encfile"

echo -e "\ndecompress $encfile at `date`"
echo $encfile | decompx $datafile 
errorchk $? "decompress $encfile"

echo -e "\nMove $encfile to $inbound_archive at `date`"
mv -v $encfile $inbound_archive
errorchk $? "Move $encfile to $inbound_archive"

#ftp_file $local_host $datafile $datafile "cd $lz"
#ftp_file $test_host $datafile $datafile "cd $lz"
ftp_file $qa_host $datafile $datafile "cd $lz"

echo -e "\ncreate tag file $tagfile"
touch $tagfile

#ftp_file $local_host $tagfile $tagfile "cd $lz"
#ftp_file $test_host $tagfile $tagfile "cd $lz"
ftp_file $qa_host $tagfile $tagfile "cd $lz"

echo -e "\nremove tag file $tagfile and $datafile"
rm -v $tagfile $datafile
errorchk $? "remove tag file $tagfile"

archive_clean $inbound_archive $file_pref $FileAge

echo -e "\nProcessing of incoming SABRE IND files complete at `date`"
