#!/bin/bash

export inbound_dir=$HOME/inbound
export data_file=prod_receive_ffrecflt_fltdata.comp

cd $inbound_dir

filecount=`ls -1 prod_receive_ffrecflt_fltdata?.comp |wc -l`
	if [ $filecount -eq 1 ]; then

export temp_file=`ls -1 prod_receive_ffrecflt_fltdata?.comp`

echo "checking size of file $temp_file"
startsize=`ls -l $temp_file | awk '{print $5}'`
sleep 60
endsize=`ls -l $temp_file | awk '{print $5}'`

		while [ $startsize -ne $endsize ]
		do
		echo "incomplete file... re-checking"
		startsize=`ls -l $temp_file | awk '{print $5}'`
		sleep 60
		endsize=`ls -l $temp_file | awk '{print $5}'`
		done

mv $temp_file $data_file
echo "iceland air FQTV data has been recieved from Sabre" | Mail -s `whoami` "dean.liebrich@alaskaair.com,donna.downing@alaskaair.com"

	fi
