#!/bin/bash


set -x
export ftphost=mvs
export inbound_dir=$HOME/inbound.cert
export inbound_archive=${inbound_dir}.archive
export datestamp=`date +%m%d%y.%H%M`
export dcbparms=""
export fileage=20

. /opt/local/ops_scripts/function_lib


function putdsn {

cd $inbound_dir

export data_file=`ls -1 $file_pref*`

dsn_2mvs $ftphost $data_file "'$dsn'" bin

echo -e "\nmove $data_file to $inbound_archive"
mv $data_file $inbound_archive


}

cd $inbound_dir

echo -e "\ncontents of $inbound_dir"
ls -l

echo -e "\nprocess accb file"
#	export tagfile=xxxx
        export file_pref=CERT_AS_ACCB*.CMP
	export dsn=PROG.SR.SABRE.AS.ACCB

	if [ -f $tagfile ]; then
putdsn
	fi


echo -e "\nprocess auth file"
#	export tagfile=xxxx
        export file_pref=CERT_AS_AUTH*.CMP
	export dsn=PROG.SR.SABRE.AS.AUTH
	if [ -f $tagfile ]; then
putdsn
	fi
 	


echo -e "\nprocess local file"
#	export tagfile=xxxxx
        export file_pref=CERT_AS_LOCAL*.CMP
	export dsn=PROG.SR.SABRE.AS.LOCAL
	if [ -f $tagfile ]; then
putdsn
	fi


echo -e "\nprocess accb file"
#	export tagfile=xxxx
        export file_pref=CERT_AS_NOBILL*.CMP
	export dsn=PROG.SR.SABRE.AS.ACCB.NOBILL
	if [ -f $tagfile ]; then
putdsn
	fi


