#!/bin/bash


export ftphost=mvs
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`date +%m%d%y.%H%M`
export dcbparms=""
export fileage=20

. /opt/local/ops_scripts/function_lib

function putdsn {

cd $inbound_dir

dsn_2mvs $ftphost $data_file "'$dsn'" bin


echo -e "\nmove $data_file to $inbound_archive"
mv $data_file  $inbound_archive/$data_file.$datestamp


echo -e "\nremove tagfiles older than $fileage days"

rm $tagfile

}

echo -e "\nprocess tcn file"
	export tagfile=certrecatc_tcn4.tag
	export data_file=cert_amris_receive_tcn.comp
	export dsn=PROG.SR.AMRIS.RECEIVE.TCN4.COMP
putdsn
