#!/bin/bash

export PATH=/usr/local/TDAccess3.2:$PATH
export test_host=ftptest
export RUNTIMEPATH=/usr/local/TDAccess3.2
export LD_LIBRARY_PATH=/usr/local/TDAccess3.2
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export FileAge=10
export ops=/opt/local/ops_scripts
export mail_to="Production.Operations@alaskaair.onmicrosoft.com"

. /opt/local/ops_scripts/function_lib

export file_env=$1

function mainproc {

cd $outbound_dir

echo -e "\nBegin processing for outgoing VITStar files to Sabre at `date`"
ftp_check $local_host

echo -e "\ncheck connectivity to $sftp_host"
        sftp -v $sftp_host <<CHECK >ftp_results.$$
        dir
        quit
CHECK
        result=$?

export check=`grep -ic sftp ftp_results.$$`

        if [ $result -ne 0 -o $check -lt 1 ]; then
        echo "FTP check to $sftp_host failed"
        cat ftp_results.$$
        rm -fv ftp_results.$$
        exit 4
        fi

cat ftp_results.$$
rm -fv ftp_results.$$

echo -e "\ncontents of $outbund_dir"
ls -l

echo -e "\nftp get VISTar file from $ftp_local_host\n"
        ftp -v -i $local_host <<MGET >ftp_results.$$
        cd $src_lz
        dir
        mget ${file_prefix}*
        bye
MGET
        result=$?

        if [ $result -ne 0 ];then
        echo "\nFTP get of $file_prefix file failed,
        please investigate\n"
        cat ftp_results.$$
        rm ftp_results.$$
        exit 4
        fi

cat ftp_results.$$
rm ftp_results.$$

export datafile=`ls -1 ${file_prefix}*.xml`
export cmpfile=`echo $datafile | sed -e 's/xml/cmp/'`

securezip $datafile outbound

echo -e "\nprocessing compressed VITStar file $cmpfile"

echo -e "\ncompress $datafile at `date`\n"
echo $datafile | compx $cmpfile 
errorchk $? "compress $datfile"

echo -e "\nFTP $cmpfile to $sftp_host"
        sftp -v $sftp_host <<PUT >ftp_results.$$
        put $cmpfile
        quit
PUT
        result=$?

export check=`grep -ic sftp ftp_results.$$`

        if [ $result -ne 0 -o $check -lt 1 ]; then
        echo "FTP $cmpfile to $sftp_host failed"
        cat ftp_results.$$
        rm -fv ftp_results.$$
        exit 4
        fi

rm -fv ftp_results.$$

ftp_file $local_host $datafile $datafile "cd $arch_lz"
ftp_delete $local_host $datafile "cd $arch_lz"

echo -e "\nremove $datafile and compress.log from $outbound_dir"
rm -v $datafile compress.log $cmpfile

archive_clean $outbound_archive $file_prefix $FileAge

echo -e "\nProcessing of outgoing VITStar files complete at `date`"

}

case "$file_env" in

        cert)
export local_host=ftptest
sftp_host=ex_as002@efg.cert.sabre.com
export src_lz=/mptest/VITStar
export arch_lz=${src_lz}/archive
file_prefix=CI_CRT_
mainproc
       ;;

        prod)
export local_host=asprodftp
sftp_host=ex_as002@efg.sabre.com
export src_lz=/mpprod/VITStar
export arch_lz=${src_lz}/archive
file_prefix=CI_PRD_
mainproc
       ;;
	
	*)
echo -e "\nargument is missing or invalid, 
need to pass one of the following arguments: 
cert or prod"
exit 4
        ;;
esac
