#!/bin/bash

export local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export lz=/psmc/sabregm/inbound
export datestamp=`/bin/date +%b%d%Y.%H%M`
export FileAge=10
export ops=/opt/local/ops_scripts
export dom=alaskaair.com
export mail_to="dean.liebrich@$dom"

. /opt/local/ops_scripts/function_lib

cd $inbound_dir
echo -e "\ncontents of $inbound_dir"
ls -l

function mainproc {

export datfile=`ls -1 $file_pref*.dat`
export tagfile=`echo $datfile | sed -e 's/dat/tag/'`

echo -e "\nprocessing file $datfile"

securezip $datfile inbound

ftp_file $local_host $datfile $datfile "cd $lz"
ftp_file $local_host $tagfile $tagfile "cd $lz"

echo -e "\nremove tag file $tagfile and dat file $datfile"
rm -v $tagfile $datfile
errorchk $? "remove tag file $tagfile"

archive_clean $inbound_archive $file_pref $FileAge

}

echo -e "\nBegin processing for pre departure file from Sabre at `date`"
ftp_check $local_host
export file_pref=as_predptr
mainproc
echo -e "\nProcessing of incoming pre departure file complete at `date`"

echo -e "\nBegin processing for post departure file from Sabre at `date`"
ftp_check $local_host
export file_pref=as_postdptr
mainproc
echo -e "\nProcessing of incoming post departure file complete at `date`"
