#!/bin/sh

. /opt/local/ops_scripts/function_lib

export ftphost=mvs
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`date +%m%d%y.%H%M`
export filename=srrecps2.tag
export MAILLST="dean.liebrich@alaskaair.com,finance.info.team.oncall@alaskaair.com"
MSG="The PS2000 tag file was detected at $datestamp and moved to the archive directory"

cd $inbound_dir

ls -l

filecheck=`ls -1 $filename | wc -l`

	if [ $filecheck -gt 0 ]; then
echo $MSG | Mail -s "PS2000 tag file" $MAILLST
mv $filename $inbound_archive/$filename.$datestamp
	fi

exit 0
