#!/bin/bash

# Set up the Safeway data transfer environment
# This script is used by other scripts to preset values from a common source.

export PGPPASS=seavvdmzftp
export pgp_remote_sig="safeway TP"
export ftp_host=ftp.safeway.com
export ftp_enroll_host="167.146.8.29 5565"	#prod
#export ftp_enroll_host=165.19.8.145 5565"	#test
export ftp_local_host=asprodftp
export lz=mpprod
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export file_prefix=SYSAFEWAYPIT
export local_file=${file_prefix}.txt
export safeway_file=SYSAFEWAYPIT*
export safeway_pgp_file=$safeway_file.asc
export handback_count=safeway_count
export handback_pgp_count=$handback_count.asc
export handback_error=safeway_error
export handback_pgp_error=$handback_error.asc
export tagfile=safeway.tag
export alert_recipient=dean.liebrich@alaskaair.com
export datestamp=`date +%b%d%Y.%H%M`
export info_to="dean.liebricha@alaskaair.com"
export errors_to="production.services@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20

. /opt/local/ops_scripts/function_lib
