#!/bin/bash

#stand alone script
export ftp_local_host=asprodftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="production.services@alaskaair.com"
export safeway_in_pre=SYSAFEWAYPIT
export FileAge=20

. /opt/local/ops_scripts/function_lib

program=`basename $0`

cd $inbound_dir

export data_file=`ls -1 $safeway_in_pre*`
echo -e "\n This is the safeway in file  $data_file"
records=`wc $data_file | awk '{print $2}'`

securezip $data_file inbound

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $data_file

echo -e "\nremove temp files from $inbound_dir"
rm -fv $solar_file $data_file

archive_clean $inbound_archive $data_file $FileAge
