#!/bin/bash

# Set the environment variable
. $HOME/bin/sco_pos_environment

export airdir=$1

	if [ -z $airdir ]; then
echo -e "\n	Missing airline/direction parm,
	proper syntax is process_scotia_data airline.direction
	where airline=as or qx and direction=in or out. i.e.
	process_scotia_data asout\n"
	exit 4
	fi	

case "$airdir" in

	qxin)

export airline=QX
export sco_pgp_file=RSAPEDCI.new
export local_file=qxscotia-report
export local_pgp_file=${local_file}.pgp


echo -e "\nBegin processing for QX inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"

;;

	asin)

export airline=AS
export sco_pgp_file=RSAPEDCI.new  
export local_file=scotia-report
export local_pgp_file=${local_file}.pgp

echo -e "\nBegin processing for AS inbound $local_file"
inproc
echo -e "\nInbound processing complete for $local_file"

;;

	asout)

airline=AS
export data_file=appaysco
export data_file_asc=${data_file}.asc
export sco_pgp_file=appaysco.RSAHCHIN
export tag_file=${data_file}.tag

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $data_file"

;;

	qxout)

export airline=QX
export data_file=qppaysco
export data_file_asc=${data_file}.asc
export sco_pgp_file=qxapposcad.RSAHCHIN 
export tag_file=${data_file}.tag

echo -e "\nBegin processing for $airline outbound file $data_file"
outproc
echo -e "\nOutbound processing complete for $airline file $data_file"

;;

esac
