#!/bin/bash

# Set up the Scotia Systems data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/scotia_environment"

export PGPPASS=seavvdmzftp
export pgp_remote_signature="eaaprod"
export BATCHMODE=yes          # Turn on non-prompted PGP encrypting
export ftp_host=205.210.223.63
export ftp_local_host=asprodftp
export handback_data_file=appaysco
export qxhandback_data_file=qppaysco
export scotia_file=ededsacc
export scotia_filer=RSAPEDCI
export qxscotia_filer=RSAPEDCI
export scotia_new_file=ededsacc.new
export scotia_pgp_file=ededsacc.pgp
export scotia_new_filer=RSAPEDCI.new
export scotia_pgp_filer=RSAPEDCI.pgp
export qxscotia_new_filer=RSAPEDCI.new
export qxscotia_pgp_filer=RSAPEDCI.pgp
export qxqxscotia_pgp_filer=QXRSAPEDCI
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export handback_data_file_asc=${handback_data_file}.asc
export qxhandback_data_file_asc=${qxhandback_data_file}.asc
export tagfile=scotia.tag
export alert_recipient=eps@alaskaair.com
export dom=alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export outdate=`/bin/date +%Y%m%d`
export info_to="frederick.thinh@scotiabank.com"
export infor_to="ps.fin.production.system.msgs@$dom,Treasury@$dom,joanne.gies@$dom"
export errors_to="eps@alaskaair.com,production.services@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=10
