#!/bin/bash

# Set up the Scotia data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/sco_pos_environment"

export PGPPASS=seavvdmzftp
export remote_sig="eaaprod"
export BATCHMODE=yes          # Turn on non-prompted PGP encrypting
export ftp_host=205.210.223.63
export ftp_local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export tagfile=boa_apos.tag
export DT=`date '+%c'`
export info_to="dean.liebrich@alaskaair.com,joanne.gies@alaskaair.com"
export datestamp=`/bin/date '+%b%d%Y.%H%M'`
export outdate=`/bin/date '+%Y%m%d'`
export errors_to="dean.liebrich@alaskaair.com,joanne.gies@alaskaair.com"
export infor_to="ps.fin.production.system.msgs@alaskaair.com,joanne.gies@alaskaair.com"
#export infor_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=99

. /opt/local/ops_scripts/function_lib

function outproc {

rm ~/.netrc
ln -s ~/.netrc.$airdir ~/.netrc

cd $outbound_dir

echo $data_file 

echo -e "\nencrypting file $data_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor --sign -r "$remote_sig" --output $data_file_asc --encrypt $data_file >pgp_transcript.$$	
	result=$?

	if [ $result -ne 0 -o ! -f $data_file_asc ]; then
	echo "Alaska Scotia file $data_file encryption failure"
	cat pgp_transcript.$$
	rm -f pgp_transcript.$$
	exit 8
	fi

cat pgp_transcript.$$
rm -f pgp_transcript.$$


#ftp_vendor_check $ftp_host

ftp_vendor $ftp_host $data_file_asc "$sco_pgp_file" bin

echo -e "\nmove $data_file_asc to $outbound_archive"
mv $data_file_asc $outbound_archive/$data_file_asc.$datestamp
mv $data_file $outbound_archive/$data_file.$datestamp

echo -e "\nremoving temporary files"
rm -f pgp_transcript.$$ ftp_results.$$ $data_file $tag_file

echo -e "\nclean up archive directory"
	find $outbound_archive/$data_file_asc* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

}

function inproc {

rm ~/.netrc
ln -s ~/.netrc.$airdir ~/.netrc

cd $inbound_dir

#ftp_vendor_check $ftp_host 

ftp_vendor_get $ftp_host "$sco_pgp_file" $local_pgp_file bin

echo -e "\ndecrypt $local_pgp_file" 
echo $PGPPASS | gpg --passphrase-f 0 --batch --decrypt --output $local_file $local_pgp_file

result=$?

	if [ $result -ne 0 -o ! -s $local_file ]; then
	echo -e "\n`whoami` $airdir file decrypt problem.\n"
	exit 8
	fi

#ftp_vendor_check $ftp_local_host

ftp_vendor $ftp_local_host $local_file $local_file.$outdate.txt "cd PSFINFTP/AP/APPOSPAY"

echo "Send mail notification to $infor_to"
Mail -s "The $airline Scotia report has been sent to your server at `date`" $infor_to < $local_file

echo -e "\nmove $local_pgp_file to archive directory and timestamp"
mv $local_file $inbound_archive/$local_file.$datestamp

echo "remove temp files"
rm -f $local_file $local_pgp_file

echo "removing archived files older than $FileAge days"
find $inbound_archive/* -mtime +$FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

}
