This is an automated message, please do not    
respond to this email address....

SIR Monthly close file  
has been successfully FTP to Shephard Systems.
If this is not the case, please contact
me.
  
thank you.
David.
david.kim@alaskaair.com
office: (206) 431 - 7091

note: if weekends/holidays/after hours:
please contact:
    production.services@alaskaair.com
    to review stdlst for the AGAPPS maestro schedule TASIR02.
    (especially:  TASIR02-SIR2FTP job)

