#!/bin/bash

export ftp_host=216.113.156.71
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`date +%Y%m%d.%H%M%S`
export tagfile=atlas_sir_pmth_cls.tag
export data_file=atlas_sir_xclose
export comp_file=${data_file}.Z
export ftp_out_file=`datecalc today -1 days pic YYYYMMDD`close_SIR.Z
export maillist="ATLAS.administration@AlaskaAir.com,psmc.rm.support@alaskaair.com"
export FileAge=20

. /opt/local/ops_scripts/function_lib

echo -e "\nprocess outgoing shepsysfile $data_file"

cd $outbound_dir

ftp_vendor_chk $ftp_host

securezip $data_file outbound

compress -f $data_file
errorchk $? "compress $data_file"

ftp_vendor $ftp_host $comp_file $ftp_out_file bin

archive_clean $outbound_archive "$data_file" $FileAge

echo -e "\nremove file $data_file"
rm -fv $comp_file $tagfile

#echo -e "\nsend email to $maillist"
#Mail -s "SIR Monthly Close file process" $maillist < ~/bin/SIRcls_cmplt.msg

echo -e "\nend processing for outgoing file $data_file"
