#!/bin/bash

# Set up the Shepherd data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/shepherd_environment"

#export ftp_exthost=12.153.91.11
export ftp_exthost=216.113.156.71
export ftp_localhost=seavvpsmcfs
export filename=process_qsi
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export filedate=`date +%Y%m%d.%H%M%S`
export ext=".dat.gz"
export tagext=".tag"
export FileAge=20

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

ftp_vendor_chk $ftp_localhost
ftp_vendor_chk $ftp_exthost

#Remove tag file from $ftp_localhost
ftp_delete $ftp_localhost $filename$tagext "cd psmc/qsi/outbound"

#Create list of files ready to be sent to Shepherd
	ftp $ftp_localhost <<results >ftp_results.$$
	cd psmc/qsi/outbound
	ls -1
	bye
results

echo "This is the dir list:"
cat ftp_results.$$

putfilelist=`grep -e "qsi_" ftp_results.$$`  

echo "This is the put list:"
echo "$putfilelist" | while read FILE1
	do 
	echo "Processing file $FILE1"
	ftp_vendor_get $ftp_localhost $FILE1 $FILE1 "cd psmc/qsi/outbound"	
	compress $FILE1
	ftp_vendor $ftp_exthost $FILE1.Z $FILE1.Z
	mv $FILE1.Z $outbound_archive/$FILE1.$filedate.Z
	ftp_delete $ftp_localhost $FILE1 "cd psmc/qsi/outbound"
done

archive_clean $outbound_archive "*" $FileAge

}
