#!/bin/bash

export ftp_host=216.113.156.71
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`date +%Y%m%d.%H%M%S`
export tagfile=atlas_sir_files.tag
export FileAge=20

. /opt/local/ops_scripts/function_lib

function outproc {

cd $outbound_dir

securezip $data_file outbound

dos2unix $data_file

compress -f $data_file
errorchk $? "compress $data_file"

ftp_vendor $ftp_host $comp_file $ftp_out_file bin

archive_clean $outbound_archive "$data_file" $FileAge

echo -e "\nremove file $data_file"
rm -fv $comp_file

}

ftp_vendor_chk $ftp_host

export data_file=atlas_sir_voids
export comp_file=${data_file}.Z
export ftp_out_file=`datecalc today -1 days pic YYYYMMDD`_SIRv.Z
echo -e "\nprocess outgoing shepsysfile $data_file"
outproc
echo -e "\nend processing for outgoing file $data_file"

export data_file=atlas_sir_xtract
export comp_file=${data_file}.Z
export ftp_out_file=`datecalc today -1 days pic YYYYMMDD`_SIR.Z
echo -e "\nprocess outgoing shepsysfile $data_file"
outproc
rm -fv $tagfile
echo -e "\nend processing for outgoing file $data_file"
