#!/bin/bash

# Process incoming/outgoing UATP files to/from SITA 

# Set the environment variables
. $HOME/bin/`whoami`_environment_adhoc   #PROD
program=`basename $0`

export filetype=$1

case "$filetype" in

	out)
	#export file=tsti0027 	#TEST
	export file=atci0027	#PROD
	export uatp_file=${file}.asc
	
echo -e "\nBegin processing UATP file to SITA"
outproc
echo -e "\nProcessing UATP file from SITA complete"
;;

	result)
	#export file=tstv0027	#TEST
	export file=atcv0027 	#PROD
	export uatp_file=${file}.asc
	export jcl=$HOME/bin/sraerrck.jcl


echo -e "\nBegin processing UATP `whoami` validation file"
decrypt
result
echo -e "\nProcessing for UATP `whoami` validation file complete"
;;

        recon)
	#export file=tstz0027.zip    #TEST
        export file=atcz0027.zip   #PROD
        export uatp_file=${file}.asc
	export alfile=AL0027
	export formfile=FORM0027
	export jcl=$HOME/bin/srarturn.jcl

echo -e "\nBegin processing UATP `whoami` recon file"
decrypt
recon
echo -e "\nProcessing for UATP `whoami` recon file complete"
;;

	*)
#Invalid Filetype parameter given
echo "Filetype = $filetype This is an unknown parameter value.  Known values are - out, result and recon"
exit 10
;;

esac
