#!/bin/bash

# Set up the smart signal push
# This script is stand alone

export PGPPASS=seavvdmzftp
export remote_sig="SmartSignal Customer Support"
export ftp_host=ftp.smartsignaldata.com
export sftp_host=500200281@sftp.gemft.net
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export tagfile=smartsig.tag
export data_file=sgefiles.zip
export pgpfile=${data_file}.gpg
export emailtxt=blat_file_list.txt
export ssdom=ge.com
export maillist="ruby.thayer@alaskaair.com,travis.zuber@$ssdom,dan.wagner@$ssdom,alex.p.jenkins@$ssdom,eric.logis@$ssdom"
export DT=`date '+%c'`
export datestamp=`/bin/date '+%b%d%Y.%H%M'`
export maildate=`/bin/date '+%Y%m%d-%H:%M'`
export logfile=$HOME/transfer_log
export FileAge=20

. /opt/local/ops_scripts/function_lib

cd $outbound_dir

#ftp_vendor_chk $sftp_host


#ftp_vendor $ftp_host $data_file $data_file.$datestamp passive bin

echo -e "\nput $data_file to $sftp_host"
	sftp $sftp_host <<PUTDATA >ftp_results.$$
        cd tovan/500100362
	bin
	put $data_file $data_file.$datestamp
        dir
	bye
PUTDATA
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP put of $data_file to GXS failed, contact EPS"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	fi

cat ftp_results.$$
rm -f ftp_results.$$

securezip $data_file outbound 
securezip $emailtxt outbound

Mail -s "Files sent to SmartSignal on $maildate" $maillist < $emailtxt

echo -e "\nremoving temporary files"
rm -f $data_file $tag_file $pgpfile $emailtxt

archive_clean $outbound_archive "*" $FileAge
