#!/bin/sh

# Process data from Starwood Hotels
#

export ftp_local_host=asprodftp
export lz=mpprod
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export data_file=starwood
export local_file=SWSTARWOODHOTELSPIT.txt
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="production.services@alaskaair.com"
export FileAge=20

. /opt/local/ops_scripts/function_lib

cd $inbound_dir
    
#rename file for SOLAR conv.
mv $data_file $local_file

securezip $local_file inbound

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

echo -e "\nremove temp files"
rm -f $local_file 

archive_clean $inbound_archive $local_file $FileAge
