#!/bin/bash

# Encrypt the ID90 data file to ftp to 
# Set the environment variables
#

program=`basename $0`
export PGPPASS=seavvdmzftp
export ftp_host=apps.id90.com
export ftp_local_host=asprodftp
ecport local_dir=?
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export basename=wbat_poc
export alert_recipient=joanne.gies@alaskaair.com
export datestamp=`date +%b%d%Y.%H%M`
export info_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=10
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

function mainproc {

cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\nget $data_file from $ftp_local_host"
ftp_vendor_get $ftp_local_host $data_file $data_file "cd $local_dir"

#echo -e "\nencrypt `whoami` file $data_file"
#echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor --sign -r "$pgp_signature" --output $data_pgp_file --encrypt $data_file >pgp_transcript.$$ 2>&1

#	result=$?

	if [ $result -ne 0 ]; then
#echo -e "\nencryption failed for `whoami` file $data_file, contact Prod. Svcs.\n"
#cat pgp_transcript.$$
#rm pgp_transcript.$$
#	exit 4
#	fi

#cat pgp_transcript.$$
#rm pgp_transcript.$$


securezip $data_file outbound

ftp_vendor "$ftp_host" $data_file $data_file "cd ???/???"

echo -e "\nfile was sent to $whoami" 
	
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP of $whoami file failed, please investigate"
	cat $ftp_results.$$
	exit 8
	fi


cat ftp_results.$$
rm -f ftp_results.$$



echo #-e "\ndelete $data_file on asprodftp" 
        ftp -v asprodftp <<DELDATA >ftp_results.$$
	cd "???\??"
        delete $data_file_file
	bye

DELDATA
archive_clean $outbound_archive $data_file $FileAge

echo -e "\nclean up temp files"
rm -f $data_file $data_pgp_file
