#!/bin/bash
set -x

# Encrypt the Talx data file and push to Talx
# for processing
#If sending test data use 11971testin
#If sending prod data use 11971prodin
# Set the environment variables
. $HOME/bin/talx_new_environment

cd $outbound_dir
rm -f $tagfile

#process talx file
export datafile=qxtalx
export pgpfile=11971testin_qx.msf
export tagfile=$hcmdir/qxtalx.tag


mainproc

#Mail -s "Talx QX data test files sent to $ftp_host at `date`" $talx_mailto </dev/null
