#!/bin/bash

# Process Thrifty mileage plan files
#

# Set environment values
. $HOME/bin/thrifty_environment
program=`basename $0`

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_choice_file direction where
        direction equals in or out\n"
        exit 4
        fi

case "$direction" in

        in)

export data_file=ZTTHRIFTYCARRENTALPIT.txt

echo -e "\nBegin processing for `whoami` inbound processing"
inbound
echo -e "\nEnd of `whoami` inbound processing"

        ;;

        out)

export data_file=ffthr_handback.$datestamp

echo -e "\nBegin processing for `whoami` outbound processing"
outbound
echo -e "\nEnd of `whoami` outbound processing"

        ;;

esac

