#!/bin/sh

# script to process Thrifty car rental data
# contact info: 
#

export ftp_host=ftp1.thrifty.com
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export ftp_local_host=asprodftp
export lz=mpprod
export rem_file=thrifty.txt
export rem_old_file=${rem_file}.old
export outfile_prefix=ZTTHRIFTYCARRENTALPIT
export outfile_tag=ffthr_handbckk.tag
export datestamp=`date +%y%m%d`
export FileAge=14

. /opt/local/ops_scripts/function_lib

function inbound {

cd $inbound_dir

echo -e "\nbegin processing for incoming `whoami` MP file"

ftp_vendor_chk $ftp_host
ftp_check $ftp_local_host

ftp_vendor_get $ftp_host $rem_file $data_file

ftp_solar_in $ftp_local_host $data_file

securezip $data_file inbound

echo -e "\nclean up $inbound_dir"
rm -f $data_file

ftp_delete $ftp_host $rem_old_file "cd out"
ftp_rename $ftp_host $rem_file $rem_old_file

archive_clean $inbound_archive $data_file $FileAge

echo -e "\nprocessing of inbound `whoami` file complete"

}

function outbound {

cd $outbound_dir

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix


exit

export solar_file=`ls -1 $outfile_prefix*`
echo -e "\nprocessing outbound file $solar_file"

securezip $solar_file outbound

echo -e "\ncreate tag file"
echo "tag file" > $outfile_tag

ftp_vendor $ftp_host $solar_file $data_file ascii 
ftp_vendor $ftp_host $outfile_tag $outfile_tag ascii 

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nclean up $outbound_dir"
rm -f $outfile_tag $solar_file

archive_clean $outbound_archive $outfile_prefix $FileAge

}
