#!/bin/sh

# define variables  #
export ftp_host=appprod6
export INDIR=/ftphome/trisept/inbound
export ARCHDIR=/ftphome/trisept/inbound.archive
export INFIL=apasdata
export DONEFIL=apasdone
export OUTFIL=/appl/fin/interfaces/ap/data/trisept_as.dat
export RELFIL=/appl/fin/interfaces/ap/data/trisept_as_release
export datestamp=`date +%m%d%y.%H%M`
export FileAge=20

######################################################
#  This script is trig'd by the existence of file
#  apasdone.  This file is FTP'd to this server by
#  Trisept and indicates a successful xmit of data file
#  file apasdata.  The file is then FTP'd to AAPPROD6 and
#  named trisept_as.dat.  The apasdone file is then 
#  FTP'd to AGAPPS and named trisept_as_release.  This
#  job is followed by APPPROD6#APTRISPT.APTRISPT.   
#  
    
cd $INDIR

echo -e "\ntimestamp and copy $INFIL to $ARCHDIR"
cp $INFIL $ARCHDIR/$INFIL.$datestamp
gzip $ARCHDIR/$INFIL.$datestamp

echo -e "nftp $INFIL to $ftp_host as $OUTFIL"
ftp  -v $ftp_host <<EOF >ftp_results.$$
put $INFIL $OUTFIL 
bye 
EOF
	result=$?

if [ $result -ne 0 ]; then
echo "FTP of $INFIL to $ftp_host failed"
cat ftp_results.$$
rm ftp_results.$$
exit 8
fi

cat ftp_results.$$ 
rm -f ftp_results.$$

echo -e "\nftp $DONEFIL to $ftp_host as $RELFIL"
ftp -v $ftp_host <<EOF1 >ftp_results.$$
put $DONEFIL $RELFIL
bye
EOF1
	result=$?

if [ $result -ne 0 ]; then
echo "FTP of $DONEFIL to $ftp_host failed"
cat ftp_results.$$
exit 8
fi 

cat ftp_results.$$ 

echo -e "\nclean up data directory"
rm -f $DONEFIL $INFIL ftp_results.$$

echo -e "\nremove archived files older than $FileAge days"
find $ARCHDIR/$INFIL.* -mtime +$FileAge -print |
      while read FILE1
      do
      echo "removing file $FILE1"
      rm -f $FILE1
      done
