#!/bin/sh

###########################################################
#  PUT QX RF REDEMPTION FILE (IV06QX) TO MVS DATQXET      #
#  RF.RFQXRRCV.QX.REDEEM AND TRIGGER RFQXRRCV             #
###########################################################
#  This script is trig'd by the existence of file IV06QXDN
#  which is FTP'd to this server by Trisept and indicates 
#  a successful xmit of QX ReFunds Redemption data file,
#  IV06QX.  If the input file is empty, the script will
#  just exit.  Otherwise the file is ftp'd to MVS dataset
#  RF.RFQXRRCV.QX.REDEEM.  JCL is then submitted to the  
#  MVS internal reader to trigger CA7 job RFQXRRCV.
#  The input file IV06QX is then timestamped, moved to the  
#  archive directory, and compressed.
#########################################################
   
INDIR=/ftphome/trisept/inbound
ARCHDIR=/ftphome/trisept/inbound.archive
INFIL=IV06QX
JCL=$HOME/bin/rfqxrrcv.jcl
dataset=rf.rfqxrrcv.qx.redeem
datestamp=`date +%m%d%y.%H%M`
FileAge=14

echo -e "\nremoving done file"
rm -f $INDIR/IV06QXDN

	if [ -s $INDIR/$INFIL ]; then

echo -e "\nftp $INFIL to MVS dataset $dataset"
# ftp data file to MVS #
ftp -v 159.49.42.28 <<EOF >ftp_results.$$
site recfm=fb lrecl=125 cylinders pri=3 sec=10 blksize=0 unit=prdda
put $INDIR/$INFIL '$dataset' 
bye
EOF

succftp=`grep -c "Transfer complete" ftp_results.$$`

	if [ $succftp -eq 1 ]; then
cat ftp_results.$$
rm -f ftp_results.$$

echo -e "\nsubmit jcl $JCL to MVS"
ftp -v 159.49.42.28 <<EOF1 >ftp_results.$$
site file=jes
put $JCL 
bye
EOF1

	else 
echo -e "\nftp of $INFIL to MVS failed\n"
	exit 8
	fi

cat ftp_results.$$
succftp=`grep -c "Transfer complete" ftp_results.$$` 

	if [ $succftp -eq 1 ]; then
rm -f ftp_results.$$

echo -e "\nmove $INFIL to $ARCHDIR/$INFIL.$datestamp"
mv $INDIR/$INFIL $ARCHDIR/$INFIL.$datestamp
gzip $ARCHDIR/$INFIL.$datestamp

echo -e "\ndelete archived files older than $FileAge days"
find $ARCHDIR/$INFIL* -mtime $FileAge -print |
	while read FILE1
	do
	echo "removing file $FILE1"
	rm -f $FILE1
	done

	exit 0

	else

echo -e "\nftp submit of job $JCL to MVS failed\n"
	exit 8

	fi

	else

echo -e "\nThe $INFIL file received from Trisept was empty removing file"
rm -f $INDIR/$INFIL

	exit 0

	fi
