#!/bin/sh

############################################################
#  PUT AS RESERVATION FILES (AS*L, AS*2) TO ftpprod        #
############################################################
#  This script is trig'd by the existence of file ASZZZZZZ
#  which is FTP'd to this server by Trisept, and indicates
#  a successful xmit of the AS res (Eclipse) files, AS*L &
#  AS*2. The data files are immediately datestamped and
#  copied to the Trisept archive directory and compressed.
#  The files are then FTP'd to asprodftp:\\seavvfile1\ftpprod\  
#  There are 42 files in all that are pushed to asprodftp. 
#############################################################

export airline=AS
export INDIR=$HOME/inbound
export ARCHDIR=$HOME/inbound.archive
export ftp_host=agapps
export ftp_host_test=icstest
export ftp_host_win=asprodftp
export datestamp=`date +%m%d%y.%H%M`
export DONEFIL=${airline}ZZZZZZ
export win_tag=vacresdlyld.tag
export FileAge=50

function mainproc {

cd $INDIR

echo -e "\nremove archived files older than $FileAge days"
find $ARCHDIR/$airline*.* -mtime +$FileAge -print | xargs rm -fv

echo -e "\ntimestamp and compress incoming files"
	find . -name "$airline*" -print |
        while read FILE1
        do
	echo "\narchiving file $FILE1"
	gzip <$FILE1 >$ARCHDIR/$FILE1.$datestamp.gz
	echo -e "\nrenaming $FILE1 to $FILE1.txt"
	mv -v $FILE1 $FILE1.txt
	$HOME/bin/remove_crlf.pl $FILE1.txt >$FILE1
	rm -fv $FILE1.txt
        done
}

function ftpprd {

touch $win_tag

echo -e "\nftp resfiles to $ftp_host_win"
	ftp -v -i $ftp_host_win <<EOF >ftp_results.$$
	cd AlaskaAir/VACATION_RESDATA
	mput $airline*
	put $win_tag
	bye
EOF
	result=$?

	if [ $result -ne 0 ]; then
echo -e "\nftp resfiles to $ftp_host_win failed"
cat ftp_results.$$
rm -fv ftp_results.$$ $win_tag
	exit 4
	fi

echo -e "\nresults of ftp resfiles to $ftp_host_win:"
cat ftp_results.$$

echo -e "remove ftp_results.$$ $win_tag"
rm -fv ftp_results.$$ $win_tag

}

function ftptest {

echo -e "\nftp files to $ftp_host_test:/tmp/resfiles"
	ftp -v -i $ftp_host_test <<EOF >ftp_results.t$$
	cd /tmp/resfiles
	mput $airline*
	bye
EOF

rm -fv ftp_results.t$$

}

function ftpprod {
echo -e "\nftp files to $ftp_host:/tmp/resfiles"
	ftp -v -i $ftp_host <<EOF >ftp_results.$$
	cd /tmp/resfiles
	mput $airline*
	bye
EOF

succftp=`cat ftp_results.$$ | grep -c "Transfer complete"`
echo -e "\n$succftp files were successfully transferred to AGAPPS"

	if [ $succftp -lt 42 ]; then
echo "<<EOFMSG
The reservation files were not tranferred to AGAPPS successfully.
Only $succftp of 42 files were successfully sent.
Please investigate or notify Ops Analyst.
`cat ftp_results.$$`
EOFMSG"
rm -fv ftp_results.$$
	exit 8
	fi

echo -e "\nremove tag file $DONEFIL and data files"
rm -fv $DONEFIL ftp_results.$$ $airline*

}

echo -e "\nBegin processing for $airline\n"
mainproc
ftptest
ftpprd
ftpprod
echo -e "\nProcessing for $airline complete\n"
