#!/bin/sh

export airline=AS
export INDIR=$HOME/inbound
export ARCHDIR=$HOME/inbound.archive
export ftp_host=icstest
export PUTFIN=$airline*

cd $INDIR

echo -e "\nprocess new trisept files"
	find . -name "$airline*" -print |
        while read FILE1
        do
	echo -e "\nrenaming $FILE1 to $FILE1.txt"
	mv $FILE1 $FILE1.txt
	echo -e "remove crlf"
	$HOME/bin/remove_crlf.pl $FILE1.txt >$FILE1
#	rm -fv $FILE1.txt
        done

echo -e "\nftp files to $ftp_host:/tmp/resfiles"
	ftp -v -i $ftp_host <<EOF >ftp_results.t$$
	cd /tmp/resfiles
	mput $PUTFIN
	bye
EOF

rm -f ftp_results.$$
