#!/bin/sh

export ftp_host=appprod6
export INDIR=/ftphome/trisept/inbound
export ARCHDIR=/ftphome/trisept/inbound.archive
export INFIL=apascdat
export OUTFIL=trisept_asc.dat
export DONEFILE=apascdne
export TAG=trisept_asc_release
export datestamp=`date +%m%d%y.%H%M`
export MLDOM=@alaskaair.com
export MLLIST="dean.liebrich$MLDOM"
export FileAge=20

######################################################
#  This script is trig'd by the existence of file
#  apascdne.  This file is FTP'd to this server by
#  Trisept and indicates a successful xmit of data file
#  file APASCDAT.  A datestamped done file is then
#  is FTP'd to APPPROD6 named trisept_asc_release.  This 	
#  will satisfy an opens dependency for TWS job 
#  
    
cd $INDIR

echo -e "\ntimestamp and copy $INFIL to $ARCHDIR"
cp $INFIL $ARCHDIR/$INFIL.$datestamp
gzip $ARCHDIR/$INFIL.$datestamp

echo -e "\nftp $INFIL file to $ftp_host as $OUTFIL" 
ftp -v $ftp_host <<EOF >ftp_results.$$
cd /appl/fin/interfaces/ap/data
put $INFIL $OUTFIL 
bye 
EOF
	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP of $INFIL to $ftp_host failed"
	cat ftp_results.$$
	rm -f ftp_results.$$
	exit 8
	fi

cat ftp_results.$$
rm -f ftp_results.$$
 
echo -e "\nwrite datestamp to $ftp_host tag file"
echo "apascdat received $datestamp" > $TAG

echo -e "\nftp $TAG to $ftp_host"
ftp -v $ftp_host <<EOF1 >ftp_results.$$
cd /appl/fin/interfaces/ap/data
put $TAG
bye
EOF1

	result=$?

	if [ $result -ne 0 ]; then
	echo "FTP of file trisept_asc_release to $ftp_host failed"
	cat ftp_results.$$
	rm -f ftp_results.$$
	exit 8
	fi 

cat ftp_results.$$

echo -e "\nclean up data directory"
rm -f ftp_results.$$ $TAG $INFIL $DONEFILE

echo -e "\nremove files older than $FileAge days"
find $ARCHDIR/$INFIL.* -mtime +$FileAge -print |
	while read FILE1
        do
	echo "removing file $FILE1"
	rm -f $FILE1
        done
