#!/bin/sh

############################################################
#  PUT AS RESERVATION FILES TO FTPTEST                     #
############################################################

export INDIR=$HOME/inbound
export ARCHDIR=$HOME/inbound.archive
export ftp_host=testftp
export datestamp=`date +%m%d%y.%H%M`
export PUTFIL=$airline*L
export PUTFIL2=$airline*2
export FileAge=50

cd $INDIR

gzip $PUTFIL
gzip $PUTFIL2

echo -e "\nftp files to $ftp_host"
	ftp -v -i $ftp_host <<EOF >ftp_results.$$
	bin
	cd Vacations
	mput $PUTFIL.gz
	mput $PUTFIL2.gz
	bye
EOF

succftp=`cat ftp_results.$$ | grep -c "Transfer complete"`
echo -e "\n$succftp files were successfully transferred to AGAPPS"

# if 42 files were transferred then do cleanup #
	if [ $succftp -lt 42 ]; then

echo "<<EOFMSG
The reservation files were NOT tranferred to $ftp_host successfully.
Only $succftp of 42 files were successfully sent.
Please investigate.
`cat ftp_results.$$`
EOFMSG" | Mail -s "new Trisept to Vacations feed" dean.liebrich@alaskaair.com

rm -fv ftp_results.$$
	exit 8
	else

echo -e "\ncleaning up data directory"
rm -fv ftp_results.$$ $PUTFIL.gz $PUTFIL2.gz
	fi
