#!/bin/sh

###########################################################
#  PUT AS RF COMMISSION FILE (cmasdata) TO MVS DATASET    #
#  RF.RFASCRCV.AS.COMMISSN AND TRIGGER RFASCRCV           #
###########################################################
#  This script is trig'd by the existence of file cmasdone
#  which is FTP'd to this server by Trisept and indicates 
#  a successful xmit of AS ReFunds Commission data file,
#  cmasdata.  If the input file is empty, the script will
#  just exit.  Otherwise the file is ftp'd to MVS dataset
#  RF.RFASCRCV.AS.COMMISSN.  JCL is then submitted to the  
#  MVS internal reader to trigger CA7 job RFASCRCV.
#  The input file cmasdata is then timestamped, moved to the  
#  archive directory, and compressed.
#########################################################
   
INDIR=/ftphome/trisept/inbound
ARCHDIR=/ftphome/trisept/inbound.archive
INFIL=cmasdata
JCL=$HOME/bin/rfascrcv.jcl
dataset=rf.rfascrcv.as.commissn
datestamp=`date +%m%d%y.%H%M`
FileAge=14

echo "removing done file"
rm -f $INDIR/cmasdone

	if [ -s $INDIR/$INFIL ]; then

echo "ftp $INFIL to MVS dataset $dataset"
ftp -v 159.49.42.28 <<EOF >ftp_results.$$
site recfm=fb lrecl=710 cylinders pri=1 sec=10 blksize=0 unit=prdda
put $INDIR/$INFIL '$dataset' 
bye
EOF

succftp=`grep -c "Transfer complete" ftp_results.$$`

	if [ $succftp -ge 1 ]; then
rm -f ftp_results.$$

echo "submit jcl $JCL to MVS"
ftp -v 159.49.42.28 <<EOF1 >ftp_results.$$
site file=jes
put $JCL 
bye
EOF1

	else 
echo "ftp of $INFIL to MVS failed"
	exit 8
	fi

cat ftp_results.$$
succftp=`grep -c "Transfer complete" ftp_results.$$` 

	if [ $succftp -eq 1 ]; then

rm -f ftp_results.$$

echo "move $INFIL to $ARCHDIR/$INFIL.$datestamp"

mv $INDIR/$INFIL $ARCHDIR/$INFIL.$datestamp
gzip $ARCHDIR/$INFIL.$datestamp

echo "delete archived files older than $FileAge days"

find $ARCHDIR/$INFIL* -mtime +$FileAge -print |
      while read FILE1
      do
      echo "removing file $FILE1"
      rm -f $FILE1
      done

exit 0

	else

echo " ftp submit of job $JCL to MVS failed"
echo "RFASCMGT failed" | Mail -s "RFASCMGT" dean.liebrich@alaskaair.com
exit 8

	fi
fi

echo "The $INFIL file received from Trisept was empty removing file"
rm -f $INDIR/$INFIL

exit 0
