#!/bin/bash

# Encrypt the AS data file to ftp to 
# Set the environment variables
#

program=`basename $0`

export pgp_signature="Horizon/Alaska Employee Loader"
export PGPPASS=seavvdmzftp
export ftp_local_host=testftp	#test
#export ftp_local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export basename=wbat_test_poc
export alert_recipient=dean.liebrich@alaskaair.com
export datestamp=`date +%b%d%Y.%H%M`
export info_to="dean.liebricha@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=10
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

function mainproc {

cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\nget $data_file from $ftp_local_host"
ftp_vendor_get $ftp_local_host $data_file $data_file "cd $local_dir"

echo -e "\nencrypt `whoami` file $data_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor --sign -r "$pgp_signature" --output $data_pgp_file --encrypt $data_file >pgp_transcript.$$ 2>&1

	result=$?

	if [ $result -ne 0 ]; then
echo -e "\nencryption failed for `whoami` file $data_file, contact Prod. Svcs.\n"
cat pgp_transcript.$$
rm pgp_transcript.$$
	exit 4
	fi

cat pgp_transcript.$$
rm pgp_transcript.$$

echo -e "\nput file $data_file to $vendor_host"
sftp -v $vendor_host <<PUT >ftp_results.$$
bin
put $data_pgp_file
dir
bye
PUT
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nsftp of $data_file to $vendor_host failed"
	cat $ftp_results.$$
	rm -f $ftp_results.$$
	exit 4
	fi 

cat ftp_results.$$
rm -f ftp_results.$$

archive_clean $outbound_archive $data_file $FileAge

securezip $data_file outbound

echo -e "\nclean up temp files"
rm -f $data_file $data_pgp_file

}

export airline=$1

	if [ -z $airline ]; then
echo -e "\n	Missing airline parm.
	proper syntax is: put_wbat_data airline,
	where airline=AS or QX\n"
	exit 4
	fi

case "$airline" in

	AS)

export data_file=${basename}_as.xml
export data_pgp_file=${basename}_as.asc
export vendor_host=alaskaupload@upload.wbat.org:incoming
export local_dir="safety/wbat/AS"

echo -e "\nbegin processing file $data_file for $airline"
mainproc
echo -e "\nend `whoami` processing for $data_file"

	;;

	QX)

export data_file=${basename}_qx.xml
export data_pgp_file=${basename}_qx.asc
export vendor_host=horizonupload@upload.wbat.org:incoming
export local_dir="safety/wbat/QX"

echo -e "\nbegin processing file $data_file for $airline"
mainproc
echo -e "\nend `whoami` processing for $data_file"

	;;

esac


#export data_file=wbat_aircraft.xml

#echo -e "\nbegin processing file $data_file"
#mainproc
#echo -e "\nend `whoami` processing for $data_file"
