#!/bin/bash

# Set up the Fidelity data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/fidelity_environment"

export vendor_host=horizonupload@upload.wbat.org:incoming
#export ftp_local_host=asprodftp
export ftp_local_host=asprodftp
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export alert_recipient=dean.liebrich@alaskaair.com
export datestamp=`date +%b%d%Y.%H%M`
export info_to="dean.liebricha@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=10
export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

function mainproc {

cd $outbound_dir

echo -e "\ncopy $datafile to $outbound_archive/$datafile.$datestamp"
cp $datafile $outbound_archive/$datafile.$datestamp

ftp_check $ftp_local_host

echo -e "\nget $datafile from $ftp_local_host"
ftp_vendor_get $ftp_local_host $datafile $datafile "cd safety/wbat"

echo -e "\nput file $datafile to $vendor_host"
sftp -v $vendor_host <<PUT >ftp_results.$$
put $datafile
dir
bye
PUT
	result=$?

	if [ $result -ne 0 ]; then
	echo -e "\nsftp of $datafile to $vendor_host failed"
	cat $ftp_results.$$
	rm -f $ftp_results$$
	exit 4
	fi 

cat ftp_results.$$
rm -f $ftp_results.$$

archive_clean $outbound_archive $datafile $FileAge

}
