#!/bin/bash

# FTP MP handback file to vinesse

# Set environment values
. $HOME/bin/vinesse_environment
program=`basename $0`

cd $outbound_dir

ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix

export solar_file=`ls -1 $oufile_prefix*`
echo -e "\nprocessing outbound file $solar_file"

echo -e "\nmake record length 150 for all records"
$HOME/bin/150.pl $solar_file >$out_data_file
	result=$?

	if [ $result -ne 0 ]; then
	echo -e  "\nchange record length failed, contact EPS"
	exit 4
	fi

echo -e "\nEncrypt Alaska to vinesse file $out_data_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor -r "$pgp_remote_signature" --output $out_pgp_data --encrypt $out_data_file > pgp_transcript.$$

	result=$?	

	if [ $result -ne 0 ]; then
	echo -e "\nEncryption error on Alaska to vinesse file $out_data_file,
	notify EPS during normal business hours\n"
	cat pgp_transcript.$$
	rm -f pgp_transcript.$$
	exit 4
	fi

#ftp_vendor_chk $ftp_host
#ftp_vendor $ftp_host $out_pgp_data $out_pgp_data 


echo -e "\nput  $data_file on Vinesse server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd Alaska
       	put $out_pgp_data $out_pgp_data
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$


securezip $solar_file outbound

ftp_delete $ftp_local_host VNVINESSEPIT* "cd mpprod/outbound/handback"

echo -e "\nclean up outbound directory"
rm -f $solar_file $out_pgp_data $out_data_file rm pgp_transcript.$$ 

archive_clean $outbound_archive $outfile_prefix $FileAge
