#!/bin/bash

program=`basename $0`

. $HOME/bin/vsp_environment

	#export vsp_file=t4399172		#test
	export vsp_file=g4399172		#prod
	export data_file=${vsp_file}.dat
	export pgp_file=${vsp_file}.pgp
	#export tagfile=$hcmdir/t4399172.tag 	#test
	export tagfile=$hcmdir/g4399172.tag 	#prod

echo -e "\nBegin processing Vison Service Plan for Alaska Air"

vspproc

echo -e "\nVison Service Plan data transfer for Alaska Air complete"
