#!/bin/bash

# Set up the wadental data transfer environment
# This script is used by other scripts to preset values from a common source.
# Usage: (in another script) ". $HOME/bin/wadental_environment"

export PGPPASS=seavvdmzftp
export pgp_remote_signature="wds_pgp@deltadentalwa.com"
export ftp_host=ftp3.deltadentalwa.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export filedate=`/bin/date +%Y%m%d`
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export tagfile=wadentservice.tag
export hcmdir=/home/hcmprod/outbound/wadental
export inbound_archive=${inbound_dir}.archive
export alert_recipient=dean.liebrich@alaskaair.com
export wadental_mailto="joanne.gies@alaskaair.com,cmitchell@deltadentalwa.com"
export debug_to="dean.liebrich@alaskaair.com,joanne.gies@alaskaair.com"
export info_to="dean.liebrich@alaskaair.com,joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20

. /opt/local/ops_scripts/function_lib

function mainproc { 

cd $outbound_dir

cp $hcmdir/$datafile $outbound_dir

	result=$?

        if [ $result -ne 0 ]; then
        echo -e "\nget $datafile from $hcmdir failed"
	echo "contents of $hcmdir:"
	ls -l $hcmdir
        exit 4
        fi

echo -e "\nbegin processing for $data_file file"

echo -e "\nencrypting file $data_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v --armor -r "$pgp_remote_signature" --output $pgpfile --encrypt $datafile >pgp_transcript.$$
	
	result=$?

	if [ ! -s $pgpfile -o $result -ne 0 ]; then
	echo -e "\n$datafile encryption failure, contact Production Analyst" 
	cat pgp_transcript.$$
	rm pgp_transcript.$$
	exit 4
	fi

ftp_vendor $ftp_host $pgpfile $pgpfile bin

securezip $datafile outbound

echo -e "\nremoving temporary files"
rm -f $pgpfile $datafile $hcmdir/$datafile $hcmdir/$tagfile pgp_transcript.$$

archive_clean $outbound_archive $datafile $FileAge

echo -e "\nEnd of processing for file $datafile"
 
}
