#!/bin/bash

# Check for and then archive the West Coast Hotels data file
# put file on seavvfile1
#

export ftp_local_host=asprodftp
export lz=mpprod
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
export local_file=WCWESTCOASTHOTELSPIT.txt
export info_to="joanne.gies@alaskaair.com"
export FileAge=15
program=`basename $0`

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

data_file=`ls -1 H*.txt`
echo -e "\nBegin processing file $data_file for `whoami`"

# rename local file for SOLAR conv (see if we can get Vendor to put file as Solar name)
mv $data_file $local_file

ftp_check $ftp_local_host
ftp_solar_in $ftp_local_host $local_file

securezip $local_file inbound

echo -e "\nClean up inbound dirctory"
rm -f $local_file ftp_results.$$ $mvs_file

archive_clean $inbound_archive $local_file $FileAge

