#!/bin/bash

export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export alert_recipient=joanne.gies@alaskaair.com
export datestamp=`/bin/date +%b%d%Y.%H%M`
export errors_to="systems.management@alaskaair.com"
export FileAge=30

. /opt/local/ops_scripts/function_lib

cd $inbound_dir

ftp_check $ftp_local_host 

	ls -1 *.del | while read FILE1
     	do
# the following determines the file name with the datestamp removed
export namecount=`echo $FILE1 |wc |awk '{print $3}'`
let cutamt1=$namecount-12
let cutamt2=$namecount-5
export datename=`echo $FILE1 | cut -c$cutamt1-$cutamt2`
export newname=`echo $FILE1 | sed -e "s/$datename//"`

ftp_file $ftp_local_host $FILE1 $newname "cd AlaskaAir/WestData"

securezip $FILE1 inbound

rm -fv $FILE1
	done

archive_clean $inbound_archive .del. $FileAge
