#!/bin/bash

echo -e "\ncheck connectivity to $sftp_host" 
	sftp -v alaskair@sftp.workflowone.com <<CHECK >ftp_results.$$
        quit
CHECK

	result=$?
	ftpcheck=`grep -c sftp ftp_results.$$`

	if [ $result -ne 0 -o $ftpcheck -lt 1 ]; then
	echo -e "\nunable to connect to $sftp_host\n"
	cat ftp_results.$$
	rm -fv ftp_results.$$
	exit 4
	fi

echo -e "\nconnectivity to $sftp_host confirmed, processing continues..."
