#!/bin/bash

program=`basename $0`

. $HOME/bin/workflow_environment

export mailing=$1

#make sure mailing parm was passed as first arg
	if [ -z $mailing ]; then
echo -e "\n Missing mailing parm.  Proper syntax
is put_workflow_data mailing, where mailing
is equal to br, cards, or cargo."
	exit 4
	fi

case "$mailing" in
br)
	export datafile=BR_Renewal_Notices.csv
	export filedir=/mpprod/outbound/workflowone/BR_Notices
        export sftp_host=joannegies@sftp.wrightimg.com
br_notices
;;

awb)
	export filedir=/Cargospot/awb
        export sftp_host=joannegies@sftp.wrightimg.com
awb
;;

cargo)
	export filedir=/Cargospot/invoices
        export sftp_host=joannegies@sftp.wrightimg.com
cargo
;;

cards)
	export filedir=/mpprod/outbound/workflowone/Cardfile
        export sftp_host=AAIRLINES@secure.denverips.com
cards
;;

bagtag)
	export filedir=/alaskaair_web/selftag/
        export sftp_host=alaskair@sftp.workflowone.com
        export tag=HOLDER_EXTRACT_TAG.TXT
bagtag
;;

esac

echo -e "\nWorkflow data transfer for Alaska Air complete"

#Mail -s "Workflow data files sent to $ftp_host at `date`" $mailto </dev/null
