#!/bin/bash

set -x

# Set up the WOTC data transfer environment

export PGPPASS=seavvdmzftp
export remote_sig="430-ALASKA AIRLINES"
export sftp_host=alaskaair.upload@gossft.ey.com
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export hcmdir_out=/home/hcmprod/outbound/wotc
export alert_recipient=joanne.gies@alaskaair.com
export filepref=aagey
export dir=To_EY
export datestamp=`/bin/date "+%Y%m%d"`
#export infor_to="joanne.gies@alaskaair.com"
export logfile=$HOME/transfer_log
export FileAge=20

export ops=/opt/local/ops_scripts

. /opt/local/ops_scripts/function_lib

cd $hcmdir_out

ls -1 ${filepref}*.csv |
	while read FILE1
	do
	export datafile=$FILE1
	export tagfile=`echo $FILE1 | sed -e 's/csv/tag/'`


echo -e "\nget $datafile from $hcmdir_out"
cp -p $hcmdir_out/$datafile $outbound_dir

securezip $datafile outbound 

cd $outbound_dir


export remotefile=`echo $FILE1 | sed -e 's/.csv//'`

export outfile=${remotefile}_$datestamp.csv.pgp

data_records=`wc -l $datafile | awk '{print $1}'`

echo -e "\nencrypt $data_file"
echo $PGPPASS | gpg --passphrase-fd 0 --batch -v -r "$remote_sig" --output $outfile --encrypt $datafile >gpg_transcript.$$

	result=$?

	if [ $result -ne 0 ]; then
	echo "Ernst Young data file encryption failure, contact Production Services."
	cat gpg_transcript.$$
	rm -fv gpg_transcript.$$
  	exit 8
	fi

rm -fv gpg_transcript.$$


echo -e "\nput  $outfile to Ernst Young server" 
	sftp -v $sftp_host <<GETDATA >ftp_results.$$ 2>&1
        cd $dir
       	put $outfile $outfile
        quit
GETDATA

cat ftp_results.$$
rm -fv ftp_results.$$

data_records=`wc -l $outfile | awk '{print $1}'`
echo -e "\n$datestamp: there were $data_records records sent to Ernst and Young" 


#echo -e "\nRemove $datafile and $tagfile"
rm -fv $hcmdir_out/$tagfile $hcmdir_out/$datafile
rm $outfile $datafile

	done

archive_clean outbound $basename $FileAge





