#!/bin/bash

#This script is for the partner miles that Wyndham sends us once
#a week. It also includes - us sending them a handback file.
#Job names are: FFWYNDHAM_IN and FFWYNDHAM_PUT

set -x
export pgppass=seavvdmzftp
export pgp_rem_sig="30DA6CFA"
export sftp_host=chanthni@198.246.150.12
export ftp_local_host=asprodftp
#export ftp_local_host=testftp
export inbound_dir=$HOME/inbound
export inbound_archive=${inbound_dir}.archive
export outbound_dir=$HOME/outbound
export outbound_archive=${outbound_dir}.archive
export datestamp=`/bin/date +%b%d%Y.%H%M`
#export indate=`date +%Y%m%d%H%M`
export outdate=`date +%Y%m%d_%H%M%S`
export info_to="joanne.gies@alaskaair.com,dean.liebricha@alaskaair.com"
export FileAge=14

. /opt/local/ops_scripts/function_lib

direction=$1

#make sure direction parm was passed in as first arg
        if [ -z $direction ]; then
echo -e "\n     Missing direction parm.
        proper syntax is: process_wyndham_data direction where
        direction equals wynd_in or wynd_out\n"
        exit 4
        fi

function outproc {

cd $outbound_dir

ftp_check $ftp_local_host

echo -e "\ncheck for ftp connectivity to $sftp_host"
	sftp -v $sftp_host <<TEST >ftp_results.$$
	pwd
	bye
TEST

ftptest=`grep -i -c -e "Remote working directory" ftp_results.$$`

	if [ $ftptest -lt 1 ]; then
echo -e "\nUNABLE TO OPEN SFTP SESSION TO $sftp_host\n"
	cat ftp_results.$$
	rm ftp_results.$$
	exit 4
	else
echo -e "\nconnection to $sftp_host confirmed, processing continues...\n"
rm ftp_results.$$
	fi

#ftp_check $ftp_local_host
ftp_solar_out $ftp_local_host $outfile_prefix

export solar_file=`ls -1 $outfile_prefix*`
echo -e "\nprocessing outbound file $solar_file"

echo $solar_file

securezip $solar_file outbound

export out_file=AS_RESP_${outdate}.txt
export out_file_pgp=${out_file}.pgp

mv $solar_file  $out_file

echo $pgppass | gpg --passphrase-fd 0 --batch --armor -r $pgp_rem_sig --output $out_file_pgp --encrypt $out_file >pgp_transcript.$$ 2>&1
errorchk $? "encrypt outbound $out_file for `whoami`"


echo -e "\nsftp $out_file_pgp to $sftp_host"
	sftp -v $sftp_host <<PUT >ftp_results.$$
        cd incoming
       	put $out_file_pgp
        dir
	bye
PUT
errorchk $? "ftp data files to $sftp_host"

ftp_delete $ftp_local_host $solar_file "cd mpprod/outbound/handback"

echo -e "\nremove $data_file files from $outbound_dir"
rm -fv pgp_transcript.$$ $out_file $out_file_pgp
errorchk $? "remove $solar_file from $outbound_dir"

archive_clean $outbound_archive $outfile_prefix $FileAge

}

function inproc {

cd $inbound_dir

ftp_check $ftp_local_host

export pgp_file=`ls -1 $in_file_pref*`

echo $pgppass | gpg --passphrase-fd 0 --batch --output $local_file --decrypt $pgp_file >pgp_transcript.$$ 2>&1 
errorchk $? "decrypt $pgp_file for inbound `whoami`"

mv -fv $pgp_file $inbound_archive
errorchk $? "move $pgp_file to $inbound_archive"

#this may not be needed -- from copied script only
#echo -e "\nremove carriage control"
#$HOME/bin/remove_crlf.pl $local_tmp_file >$local_file
#errorchk $? "remove carriage control"

ftp_solar_in $ftp_local_host $local_file

echo "remove temp files"
rm -fv $local_file pgp_transcript.$$ $pgp_file
errorchk $? "remove temp files from $inbound_dir"

archive_clean $inbound_archive $in_file_pref $FileAge

}

case "$direction" in 

	wynd_in)

export in_file_pref=AS_TRAN
#export local_tmp_file=WYWYNDHAM.tmp
export local_file=WYWYNDHAMPIT.txt
echo -e "\nBegin processing for Autopost 'in' file"
inproc
echo -e "\nProcessing for Miles from Wyndham autopost 'in' complete"
	;;

        wynd_out)

export lz=mpprod
export outfile_prefix=WYWYNDHAMPIT
#export chgdir="cd /asaa/aadvantage/hfasprod/./striplf/lrecl=300"
echo -e "\nBegin processing for $outfile_prefix"
outproc
echo -e "\nProcessing for handback mls to Wyndham for complete"
	;;

esac
